#include "librpc/gen_ndr/ndr_samr.h"
#ifndef __SRV_SAMR__
#define __SRV_SAMR__
NTSTATUS _samr_Connect(struct pipes_struct *p, struct samr_Connect *r);
NTSTATUS _samr_Close(struct pipes_struct *p, struct samr_Close *r);
NTSTATUS _samr_SetSecurity(struct pipes_struct *p, struct samr_SetSecurity *r);
NTSTATUS _samr_QuerySecurity(struct pipes_struct *p, struct samr_QuerySecurity *r);
NTSTATUS _samr_Shutdown(struct pipes_struct *p, struct samr_Shutdown *r);
NTSTATUS _samr_LookupDomain(struct pipes_struct *p, struct samr_LookupDomain *r);
NTSTATUS _samr_EnumDomains(struct pipes_struct *p, struct samr_EnumDomains *r);
NTSTATUS _samr_OpenDomain(struct pipes_struct *p, struct samr_OpenDomain *r);
NTSTATUS _samr_QueryDomainInfo(struct pipes_struct *p, struct samr_QueryDomainInfo *r);
NTSTATUS _samr_SetDomainInfo(struct pipes_struct *p, struct samr_SetDomainInfo *r);
NTSTATUS _samr_CreateDomainGroup(struct pipes_struct *p, struct samr_CreateDomainGroup *r);
NTSTATUS _samr_EnumDomainGroups(struct pipes_struct *p, struct samr_EnumDomainGroups *r);
NTSTATUS _samr_CreateUser(struct pipes_struct *p, struct samr_CreateUser *r);
NTSTATUS _samr_EnumDomainUsers(struct pipes_struct *p, struct samr_EnumDomainUsers *r);
NTSTATUS _samr_CreateDomAlias(struct pipes_struct *p, struct samr_CreateDomAlias *r);
NTSTATUS _samr_EnumDomainAliases(struct pipes_struct *p, struct samr_EnumDomainAliases *r);
NTSTATUS _samr_GetAliasMembership(struct pipes_struct *p, struct samr_GetAliasMembership *r);
NTSTATUS _samr_LookupNames(struct pipes_struct *p, struct samr_LookupNames *r);
NTSTATUS _samr_LookupRids(struct pipes_struct *p, struct samr_LookupRids *r);
NTSTATUS _samr_OpenGroup(struct pipes_struct *p, struct samr_OpenGroup *r);
NTSTATUS _samr_QueryGroupInfo(struct pipes_struct *p, struct samr_QueryGroupInfo *r);
NTSTATUS _samr_SetGroupInfo(struct pipes_struct *p, struct samr_SetGroupInfo *r);
NTSTATUS _samr_AddGroupMember(struct pipes_struct *p, struct samr_AddGroupMember *r);
NTSTATUS _samr_DeleteDomainGroup(struct pipes_struct *p, struct samr_DeleteDomainGroup *r);
NTSTATUS _samr_DeleteGroupMember(struct pipes_struct *p, struct samr_DeleteGroupMember *r);
NTSTATUS _samr_QueryGroupMember(struct pipes_struct *p, struct samr_QueryGroupMember *r);
NTSTATUS _samr_SetMemberAttributesOfGroup(struct pipes_struct *p, struct samr_SetMemberAttributesOfGroup *r);
NTSTATUS _samr_OpenAlias(struct pipes_struct *p, struct samr_OpenAlias *r);
NTSTATUS _samr_QueryAliasInfo(struct pipes_struct *p, struct samr_QueryAliasInfo *r);
NTSTATUS _samr_SetAliasInfo(struct pipes_struct *p, struct samr_SetAliasInfo *r);
NTSTATUS _samr_DeleteDomAlias(struct pipes_struct *p, struct samr_DeleteDomAlias *r);
NTSTATUS _samr_AddAliasMember(struct pipes_struct *p, struct samr_AddAliasMember *r);
NTSTATUS _samr_DeleteAliasMember(struct pipes_struct *p, struct samr_DeleteAliasMember *r);
NTSTATUS _samr_GetMembersInAlias(struct pipes_struct *p, struct samr_GetMembersInAlias *r);
NTSTATUS _samr_OpenUser(struct pipes_struct *p, struct samr_OpenUser *r);
NTSTATUS _samr_DeleteUser(struct pipes_struct *p, struct samr_DeleteUser *r);
NTSTATUS _samr_QueryUserInfo(struct pipes_struct *p, struct samr_QueryUserInfo *r);
NTSTATUS _samr_SetUserInfo(struct pipes_struct *p, struct samr_SetUserInfo *r);
NTSTATUS _samr_ChangePasswordUser(struct pipes_struct *p, struct samr_ChangePasswordUser *r);
NTSTATUS _samr_GetGroupsForUser(struct pipes_struct *p, struct samr_GetGroupsForUser *r);
NTSTATUS _samr_QueryDisplayInfo(struct pipes_struct *p, struct samr_QueryDisplayInfo *r);
NTSTATUS _samr_GetDisplayEnumerationIndex(struct pipes_struct *p, struct samr_GetDisplayEnumerationIndex *r);
NTSTATUS _samr_TestPrivateFunctionsDomain(struct pipes_struct *p, struct samr_TestPrivateFunctionsDomain *r);
NTSTATUS _samr_TestPrivateFunctionsUser(struct pipes_struct *p, struct samr_TestPrivateFunctionsUser *r);
NTSTATUS _samr_GetUserPwInfo(struct pipes_struct *p, struct samr_GetUserPwInfo *r);
NTSTATUS _samr_RemoveMemberFromForeignDomain(struct pipes_struct *p, struct samr_RemoveMemberFromForeignDomain *r);
NTSTATUS _samr_QueryDomainInfo2(struct pipes_struct *p, struct samr_QueryDomainInfo2 *r);
NTSTATUS _samr_QueryUserInfo2(struct pipes_struct *p, struct samr_QueryUserInfo2 *r);
NTSTATUS _samr_QueryDisplayInfo2(struct pipes_struct *p, struct samr_QueryDisplayInfo2 *r);
NTSTATUS _samr_GetDisplayEnumerationIndex2(struct pipes_struct *p, struct samr_GetDisplayEnumerationIndex2 *r);
NTSTATUS _samr_CreateUser2(struct pipes_struct *p, struct samr_CreateUser2 *r);
NTSTATUS _samr_QueryDisplayInfo3(struct pipes_struct *p, struct samr_QueryDisplayInfo3 *r);
NTSTATUS _samr_AddMultipleMembersToAlias(struct pipes_struct *p, struct samr_AddMultipleMembersToAlias *r);
NTSTATUS _samr_RemoveMultipleMembersFromAlias(struct pipes_struct *p, struct samr_RemoveMultipleMembersFromAlias *r);
NTSTATUS _samr_OemChangePasswordUser2(struct pipes_struct *p, struct samr_OemChangePasswordUser2 *r);
NTSTATUS _samr_ChangePasswordUser2(struct pipes_struct *p, struct samr_ChangePasswordUser2 *r);
NTSTATUS _samr_GetDomPwInfo(struct pipes_struct *p, struct samr_GetDomPwInfo *r);
NTSTATUS _samr_Connect2(struct pipes_struct *p, struct samr_Connect2 *r);
NTSTATUS _samr_SetUserInfo2(struct pipes_struct *p, struct samr_SetUserInfo2 *r);
NTSTATUS _samr_SetBootKeyInformation(struct pipes_struct *p, struct samr_SetBootKeyInformation *r);
NTSTATUS _samr_GetBootKeyInformation(struct pipes_struct *p, struct samr_GetBootKeyInformation *r);
NTSTATUS _samr_Connect3(struct pipes_struct *p, struct samr_Connect3 *r);
NTSTATUS _samr_Connect4(struct pipes_struct *p, struct samr_Connect4 *r);
NTSTATUS _samr_ChangePasswordUser3(struct pipes_struct *p, struct samr_ChangePasswordUser3 *r);
NTSTATUS _samr_Connect5(struct pipes_struct *p, struct samr_Connect5 *r);
NTSTATUS _samr_RidToSid(struct pipes_struct *p, struct samr_RidToSid *r);
NTSTATUS _samr_SetDsrmPassword(struct pipes_struct *p, struct samr_SetDsrmPassword *r);
NTSTATUS _samr_ValidatePassword(struct pipes_struct *p, struct samr_ValidatePassword *r);
void samr_get_pipe_fns(struct api_struct **fns, int *n_fns);
struct rpc_srv_callbacks;
NTSTATUS rpc_samr_init(const struct rpc_srv_callbacks *rpc_srv_cb);
NTSTATUS rpc_samr_shutdown(void);
#endif /* __SRV_SAMR__ */
