#!/usr/bin/env python

bld.SAMBA_LIBRARY('service',
	source='service.c service_stream.c service_named_pipe.c service_task.c',
	autoproto='service_proto.h',
	deps='tevent MESSAGING samba_socket RPC_NDR_IRPC NDR_NAMED_PIPE_AUTH NAMED_PIPE_AUTH_TSTREAM gssapi credentials LIBTSOCKET LIBSAMBA_TSOCKET process_model',
	private_library=True
	)


bld.SAMBA_SUBSYSTEM('PIDFILE',
	source='pidfile.c',
	deps='talloc',
	autoproto='pidfile.h'
	)


bld.SAMBA_BINARY('samba',
	source='server.c',
	manpages='samba.8',
	subsystem_name='service',
	deps='''events process_model service samba-hostconfig samba-util POPT_SAMBA PIDFILE
                popt gensec registry ntptr ntvfs share cluster COMMON_SCHANNEL SECRETS''',
	pyembed=True,
	install_path='${SBINDIR}'
	)




bld.SAMBA_MODULE('process_model_single',
                 source='process_single.c',
                 subsystem='process_model',
                 init_function='process_model_single_init',
                 deps='cluster process_model samba-sockets',
                 internal_module=True
                 )


bld.SAMBA_MODULE('process_model_standard',
                 source='process_standard.c',
                 subsystem='process_model',
                 init_function='process_model_standard_init',
                 deps='events ldbsamba process_model samba-sockets cluster',
                 internal_module=False
                 )


bld.SAMBA_MODULE('process_model_thread',
                 source='process_thread.c',
                 subsystem='process_model',
                 init_function='process_model_thread_init',
                 enabled=False,
                 deps='pthread samba-sockets cluster process_model',
                 internal_module=False
                 )


bld.SAMBA_MODULE('process_model_prefork',
                 source='process_prefork.c',
                 subsystem='process_model',
                 init_function='process_model_prefork_init',
                 deps='events ldbsamba cluster samba-sockets process_model',
                 internal_module=False
                 )

bld.SAMBA_MODULE('process_model_onefork',
                 source='process_onefork.c',
                 subsystem='process_model',
                 init_function='process_model_onefork_init',
                 deps='events ldbsamba process_model cluster samba-sockets',
                 internal_module=False
                 )


bld.SAMBA_LIBRARY('process_model',
                  source='process_model.c',
                  autoproto='process_model_proto.h',
                  deps='samba-util samba-hostconfig',
                  private_library=True
                  )

