.\" Jean Tourrilhes - HPL - 2002 - 2004
.\" wireless.7
.\"
.\" Traduction 2004/02/26 Maxime CHARPENNE (voir
.\" http://www.delafond.org/traducmanfr/)
.\" 1ère traduction        : version 27-pre11 (alpha)
.\" Mise à jour 2004/08/24 : version 27-pre25
.TH WIRELESS 7 "04 mars 2004" "wireless-tools" "Manuel du Programmeur Linux"
.\"
.\" NAME part
.\"
.SH NOM
wireless \- Wireless Tools et Wireless Extensions
.\"
.\" SYNOPSIS part
.\"
.SH SYNOPSIS
.B iwconfig
.br
.B iwpriv \-a
.br
.\"
.\" DESCRIPTION part
.\"
.SH DESCRIPTION
Les
.B Wireless Extensions
sont une API vous permettant de manipuler les interfaces réseaux Wireless LAN.
Ils sont composés d'une gamme d'outils et de fichiers de configuration. Ils sont
plus amplement détaillés dans le Linux Wireless LAN Howto.
.br
Les
.B Wireless Tools
sont utilisés pour changer la configuration des interfaces réseau LAN wireless
à la volée, pour obtenir leur configuration courante, pour avoir des
statistiques et pour les diagnostiquer. Ils sont décrits dans leur propre page
man, voir ci-dessous pour les références.
.br
La
.B configuration Wireless
est propre à chaque distribution Linux. Cette page man contiendra à l'avenir
la procédure de configuration pour quelques distributions les plus communes.
(quand j'en ai les informations nécessaires). Pour le moment, consultez le
fichier DISTRIBUTIONS.txt inclus avec le paquetage Wireless Tools.
.\"
.\" DEBIAN 3.0 part
.\"
.SH DEBIAN 3.0
Dans la Debian 3.0 (et suivante) vous pouvez configurer les périphériques
réseaux LAN wireless en utilisant l'outil de configuration réseau
.BR ifupdown (8).
.TP
.B Fichier :
.I /etc/network/interfaces
.TP
.B Format :
.RI wireless\- "<fonction> <valeur>"
.br
wireless\-essid Maison
.br
wireless\-mode Ad\-Hoc
.TP
.B Voir aussi :
.I /etc/network/if\-pre\-up.d/wireless\-tools
.br
.I /usr/share/doc/wireless\-tools/README.Debian
.\"
.\" SuSE 8.0 part
.\"
.SH SuSE 8.0
La SuSE 8.0 (et suivante) a intégré la configuration wireless dans ses
scripts réseaux.
.TP
.B Outils :
.B Yast2
.TP
.B Fichiers :
.I /etc/sysconfig/network/wireless
.br
.I /etc/sysconfig/network/ifcfg\-*
.TP
.B Format :
.RI WIRELESS_ "<fonction>" = "<valeur>"
.br
WIRELESS_ESSID="Maison"
.br
WIRELESS_MODE=Ad\-Hoc
.TP
.B Voir aussi :
man ifup
.br
info scpm
.\"
.\" PCMCIA part
.\"
.SH SCRIPTS ORIGINAUX PCMCIA
Si vous utilisez les scripts originaux de configuration du paquetage Pcmcia,
vous pouvez utiliser cette méthode.
.TP
.B Fichier :
.I /etc/pcmcia/wireless.opts
.TP
.B Format :
*,*,*,*)
.br
    ESSID="Maison"
.br
    MODE="Ad-Hoc"
.br
    ;;
.TP
.B Voir aussi :
.I /etc/pcmcia/wireless
.br
Le fichier
.I PCMCIA.txt
qui fait partie du paquetage Wireless Tools.
.\"
.\" AUTHOR part
.\"
.SH AUTEUR
Jean Tourrilhes \- jt@hpl.hp.com
.br
.I http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/
.\"
.\" TRADUCTION part
.\"
.SH TRADUCTION
Maxime CHARPENNE, août 2004 (wireless-tools.27-pre25).
.\"
.\" AVERTISSEMENT part
.\"
.SH AVERTISSEMENT SUR LA TRADUCTION
Il est possible que cette traduction soit imparfaite ou périmée. En cas de
doute, veuillez vous reporter au document original en langue anglaise fourni
avec le programme.
.\"
.\" SEE ALSO part
.\"
.SH VOIR AUSSI
.BR iwconfig (8),
.BR iwlist (8),
.BR iwspy (8),
.BR iwpriv (8),
.BR iwevent (8).
