#!/usr/bin/perl
# Diff two subunit streams
# Copyright (C) Jelmer Vernooij <jelmer@samba.org>
#
#  Licensed under either the Apache License, Version 2.0 or the BSD 3-clause
#  license at the users choice. A copy of both licenses are available in the
#  project source as Apache-2.0 and BSD. You may not use this file except in
#  compliance with one of these two licences.
#  
#  Unless required by applicable law or agreed to in writing, software
#  distributed under these licenses is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
#  license you chose for the specific language governing permissions and
#  limitations under that license.

use Getopt::Long;
use strict;
use FindBin qw($RealBin $Script);
use lib "$RealBin/lib";
use Subunit::Diff;

my $old = Subunit::Diff::from_file($ARGV[0]);
my $new = Subunit::Diff::from_file($ARGV[1]);

my $ret = Subunit::Diff::diff($old, $new);

foreach my $e (sort(keys %$ret)) {
	printf "%s: %s -> %s\n", $e, $ret->{$e}[0], $ret->{$e}[1];
}

0;
