#define TK_EOL                             1
#define TK_ASSIGN                          2
#define TK_APPEND                          3
#define TK_LKEY                            4
#define TK_PLUS                            5
#define TK_STRING                          6
#define TK_INTEGER                         7
#define TK_LPARAN                          8
#define TK_RPARAN                          9
#define TK_COMMA                          10
#define TK_ARRAY_ASSIGN                   11
#define TK_GLOBAL                         12
#define TK_LCURLY                         13
#define TK_RCURLY                         14
#define TK_ELSE                           15
#define TK_DOLLAR                         16
#define TK_SRVVARNAME                     17
#define TK_LBRACKET                       18
#define TK_RBRACKET                       19
#define TK_EQ                             20
#define TK_MATCH                          21
#define TK_NE                             22
#define TK_NOMATCH                        23
#define TK_INCLUDE                        24
#define TK_INCLUDE_SHELL                  25
