.\" minidlna.conf man page
.TH minidlna.conf 5 "October 2012"
.SH NAME
minidlna
.SH DESCRIPTION
.PP
.B minidlna
is a light weight but very functional DLNA server. In most cases, the defaults 
do not need modifications. The global configuration file is /etc/minidlna.conf 
but local users without system root access can run minidlna with their own 
configuration file.

.SH OPTIONS
.PP
The following are user configurable options in /etc/minidlna.conf.
minidlna runs by default as user nobody, so make sure system permissions are 
set correctly for read access to media and write access to cache and log dirs.

.IP "\fBfriendly_name\fP"
The name you want your media server seen as, EG: friendly_name=Home Media Server

.IP "\fBport\fP"
.nf
Port for HTTP (descriptions, SOAP, media transfer) traffic etc, defaults to 8200.
There should be no need to change this.
.fi

.IP "\fBnetwork_interface\fP"
Network interfaces to serve, comma delimited. Defaults to all.

.IP "\fBstrict_dlna\fP"
.nf
Set this to strictly adhere to DLNA standards. 
This will allow server-side downscaling of very large JPEG images,
which may hurt JPEG serving performance on (at least) Sony DLNA products.
.fi

.IP "\fBnotify_interval\fP" 
Notify interval in seconds. The default is 895 seconds.


.IP "\fBminissdpdsocket\fP"
.nf
Specify the path to the MiniSSDPd socket, 
EG: minissdpdsocket=/var/run/minissdpd.sock
.fi

.IP "\fBserial\fP"
.nf
Serial number the daemon will report to clients in its XML description. 
Defaults to 12345678
.fi

.IP "\fBmodel\fP"
.nf
Model number the daemon will report to clients in its XML description. 
Defaults to 1
.fi

.IP "\fBmedia_dir\fP" 
.nf
Path to the directory containing the media files minidlna should share. 
Use this option multile times if you have more than one directory to share. 

Example:
 media_dir=/opt/multimedia/videos
 media_dir=/opt/multimedia/movies
.fi
.PP
You can also restrict an entry to a specific media type, you do this
by using the following syntax: 
.nf
   the letter 'A', 'V' or 'P', followed by a comma (',') followed by the path.
   The meaning of the first letter is as follows:
                      'A' for audio files
                      'V' for video files
                      'P' for image files

    For example, if you want to include only video files located
    in /opt/multimedia/videos directory, and only music
    in /opt/multimedia/music, then you would use
                       media_dir=V,/opt/multimedia/videos
                       media_dir=A,/opt/multimedia/music

    Another example would be
                       media_dir=V,/opt/multimedia/videos
                       media_dir=V,/opt/multimedia/movies
                       media_dir=A,/opt/multimedia/music

    Or, if you did not care what type it finds, then you could use
                       media_dir=/opt/multimedia/videos
                       media_dir=/opt/multimedia/movies
                       media_dir=/opt/multimedia/music

    You can mix it up, find anything in music, but only Videos, in videos and movies
                       media_dir=V,/opt/multimedia/videos
                       media_dir=V,/opt/multimedia/movies
                       media_dir=/opt/multimedia/music

.fi

.IP "\fBpresentation_url\fP"
.nf
Default presentation url is http address on port 80
EG: presentation_url=http://www.mediaserver.lan/index.php
.fi

.IP "\fBdb_dir\fP"
Where minidlna stores the data files, including Album caceh files, by default 
this is /var/cache/minidlna

.IP "\fBlog_dir\fP"
Path to the directory where the log file upnp-av.log should be stored, this 
defaults to /var/log

.IP "\fBlog_level\fP"
Set this to change the verbosity of the information that is logged each 
section can use a different level: off, fatal, error, warn, info, or debug
.nf

Example
log_level=general,artwork,database,inotify,scanner,metadata,http,ssdp,tivo=warn
.fi

.IP "\fBinotify\fP"
Set to 'yes' to enable inotify monitoring of the files under media_dir 
to automatically discover new files. Set to 'no' to disable inotify.

.IP "\fBalbum_art_names\fP"
This should be a list of file names to check for when searching for album art
and names should be delimited with a forward slash ("/").
.nf

Example
album_art_names=Cover.jpg/cover.jpg/AlbumArtSmall.jpg/albumartsmall.jpg/AlbumArt.jpg
/albumart.jpg/Album.jpg/album.jpg/Folder.jpg/folder.jpg/Thumb.jpg/thumb.jpg

.fi

.IP "\fBenable_tivo\fP"
Set this to yes to enable support for streaming .jpg and .mp3 files to a TiVo 
supporting HMO, default is no.

.IP "\fBroot_container\fP" 
Use a different container as the root of the tree exposed to clients.
.nf
The possible values are:
             '.' to use the standard container (this is the default)
             'B' to use the "Browse Directory" container;
             'M' to use the "Music" container;
             'V' to use the "Video" container;
             'P' to use the "Pictures" container.
  If you specify 'B' and the client device is audio only, then
  "Music/Folders" will be used as root container and you wont see Videos.
.fi

.IP "\fBforce_sort_criteria\fP"
Always force SortCriteria to this value, regardless of the SortCriteria passed by the client.
.nf

Example
force_sort_criteria=+upnp:class,+upnp:originalTrackNumber,+dc:title

.fi



.SH VERSION
This manpage corresponds to minidlna version 1.0.25 

.SH AUTHOR
.nf
minidlna developed by Justin Maggard  https://sourceforge.net/projects/minidlna/
man page written by Noel Butler <noelb@ausics.net>
.fi

.SH LICENSE
GPL

.SH FILES
/etc/minidlna.conf

.SH SEE ALSO
 minidlna(8)

