# M32R simulator testsuite.

if [istarget m32r*-*-*] {
    # load support procs
    # load_lib cgen.exp

    # all machines
    set all_machs "m32r"


    # The .cgs suffix is for "cgen .s".
    foreach src [lsort [glob -nocomplain $srcdir/$subdir/*.cgs]] {
	# If we're only testing specific files and this isn't one of them,
	# skip it.
	if ![runtest_file_p $runtests $src] {
	    continue
	}

	run_sim_test $src $all_machs
    }
}
