[
	pointer_default(unique)
]
interface file_id
{
	typedef [public] struct {
		/* we don't use SMB_DEV_T and SMB_INO_T as we want a fixed size here,
		   and we may be using file system specific code to fill in something
		   other than a dev_t for the device */
		udlong devid;
		udlong inode;
		udlong extid; /* Support systems that use an extended id (e.g. snapshots). */
	} file_id;
}
