# German messages for international release of SWAT.
# Copyright (C) 2001 Andreas Moroder
# Copyright (C) 2007 Helge Kreutzmann, <debian@helgefjell.de>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, see <http://www.gnu.org/licenses/>.
#
msgid ""
msgstr ""
"Project-Id-Version: swat\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2007-06-04 18:15+0200\n"
"PO-Revision-Date: 2007-06-10 11:52+0200\n"
"Last-Translator: Helge Kreutzmann <debian@helgefjell.de>\n"
"Language-Team: German <debian-l10n-german@lists.debian.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../web/swat.c:139
#, c-format
msgid "ERROR: Can't open %s"
msgstr "FEHLER: Kann %s nicht öffnen"

#: ../web/swat.c:223
msgid "Help"
msgstr "Hilfe"

#: ../web/swat.c:229 ../web/swat.c:254 ../web/swat.c:275 ../web/swat.c:285
#: ../web/swat.c:294 ../web/swat.c:303 ../web/swat.c:309 ../web/swat.c:315
#: ../web/swat.c:328
msgid "Set Default"
msgstr "Standardwert setzen"

#: ../web/swat.c:450
#, c-format
msgid "failed to open %s for writing"
msgstr "konnte %s nicht zum Schreiben öffnen"

#: ../web/swat.c:473
#, c-format
msgid "Can't reload %s"
msgstr "Kann %s nicht erneut laden"

#: ../web/swat.c:543
#, c-format
msgid "Logged in as <b>%s</b>"
msgstr "Verbunden als <b>%s</b>"

#: ../web/swat.c:547
msgid "Home"
msgstr "Home"

#: ../web/swat.c:549
msgid "Globals"
msgstr "Globals"

#: ../web/swat.c:550
msgid "Shares"
msgstr "Freigaben"

#: ../web/swat.c:551
msgid "Printers"
msgstr "Drucker"

#: ../web/swat.c:552
msgid "Wizard"
msgstr "Assistent"

#: ../web/swat.c:556
msgid "Status"
msgstr "Status"

#: ../web/swat.c:557
msgid "View Config"
msgstr "Zeige Konfiguration"

#: ../web/swat.c:559
msgid "Password Management"
msgstr "Passwortverwaltung"

#: ../web/swat.c:569
msgid "Current View Is"
msgstr "Aktuelle Ansicht lautet"

#: ../web/swat.c:570 ../web/swat.c:573
msgid "Basic"
msgstr "Einfache Ansicht"

#: ../web/swat.c:571 ../web/swat.c:574
msgid "Advanced"
msgstr "Erweiterte Ansicht"

#: ../web/swat.c:572
msgid "Change View To"
msgstr "Ansicht ändern in"

#: ../web/swat.c:601
msgid "Current Config"
msgstr "Aktuelle Konfiguration"

#: ../web/swat.c:605
msgid "Normal View"
msgstr "Normale Ansicht"

#: ../web/swat.c:607
msgid "Full View"
msgstr "Komplette Ansicht"

#. Here we first set and commit all the parameters that were selected
#. in the previous screen.
#: ../web/swat.c:626
msgid "Wizard Parameter Edit Page"
msgstr "Bearbeitungsseite der Assistenten-Parameter"

#: ../web/swat.c:655
msgid "Note: smb.conf file has been read and rewritten"
msgstr "Hinweis: smb.conf wurde gelesen und überschrieben"

#. Here we go ...
#: ../web/swat.c:763
msgid "Samba Configuration Wizard"
msgstr "Samba-Konfigurationsassistent"

#: ../web/swat.c:767
msgid ""
"The \"Rewrite smb.conf file\" button will clear the smb.conf file of all "
"default values and of comments."
msgstr ""
"Der Knopf »Schreibe smb.conf neu« wird alle Kommentare und Standardwerte "
"aus der smb.conf löschen."

#: ../web/swat.c:768
msgid "The same will happen if you press the commit button."
msgstr "Das gleiche passiert beim Knopf »übernehmen«."

#: ../web/swat.c:771
msgid "Rewrite smb.conf file"
msgstr "Schreibe smb.conf neu"

#: ../web/swat.c:772
msgid "Commit"
msgstr "Übernehmen"

#: ../web/swat.c:773
msgid "Edit Parameter Values"
msgstr "Bearbeite Parameterwerte"

#: ../web/swat.c:779
msgid "Server Type"
msgstr "Server-Typ"

#: ../web/swat.c:780
msgid "Stand Alone"
msgstr "Einzelserver"

#: ../web/swat.c:781
msgid "Domain Member"
msgstr "Domänenmitglied"

#: ../web/swat.c:782
msgid "Domain Controller"
msgstr "Domänencontroller"

#: ../web/swat.c:785
msgid "Unusual Type in smb.conf - Please Select New Mode"
msgstr ""
"Ungewöhnlicher Typ in der smb.conf - Bitte wählen Sie einen neuen Modus"

#: ../web/swat.c:787
msgid "Configure WINS As"
msgstr "Konfiguriere WINS als"

#: ../web/swat.c:788
msgid "Not Used"
msgstr "Nicht benutzt"

#: ../web/swat.c:789
msgid "Server for client use"
msgstr "Server für Client-Verwendung"

#: ../web/swat.c:790
msgid "Client of another WINS server"
msgstr "Client eines anderen WINS-Servers"

#: ../web/swat.c:792
msgid "Remote WINS Server"
msgstr "Entfernter WINS-Server:"

#: ../web/swat.c:803
msgid "Error: WINS Server Mode and WINS Support both set in smb.conf"
msgstr ""
"Fehler: Sowohl WINS-Server-Modus als auch WINS-Unterstützung in smb.conf "
"aktiviert"

#: ../web/swat.c:804
msgid "Please Select desired WINS mode above."
msgstr "Bitte wählen Sie den gewünschten WINS-Modus oben aus."

#: ../web/swat.c:806
msgid "Expose Home Directories"
msgstr "Home-Verzeichnisse freigeben"

#: ../web/swat.c:821
msgid ""
"The above configuration options will set multiple parameters and will "
"generally assist with rapid Samba deployment."
msgstr ""
"Die obigen Konfigurationsoptionen bearbeiten mehrere Parameter und dienen als "
"Hilfe zur schnellen Samba-Einrichtung."

#: ../web/swat.c:834
msgid "Global Parameters"
msgstr "Globale Parameter"

#: ../web/swat.c:862 ../web/swat.c:966 ../web/swat.c:1318
msgid "Commit Changes"
msgstr "Änderungen speichern"

#: ../web/swat.c:866 ../web/swat.c:969 ../web/swat.c:1320
msgid "Reset Values"
msgstr "Werte zurücksetzen"

#: ../web/swat.c:891
msgid "Share Parameters"
msgstr "Parameter der Freigabe"

#: ../web/swat.c:934
msgid "Choose Share"
msgstr "Wähle Freigabe"

#: ../web/swat.c:951
msgid "Delete Share"
msgstr "Lösche Freigabe"

#: ../web/swat.c:958
msgid "Create Share"
msgstr "Erstelle Freigabe"

#: ../web/swat.c:994
msgid "password change in demo mode rejected"
msgstr "Änderung des Passworts im Demo-Modus nicht möglich"

#: ../web/swat.c:1007
msgid "Can't setup password database vectors."
msgstr "Kann Passwort-Datenbankvektoren nicht einrichten"

#: ../web/swat.c:1033
msgid " Must specify \"User Name\" "
msgstr " »Benutzername« muss angegeben werden "

#: ../web/swat.c:1049
msgid " Must specify \"Old Password\" "
msgstr " »Altes Passwort« muss angegeben werden "

#: ../web/swat.c:1055
msgid " Must specify \"Remote Machine\" "
msgstr " »Entfernter Server« muss angegeben werden "

#: ../web/swat.c:1062
msgid " Must specify \"New, and Re-typed Passwords\" "
msgstr " »Neues/wiederholtes Passwort« muss angegeben werden "

#: ../web/swat.c:1068
msgid " Re-typed password didn't match new password "
msgstr " Das wiederholte Passwort stimmt nicht mit dem neuen Passwort überein"

#: ../web/swat.c:1101
#, c-format
msgid " The passwd for '%s' has been changed."
msgstr " Das Passwort für '%s' wurde geändert."

#: ../web/swat.c:1104
#, c-format
msgid " The passwd for '%s' has NOT been changed."
msgstr " Das Passwort für '%s' wurde NICHT geändert."

#: ../web/swat.c:1129
msgid "Server Password Management"
msgstr "Verwaltung des Server-Passwortes"

#.
#. * Create all the dialog boxes for data collection
#.
#: ../web/swat.c:1138 ../web/swat.c:1185
msgid "User Name"
msgstr "Benutzername"

#: ../web/swat.c:1141 ../web/swat.c:1187
msgid "Old Password"
msgstr "Altes Passwort"

#: ../web/swat.c:1144 ../web/swat.c:1189
msgid "New Password"
msgstr "Neues Passwort"

#: ../web/swat.c:1146 ../web/swat.c:1191
msgid "Re-type New Password"
msgstr "Wiederhole neues Passwort"

#: ../web/swat.c:1154 ../web/swat.c:1202
msgid "Change Password"
msgstr "Ändere Passwort"

#: ../web/swat.c:1157
msgid "Add New User"
msgstr "Füge neuen Benutzer hinzu"

#: ../web/swat.c:1159
msgid "Delete User"
msgstr "Lösche Benutzer"

#: ../web/swat.c:1161
msgid "Disable User"
msgstr "Deaktiviere Benutzer"

#: ../web/swat.c:1163
msgid "Enable User"
msgstr "Aktiviere Benutzer"

#: ../web/swat.c:1176
msgid "Client/Server Password Management"
msgstr "Client/Server Passwort-Verwaltung"

#: ../web/swat.c:1193
msgid "Remote Machine"
msgstr "Entfernte Maschine"

#: ../web/swat.c:1232
msgid "Printer Parameters"
msgstr "Drucker-Parameter"

#: ../web/swat.c:1234
msgid "Important Note:"
msgstr "Wichtiger Hinweis:"

#: ../web/swat.c:1235
#, c-format
msgid "Printer names marked with [*] in the Choose Printer drop-down box "
msgstr "Mit [*] gekennzeichnete Drucker in der »Wähle Drucker«-Auswahlliste "

#: ../web/swat.c:1236
#, c-format
msgid "are autoloaded printers from "
msgstr "sind automatisch geladene Drucker aus "

#: ../web/swat.c:1237
msgid "Printcap Name"
msgstr "Printcap-Name"

#: ../web/swat.c:1238
msgid "Attempting to delete these printers from SWAT will have no effect."
msgstr ""
"Der Versuch, diese Drucker von SWAT aus zu löschen, wird keine Auswirkung "
"haben."

#: ../web/swat.c:1284
msgid "Choose Printer"
msgstr "Wähle Drucker"

#: ../web/swat.c:1303
msgid "Delete Printer"
msgstr "Lösche Drucker"

#: ../web/swat.c:1310
msgid "Create Printer"
msgstr "Erstelle Drucker"

#: ../web/statuspage.c:139
msgid "RDWR       "
msgstr "LESE/SCHREIBE "

#: ../web/statuspage.c:141
msgid "WRONLY     "
msgstr "NUR SCHREIBE  "

#: ../web/statuspage.c:143
msgid "RDONLY     "
msgstr "NUR LESE      "

#: ../web/statuspage.c:330
msgid "Server Status"
msgstr "Server-Status"

#: ../web/statuspage.c:335
msgid "Auto Refresh"
msgstr "Automatische Aktualisierung"

#: ../web/statuspage.c:336 ../web/statuspage.c:341
msgid "Refresh Interval: "
msgstr "Aktualisierungsintervall: "

#: ../web/statuspage.c:340
msgid "Stop Refreshing"
msgstr "Stoppe Aktualisierung"

#: ../web/statuspage.c:355
msgid "version:"
msgstr "Version:"

#: ../web/statuspage.c:358
msgid "smbd:"
msgstr "smbd:"

#: ../web/statuspage.c:358 ../web/statuspage.c:371 ../web/statuspage.c:385
msgid "running"
msgstr "aktiv"

#: ../web/statuspage.c:358 ../web/statuspage.c:371 ../web/statuspage.c:385
msgid "not running"
msgstr "inaktiv"

#: ../web/statuspage.c:362
msgid "Stop smbd"
msgstr "Stoppe smbd"

#: ../web/statuspage.c:364
msgid "Start smbd"
msgstr "Starte smbd"

#: ../web/statuspage.c:366
msgid "Restart smbd"
msgstr "Starte smbd neu"

#: ../web/statuspage.c:371
msgid "nmbd:"
msgstr "nmbd:"

#: ../web/statuspage.c:375
msgid "Stop nmbd"
msgstr "Stoppe nmbd"

#: ../web/statuspage.c:377
msgid "Start nmbd"
msgstr "Starte nmbd"

#: ../web/statuspage.c:379
msgid "Restart nmbd"
msgstr "Starte nmbd neu"

#: ../web/statuspage.c:385
msgid "winbindd:"
msgstr "winbindd:"

#: ../web/statuspage.c:389
msgid "Stop winbindd"
msgstr "Stoppe winbindd"

#: ../web/statuspage.c:391
msgid "Start winbindd"
msgstr "Starte winbindd"

#: ../web/statuspage.c:393
msgid "Restart winbindd"
msgstr "Starte winbindd neu"

#. stop, restart all
#: ../web/statuspage.c:402
msgid "Stop All"
msgstr "Alle Stoppen"

#: ../web/statuspage.c:403
msgid "Restart All"
msgstr "Alle neu starten"

#. start all
#: ../web/statuspage.c:407
msgid "Start All"
msgstr "Alle starten"

#: ../web/statuspage.c:414
msgid "Active Connections"
msgstr "Aktive Verbindungen"

#: ../web/statuspage.c:416 ../web/statuspage.c:429 ../web/statuspage.c:437
msgid "PID"
msgstr "PID"

#: ../web/statuspage.c:416 ../web/statuspage.c:429
msgid "Client"
msgstr "Client"

#: ../web/statuspage.c:416
msgid "IP address"
msgstr "IP-Adresse"

#: ../web/statuspage.c:416 ../web/statuspage.c:429 ../web/statuspage.c:437
msgid "Date"
msgstr "Datum"

#: ../web/statuspage.c:418
msgid "Kill"
msgstr "Töten"

#: ../web/statuspage.c:426
msgid "Active Shares"
msgstr "Aktive Freigaben"

#: ../web/statuspage.c:429
msgid "Share"
msgstr "Freigabe"

#: ../web/statuspage.c:429
msgid "User"
msgstr "Benutzer"

#: ../web/statuspage.c:429
msgid "Group"
msgstr "Gruppe"

#: ../web/statuspage.c:435
msgid "Open Files"
msgstr "Offene Dateien"

#: ../web/statuspage.c:437
msgid "Sharing"
msgstr "Freigeben"

#: ../web/statuspage.c:437
msgid "R/W"
msgstr "Lese/Schreibe"

#: ../web/statuspage.c:437
msgid "Oplock"
msgstr "Opportunistische Sperre (Lock)"

#: ../web/statuspage.c:437
msgid "File"
msgstr "Datei"

#: ../web/statuspage.c:446
msgid "Show Client in col 1"
msgstr "Zeige Client in Spalte 1"

#: ../web/statuspage.c:447
msgid "Show PID in col 1"
msgstr "Zeige PID in Spalte 1"

#: ../param/loadparm.c:836
msgid "Base Options"
msgstr "Basisoptionen"

#: ../param/loadparm.c:855
msgid "Security Options"
msgstr "Sicherheitsoptionen"

#: ../param/loadparm.c:945
msgid "Logging Options"
msgstr "Protokollier-Optionen"

#: ../param/loadparm.c:962
msgid "Protocol Options"
msgstr "Protokoll-Optionen"

#: ../param/loadparm.c:1008
msgid "Tuning Options"
msgstr "Optimierungsoptionen"

#: ../param/loadparm.c:1037
msgid "Printing Options"
msgstr "Druckoptionen"

#: ../param/loadparm.c:1075
msgid "Filename Handling"
msgstr "Dateinamen-Verwaltung"

#: ../param/loadparm.c:1105
msgid "Domain Options"
msgstr "Domänen-Optionen"

#: ../param/loadparm.c:1109
msgid "Logon Options"
msgstr "Anmelde-Optionen"

#: ../param/loadparm.c:1130
msgid "Browse Options"
msgstr "Browsing-Optionen"

#: ../param/loadparm.c:1144
msgid "WINS Options"
msgstr "WINS-Optionen"

#: ../param/loadparm.c:1153
msgid "Locking Options"
msgstr "Locking-(Sperr-)Optionen"

#: ../param/loadparm.c:1170
msgid "Ldap Options"
msgstr "LDAP-Optionen"

#: ../param/loadparm.c:1186
msgid "Miscellaneous Options"
msgstr "Sonstige Optionen"

#: ../param/loadparm.c:1191
#| msgid "Logon Options"
msgid "EventLog Options"
msgstr "EventLog-Optionen"

#: ../param/loadparm.c:1258
msgid "VFS module options"
msgstr "VFS-Modul-Optionen"

#: ../param/loadparm.c:1268
msgid "Winbind options"
msgstr "Winbind-Optionen"
