#!/usr/bin/env python

bld.SAMBA_LIBRARY('samba-hostconfig',
	source='loadparm.c generic.c util.c',
	pc_files='samba-hostconfig.pc',
	vnum='0.0.1',
	deps='DYNCONFIG',
	public_deps='samba-util',
	public_headers='param.h',
	autoproto='param_proto.h',
	)


bld.SAMBA_SUBSYSTEM('PROVISION',
	source='provision.c pyparam.c',
	deps='LIBPYTHON pyparam_util ldb pytalloc-util pyldb-util',
	pyext=True,
	)


bld.SAMBA_SUBSYSTEM('share',
	source='share.c',
	public_headers='share.h',
	deps='samba-util'
	)


bld.SAMBA_MODULE('share_classic',
	source='share_classic.c',
	subsystem='share',
	init_function='share_classic_init',
	deps='samba-util'
	)


bld.SAMBA_MODULE('share_ldb',
	source='share_ldb.c',
	subsystem='share',
	init_function='share_ldb_init',
	deps='ldbsamba auth_system_session'
	)


bld.SAMBA_SUBSYSTEM('SECRETS',
	source='secrets.c',
	deps='ldb tdb-wrap UTIL_TDB NDR_SECURITY tevent ldbwrap'
	)


bld.SAMBA_PYTHON('pyparam',
	source='pyparam.c',
	deps='samba-hostconfig pytalloc-util',
	realname='samba/param.so'
	)


bld.SAMBA_SUBSYSTEM('pyparam_util',
	source='pyparam_util.c',
	deps='LIBPYTHON samba-hostconfig',
	pyext=True,
	)

bld.SAMBA_LIBRARY('shares',
                  source=[],
                  deps='share share_classic share_ldb',
                  grouping_library=True,
                  private_library=True)
