 /*
 * Copyright 2016, ASUSTeK Inc.
 * All Rights Reserved.
 *
 * THIS SOFTWARE IS OFFERED "AS IS", AND ASUS GRANTS NO WARRANTIES OF ANY
 * KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE. BROADCOM
 * SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A SPECIFIC PURPOSE OR NONINFRINGEMENT CONCERNING THIS SOFTWARE.
 *
 */

#ifndef __nt_actMail_h__
#define __nt_actMail_h__


#include <libnt.h>
#include <nt_eInfo.h>

#define ErrorMsg(fmt,args...) \
	Debug2Console("[ACTMAIL][%s:(%d)]"fmt, __FUNCTION__, __LINE__, ##args);

/* SEND MAIL INFO STRUCTURE
---------------------------------*/
typedef struct __mail_info__t_
{
	char modelName[16];
	char subject[32];
	char toMail[64];
	char msg[100];
	time_t tstamp;
	int  MsendId;
	int  event;

}MAIL_INFO_T;

/* NOTIFY MAIL CONTENT INFO STRUCTURE
---------------------------------*/
struct MAIL_CONTENT_T
{
	int event;
	MAIL_INFO_T *MailContentFunc;
};

/* NOTIFY MAIL CONTENT CALLBACK FUNCTION DECLARE
---------------------------------*/
/* ### RESERVATION EVENT */
MAIL_INFO_T *RESERVATION_MAIL_CONFIRM_FUNC(MAIL_INFO_T *mInfo);
/* ### WAN EVENT */
MAIL_INFO_T *WAN_DISCONN_FUNC(MAIL_INFO_T *mInfo);
MAIL_INFO_T *WAN_BLOCK_FUNC(MAIL_INFO_T *mInfo);
/* ### PASSWORD EVENT */
MAIL_INFO_T *PASSWORD_SAME_WITH_LOGIN_WIFI_FUNC(MAIL_INFO_T *mInfo);
MAIL_INFO_T *PASSWORD_WIFI_WEAK_FUNC(MAIL_INFO_T *mInfo);
MAIL_INFO_T *PASSWORD_LOGIN_STRENGTH_CHECK_FUNC(MAIL_INFO_T *mInfo);
/* ### GUEST NETWORK EVENT */
/* ### RSSI EVENT */
/* ### DUALWAN EVENT */
/* ### LOGIN EVENT */
MAIL_INFO_T *LOGIN_FAIL_LAN_WEB_FUNC(MAIL_INFO_T *mInfo);
/* ### PROTECTION EVENT */
MAIL_INFO_T *PROTECTION_INTO_MONITORMODE_FUN(MAIL_INFO_T *mInfo);
MAIL_INFO_T *PROTECTION_VULNERABILITY_FUN(MAIL_INFO_T *mInfo);
MAIL_INFO_T *PROTECTION_CC_FUN(MAIL_INFO_T *mInfo);
MAIL_INFO_T *PROTECTION_DOS_FUN(MAIL_INFO_T *mInfo);
/* ### PARENTAL CONTROL EVENT */
/* ### TRAFFIC METER EVENT */
MAIL_INFO_T *TRAFFICMETER_CUTOFF_FUN(MAIL_INFO_T *mInfo);
MAIL_INFO_T *TRAFFICMETER_ALERT_FUN(MAIL_INFO_T *mInfo);
/* ### FIRMWARE EVENT */
/* ### USB EVENT */
/* ### HINT EVENT */


/* NOTIFY MAIL CONTENT CALLBACK FUNCTION TABLE
---------------------------------*/
const struct MAIL_CONTENT_T CONTENT_TABLE[] =
{
	/* RESERVATION EVENT */
	{RESERVATION_MAIL_CONFIRM_EVENT, (MAIL_INFO_T *)RESERVATION_MAIL_CONFIRM_FUNC},
	/* WAN EVENT */
	{WAN_DISCONN_EVENT, (MAIL_INFO_T *)WAN_DISCONN_FUNC},
	{WAN_BLOCK_EVENT, (MAIL_INFO_T *)WAN_BLOCK_FUNC},
	/* PASSWORD EVENT */
	{PASSWORD_SAME_WITH_LOGIN_WIFI_EVENT, (MAIL_INFO_T *)PASSWORD_SAME_WITH_LOGIN_WIFI_FUNC},
	{PASSWORD_WIFI_WEAK_EVENT, (MAIL_INFO_T *)PASSWORD_WIFI_WEAK_FUNC},
	{PASSWORD_LOGIN_STRENGTH_CHECK_EVENT, (MAIL_INFO_T *)PASSWORD_LOGIN_STRENGTH_CHECK_FUNC},
	/* GUEST NETWORK EVENT */
	/* RSSI EVENT */
	/* DUALWAN EVENT */
	/* LOGIN EVENT */
	{LOGIN_FAIL_LAN_WEB_EVENT, (MAIL_INFO_T *)LOGIN_FAIL_LAN_WEB_FUNC},
	/* PROTECTION EVENT */
	{PROTECTION_INTO_MONITORMODE_EVENT, (MAIL_INFO_T *)PROTECTION_INTO_MONITORMODE_FUN},
	{PROTECTION_VULNERABILITY_EVENT, (MAIL_INFO_T *)PROTECTION_VULNERABILITY_FUN},
	{PROTECTION_CC_EVENT, (MAIL_INFO_T *)PROTECTION_CC_FUN},
	{PROTECTION_DOS_EVENT, (MAIL_INFO_T *)PROTECTION_DOS_FUN},
	/* PARENTAL CONTROL EVENT */
	/* TRAFFIC METER EVENT */
	{TRAFFICMETER_CUTOFF_EVENT, (MAIL_INFO_T *)TRAFFICMETER_CUTOFF_FUN},
	{TRAFFICMETER_ALERT_EVENT, (MAIL_INFO_T *)TRAFFICMETER_ALERT_FUN},
	/* FIRMWARE EVENT */
	/* USB EVENT */
	/* HINT EVENT */
	/* The End */
	{0,0}
};

#endif

