language: cpp
install:
  - sudo apt-get install aptitude
  - sudo aptitude -y install $(< apt-requirements.txt)
  - sudo mkdir -p /media/ASUSWRT/
  - sudo ln -s $TRAVIS_BUILD_DIR /media/ASUSWRT/asuswrt-merlin
script: make -C $ASUSWRT_TRAVIS_PATH $ASUSWRT_TRAVIS_TARGET
env:
  global:
    - PATH=$PATH:$TRAVIS_BUILD_DIR/tools/brcm/hndtools-mipsel-linux/bin:$TRAVIS_BUILD_DIR/hndtools-mipsel-uclibc/bin
  matrix:
    - ASUSWRT_TRAVIS_TARGET=rt-n16 $ASUSWRT_TRAVIS_PATH=$TRAVIS_BUILD_DIR/release/src-rt
    - ASUSWRT_TRAVIS_TARGET=rt-n66u $ASUSWRT_TRAVIS_PATH=$TRAVIS_BUILD_DIR/release/src-rt
    - ASUSWRT_TRAVIS_TARGET=rt-ac66u $ASUSWRT_TRAVIS_PATH=$TRAVIS_BUILD_DIR/release/src-rt-6.x
