.\" .nh
.\" .ad l
.TH "hotplug2-coldplug-2.4" "8" "August 2006" "hotplug2-coldplug-2.4" "hotplug2-coldplug-2.4"
.SH "NAME"
hotplug2\-coldplug\-2.4 \- generate coldplug uevents on 2.4 kernels
.SH "SYNOPSIS"
\fBhotplug2\-coldplug\-2.4\fR
.SH "DESCRIPTION"
.PP 
This application reads various data in /proc/bus to generate uevents for the current running system, passed on through netlink socket.
.PP 
.SH "AUTHOR"
.PP 
Written by iSteve
<isteve@bofh.cz>
.SH "SEE ALSO"
.PP 
\fBhotplug2\fR(8)
