.\" Jean II - HPLB - 96
.\" iwpriv.8
.\"
.TH IWPRIV 8 "31 October 1996" "net-tools" "Linux Programmer's Manual"
.\"
.\" NAME part
.\"
.SH NAME
iwpriv \- configure optionals (private) parameters of a wireless
network interface
.\"
.\" SYNOPSIS part
.\"
.SH SYNOPSIS
.BI "iwpriv [" interface ]
.br
.BI "iwpriv " "interface private-command " "[" private-parameters ]
.br
.BI "iwpriv " "interface private-command " [ I "] [" private-parameters ]
.br
.BI "iwpriv " interface " --all"
.\"
.\" DESCRIPTION part
.\"
.SH DESCRIPTION
.B Iwpriv
is the companion tool to
.IR iwconfig (8).
.B Iwpriv
deals with parameters and setting specific to each driver (as opposed to
.I iwconfig
which deals with generic ones).
.PP
Without any argument,
.B iwpriv
list the available private commands available on each interface, and
the parameters that they require. Using this information, the user may
apply those interface specific commands on the specified interface.
.PP
In theory, the documentation of each device driver should indicate how
to use those interface specific commands and their effect.
.\"
.\" PARAMETER part
.\"
.SH PARAMETERS
.TP
.IR private-command " [" private-parameters ]
Execute the specified
.I private-command
on the interface.
.br
The command may optionally take or require arguments, and may display
information. Therefore, the command line parameters may or may not be
needed and should match the command expectations. The list of commands
that
.B iwpriv
displays (when called without argument) should give you some hints
about those parameters.
.br
However you should refer to the device driver documentation for
information on how to properly use the command and the effect.
.TP
.IR "private-command " [ I "] [" private-parameters ]
Idem, except that
.I I
(an integer) is passed to the command as a
.IR "Token Index" .
Only some command will use the Token Index (most will ignore it), and
the driver documentation should tell you when it's needed.
.TP
.BR -a / --all
Execute and display all the private commands that don't take any
arguments (i.e.  read only).
.\"
.\" DISPLAY part
.\"
.SH DISPLAY
For each device which support private commands,
.I iwpriv
will display the list of private commands available.
.PP
This include the name of the private command, the number or arguments
that may be set and their type, and the number or arguments that may
be display and their type.
.PP
For example, you may have the following display :
.br
.B "eth0      Available private ioctl :"
.br
.B "          setqualthr (89F0) : set   1 byte & get   0"
.br
.B "          gethisto (89F7) : set   0      & get  16 int"
.PP
This indicate that you may set the quality threshold and display an
histogram of up to 16 values with the following commands :
.br
.I "  iwpriv eth0 setqualthr 20"
.br
.I "  iwpriv eth0 gethisto"
.\"
.\" AUTHOR part
.\"
.SH AUTHOR
Jean Tourrilhes \- jt@hpl.hp.com
.\"
.\" FILES part
.\"
.SH FILES
.I /proc/net/wireless
.\"
.\" SEE ALSO part
.\"
.SH SEE ALSO
.BR iwconfig (8),
.BR iwlist (8),
.BR iwevent (8),
.BR iwspy (8),
.BR wireless (7).
