.\" Jean II - HPLB - 96
.\" iwspy.8
.\"
.TH IWSPY 8 "31 October 1996" "net-tools" "Linux Programmer's Manual"
.\"
.\" NAME part
.\"
.SH NAME
iwspy \- Get wireless statistics from specific nodes
.\"
.\" SYNOPSIS part
.\"
.SH SYNOPSIS
.BI "iwspy [" interface ]
.br
.BI "iwspy " interface " [+] " DNSNAME " | " IPADDR " | " HWADDR " [...]"
.br
.BI "iwspy " interface " off"
.br
.BI "iwspy " interface " setthr " "low high"
.br
.BI "iwspy " interface " getthr"
.\"
.\" DESCRIPTION part
.\"
.SH DESCRIPTION
.B Iwspy
is used to set a list of addresses to monitor in a wireless network
interface and to read back quality of link information for each of
those. This information is the same as the one available in
.I /proc/net/wireless
: quality of the link, signal strength and noise level.
.PP
This information is updated each time a new packet is received, so
each address of the list adds some overhead in the driver.
.PP
Note that this functionality works only for nodes part of the current
wireless cell, you can not monitor Access Points you are not
associated with (you can use Scanning for that) and nodes in other
cells. In Managed mode, in most case packets are relayed by the Access
Point, in this case you will get the signal strength of the Access
Point. For those reasons this functionality is mostly useful in Ad-Hoc
and Master mode.
.\"
.\" PARAMETER part
.\"
.SH PARAMETERS
You may set any number of addresses up to 8.
.TP
.BR DNSNAME " | " IPADDR
Set an IP address, or in some cases a DNS name (using the name
resolver). As the hardware works with hardware addresses,
.B iwspy
will translate this IP address through
.IR ARP .
In some case, this address might not be in the ARP cache and
.B iwspy
will fail. In those case,
.IR ping (8)
this name/address and retry.
.TP
.B HWADDR
Set a hardware (MAC) address (this address is not translated & checked
like the IP one). The address must contain a colon
.RB ( : )
to be recognised as a hardware address.
.TP
.B +
Add the new set of addresses at the end of the current list instead of
replacing it. The address list is unique for each device, so each user
should use this option to avoid conflicts.
.TP
.B off
Remove the current list of addresses and disable the spy functionality
.TP
.B setthr
Set the
.I low
and
.I high
signal strength threshold for the iwspy event (for drivers that
support it).
.br
Every time the signal strength for any of the address monitored
with iwspy goes lower than the low threshold or goes higher than the
high threshold, a Wireless Event will be generated.
.br
This can be used to monitor link outages without having to run iwspy
periodically.
.TP
.B getthr
Retrieve the current
.I low
and
.I high
signal strength threshold for the iwspy event.
\"
.\" FILES part
.\"
.SH FILES
.I /proc/net/wireless
.\"
.\" SEE ALSO part
.\"
.SH SEE ALSO
.BR iwconfig (8),
.BR iwlist (8),
.BR iwevent (8),
.BR iwpriv (8),
.BR wireless (7).

