.\" Jean Tourrilhes - HPL - 2002 - 2004
.\" wireless.7
.\"
.TH WIRELESS 7 "4 March 2004" "wireless-tools" "Linux Programmer's Manual"
.\"
.\" NAME part
.\"
.SH NAME
wireless \- Wireless Tools and Wireless Extensions
.\"
.\" SYNOPSIS part
.\"
.SH SYNOPSIS
.B iwconfig
.br
.B iwpriv \-a
.br
.\"
.\" DESCRIPTION part
.\"
.SH DESCRIPTION
The
.B Wireless Extensions
is an API allowing you manipulate Wireless LAN networking interfaces.
It is composed of a variety of tools and configuration files. It is
documented in more detail in the Linux Wireless LAN Howto.
.br
The
.B Wireless Tools
are used to change the configuration of wireless LAN networking
interfaces on the fly, to get their current configuration, to get
statistics and diagnose them. They are described in their own man
page, see below for references.
.br
.B Wireless configuration
is specific to each Linux distribution. This man page will contain in
the future the configuration procedure for a few common
distributions. For the time being, check the file DISTRIBUTIONS.txt
included with the Wireless Tools package.
.\"
.\" DEBIAN 3.0 part
.\"
.SH DEBIAN 3.0
In Debian 3.0 (and later) you can configure wireless LAN networking
devices using the network configuration tool
.BR ifupdown (8).
.TP
.B File :
.I /etc/network/interfaces
.TP
.B Form :
.RI wireless\- "<function> <value>"
.br
wireless\-essid Home
.br
wireless\-mode Ad\-Hoc
.TP
.B See also :
.I /etc/network/if\-pre\-up.d/wireless\-tools
.br
.I /usr/share/doc/wireless\-tools/README.Debian
.\"
.\" SuSE 8.0 part
.\"
.SH SuSE 8.0
SuSE 8.0 (and later) has integrated wireless configuration in their
network scripts.
.TP
.B Tool :
.B Yast2
.TP
.B File :
.I /etc/sysconfig/network/wireless
.br
.I /etc/sysconfig/network/ifcfg\-*
.TP
.B Form :
.RI WIRELESS_ "<function>" = "<value>"
.br
WIRELESS_ESSID="Home"
.br
WIRELESS_MODE=Ad\-Hoc
.TP
.B See also :
man ifup
.br
info scpm
.\"
.\" PCMCIA part
.\"
.SH ORIGINAL PCMCIA SCRIPTS
If you are using the original configuration scripts from the Pcmcia
package, you can use this method.
.TP
.B File :
.I /etc/pcmcia/wireless.opts
.TP
.B Form :
*,*,*,*)
.br
    ESSID="Home"
.br
    MODE="Ad-Hoc"
.br
    ;;
.TP
.B See also :
.I /etc/pcmcia/wireless
.br
File
.I PCMCIA.txt
part of Wireless Tools package
.\"
.\" AUTHOR part
.\"
.SH AUTHOR
Jean Tourrilhes \- jt@hpl.hp.com
.br
.I http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/
.\"
.\" SEE ALSO part
.\"
.SH SEE ALSO
.BR iwconfig (8),
.BR iwlist (8),
.BR iwspy (8),
.BR iwpriv (8),
.BR iwevent (8).
