CFILES = fsck_hfs.c strings.c utilities.c cache.c
OFILES = $(CFILES:.c=.o)

all: fsck_hfs

fsck_hfs: $(OFILES) dfalib/libdfa.a

dfalib/libdfa.a: FORCE
	$(MAKE) -C dfalib -f Makefile.lnx libdfa.a

clean:
	$(RM) fsck_hfs $(OFILES)
	$(MAKE) -C dfalib -f Makefile.lnx clean

.PHONY : FORCE clean
