# Finnish messages for international release of SWAT.
# Copyright (C) 2007 Lauri Nurmi <lanurmi@iki.fi>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
msgid ""
msgstr ""
"Project-Id-Version: i18n_swat \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2007-01-02 01:56+0200\n"
"PO-Revision-Date: 2007-01-12 18:56+0200\n"
"Last-Translator: Lauri Nurmi <lanurmi@iki.fi>\n"
"Language-Team: Finnish <laatu@lokalisointi.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: \n"

#: ../web/swat.c:139
#, c-format
msgid "ERROR: Can't open %s"
msgstr "VIRHE: Avaaminen ei onnistu — %s"

#: ../web/swat.c:223
msgid "Help"
msgstr "Ohje"

#: ../web/swat.c:229 ../web/swat.c:254 ../web/swat.c:275 ../web/swat.c:285 ../web/swat.c:294 ../web/swat.c:303 ../web/swat.c:309 ../web/swat.c:315 ../web/swat.c:328
msgid "Set Default"
msgstr "Oletusarvo"

#: ../web/swat.c:450
#, c-format
msgid "failed to open %s for writing"
msgstr "avaaminen kirjoitustilassa ei onnistu — %s"

#: ../web/swat.c:473
#, c-format
msgid "Can't reload %s"
msgstr "Uudelleen lataaminen ei onnistu — %s"

#: ../web/swat.c:543
#, c-format
msgid "Logged in as <b>%s</b>"
msgstr "Sisäänkirjautuminen käyttäjänä <b>%s</b>"

#: ../web/swat.c:547
msgid "Home"
msgstr "Koti"

#: ../web/swat.c:549
msgid "Globals"
msgstr "Yleiset"

#: ../web/swat.c:550
msgid "Shares"
msgstr "Jaot"

#: ../web/swat.c:551
msgid "Printers"
msgstr "Tulostimet"

#: ../web/swat.c:552
msgid "Wizard"
msgstr "Ohjatut asetukset"

#: ../web/swat.c:556
msgid "Status"
msgstr "Tila"

#: ../web/swat.c:557
msgid "View Config"
msgstr "Näytä asetukset"

#: ../web/swat.c:559
msgid "Password Management"
msgstr "Salasanojen hallinta"

#: ../web/swat.c:569
msgid "Current View Is"
msgstr "Näkymä nyt"

#: ../web/swat.c:570 ../web/swat.c:573
msgid "Basic"
msgstr "Tavallinen"

#: ../web/swat.c:571 ../web/swat.c:574
msgid "Advanced"
msgstr "Laajennettu"

#: ../web/swat.c:572
msgid "Change View To"
msgstr "Vaihda näkymäksi"

#: ../web/swat.c:601
msgid "Current Config"
msgstr "Nykyiset asetukset"

#: ../web/swat.c:605
msgid "Normal View"
msgstr "Normaali näkymä"

#: ../web/swat.c:607
msgid "Full View"
msgstr "Täysi näkymä"

#. Here we first set and commit all the parameters that were selected
#. in the previous screen.
#: ../web/swat.c:626
msgid "Wizard Parameter Edit Page"
msgstr "Ohjattujen asetusten muokkaussivu"

#: ../web/swat.c:655
msgid "Note: smb.conf file has been read and rewritten"
msgstr "Huom: smb.conf-tiedosto on luettu ja kirjoitettu uudelleen"

#. Here we go ...
#: ../web/swat.c:763
msgid "Samba Configuration Wizard"
msgstr "Samban ohjatut asetukset"

#: ../web/swat.c:767
msgid "The \"Rewrite smb.conf file\" button will clear the smb.conf file of all default values and of comments."
msgstr "”Kirjoita uudelleen smb.conf-tiedosto”-painike tyhjentää oletusarvot ja kommentit smb.conf-tiedostosta."

#: ../web/swat.c:768
msgid "The same will happen if you press the commit button."
msgstr "Samoin tapahtuu ”Tallenna”-painiketta painettaessa."

#: ../web/swat.c:771
msgid "Rewrite smb.conf file"
msgstr "Kirjoita uudelleen smb.conf-tiedosto"

#: ../web/swat.c:772
msgid "Commit"
msgstr "Tallenna"

#: ../web/swat.c:773
msgid "Edit Parameter Values"
msgstr "Muokkaa asetusten arvoja"

#: ../web/swat.c:779
msgid "Server Type"
msgstr "Palvelimen tyyppi"

#: ../web/swat.c:780
msgid "Stand Alone"
msgstr "Itsenäinen"

# lähde: Microsoftin käännökset
#: ../web/swat.c:781
msgid "Domain Member"
msgstr "Toimialuejäsen"

# lähde: Microsoftin käännökset
#: ../web/swat.c:782
msgid "Domain Controller"
msgstr "Toimialueen ohjauskone"

#: ../web/swat.c:785
msgid "Unusual Type in smb.conf - Please Select New Mode"
msgstr "Epätavallinen tyyppi smb.confissa — Valitse uusi tila"

#: ../web/swat.c:787
msgid "Configure WINS As"
msgstr "WINS"

#: ../web/swat.c:788
msgid "Not Used"
msgstr "Ei käytössä"

#: ../web/swat.c:789
msgid "Server for client use"
msgstr "Palvelimena"

#: ../web/swat.c:790
msgid "Client of another WINS server"
msgstr "Käyttää WINS-etäpalvelinta"

#: ../web/swat.c:792
msgid "Remote WINS Server"
msgstr "WINS-etäpalvelin"

#: ../web/swat.c:803
msgid "Error: WINS Server Mode and WINS Support both set in smb.conf"
msgstr "Virhe: Sekä WINS-palvelintila että WINS-tuki asetettu smb.confissa"

#: ../web/swat.c:804
msgid "Please Select desired WINS mode above."
msgstr "Valitse haluttu WINSin tila yltä."

#: ../web/swat.c:806
msgid "Expose Home Directories"
msgstr "Jaa kotihakemistot"

#: ../web/swat.c:821
msgid "The above configuration options will set multiple parameters and will generally assist with rapid Samba deployment."
msgstr "Yllä olevat valinnat asettavat useita asetuksia, ja auttavat Samban nopeassa käyttöönotossa."

#: ../web/swat.c:834
msgid "Global Parameters"
msgstr "Yleisasetukset"

#: ../web/swat.c:862 ../web/swat.c:966 ../web/swat.c:1318
msgid "Commit Changes"
msgstr "Tallenna muutokset"

#: ../web/swat.c:866 ../web/swat.c:969 ../web/swat.c:1320
msgid "Reset Values"
msgstr "Kumoa muutokset"

#: ../web/swat.c:891
msgid "Share Parameters"
msgstr "Jakoasetukset"

#: ../web/swat.c:934
msgid "Choose Share"
msgstr "Valitse jako"

#: ../web/swat.c:951
msgid "Delete Share"
msgstr "Poista jako"

#: ../web/swat.c:958
msgid "Create Share"
msgstr "Luo jako"

#: ../web/swat.c:994
msgid "password change in demo mode rejected"
msgstr "salasanan muutos estetty esittelytilassa"

#: ../web/swat.c:1007
msgid "Can't setup password database vectors."
msgstr "Salasanatietokannan alustus epäonnistui."

#: ../web/swat.c:1033
msgid " Must specify \"User Name\" "
msgstr " Käyttäjätunnus on annettava "

#: ../web/swat.c:1049
msgid " Must specify \"Old Password\" "
msgstr " Vanha salasana on annettava "

#: ../web/swat.c:1055
msgid " Must specify \"Remote Machine\" "
msgstr " Etäkone on annettava "

#: ../web/swat.c:1062
msgid " Must specify \"New, and Re-typed Passwords\" "
msgstr " Uusi salasana on kirjoitettava kahdesti "

#: ../web/swat.c:1068
msgid " Re-typed password didn't match new password "
msgstr " Salasanat eivät täsmää "

#: ../web/swat.c:1101
#, c-format
msgid " The passwd for '%s' has been changed."
msgstr " Käyttäjän ”%s” salasana vaihdettu."

#: ../web/swat.c:1104
#, c-format
msgid " The passwd for '%s' has NOT been changed."
msgstr " Käyttäjän ”%s” salasanaa EI vaihdettu."

#: ../web/swat.c:1129
msgid "Server Password Management"
msgstr "Palvelimen salasanojen hallinta"

#.
#. * Create all the dialog boxes for data collection
#.
#: ../web/swat.c:1138 ../web/swat.c:1185
msgid "User Name"
msgstr "Käyttäjätunnus"

#: ../web/swat.c:1141 ../web/swat.c:1187
msgid "Old Password"
msgstr "Vanha salasana"

#: ../web/swat.c:1144 ../web/swat.c:1189
msgid "New Password"
msgstr "Uusi salasana"

#: ../web/swat.c:1146 ../web/swat.c:1191
msgid "Re-type New Password"
msgstr "Uusi salasana uudelleen"

#: ../web/swat.c:1154 ../web/swat.c:1202
msgid "Change Password"
msgstr "Vaihda salasana"

#: ../web/swat.c:1157
msgid "Add New User"
msgstr "Lisää uusi käyttäjä"

#: ../web/swat.c:1159
msgid "Delete User"
msgstr "Poista käyttäjä"

# Joku suomenkielisempi olisi ehkä parempi.
#: ../web/swat.c:1161
msgid "Disable User"
msgstr "Passivoi käyttäjä"

# Joku suomenkielisempi olisi ehkä parempi.
#: ../web/swat.c:1163
msgid "Enable User"
msgstr "Aktivoi käyttäjä"

# hmm...
#: ../web/swat.c:1176
msgid "Client/Server Password Management"
msgstr "Asiakas-palvelin-salasanojen hallinta"

#: ../web/swat.c:1193
msgid "Remote Machine"
msgstr "Etäkone"

#: ../web/swat.c:1232
msgid "Printer Parameters"
msgstr "Tulostinasetukset"

#: ../web/swat.c:1234
msgid "Important Note:"
msgstr "Tärkeä huomautus:"

#: ../web/swat.c:1235
#, c-format
msgid "Printer names marked with [*] in the Choose Printer drop-down box "
msgstr "Tähdellä [*] merkityt tulostimien nimet pudotusvalikossa ovat "

#: ../web/swat.c:1236
#, c-format
msgid "are autoloaded printers from "
msgstr "automaattisesti ladattuja tulostimia "

#: ../web/swat.c:1237
msgid "Printcap Name"
msgstr "Printcap Name -asetuksen osoittamasta paikasta"

#: ../web/swat.c:1238
msgid "Attempting to delete these printers from SWAT will have no effect."
msgstr "Näiden tulostimien poistaminen ei onnistu SWATin kautta."

#: ../web/swat.c:1284
msgid "Choose Printer"
msgstr "Valitse tulostin"

#: ../web/swat.c:1303
msgid "Delete Printer"
msgstr "Poista tulostin"

#: ../web/swat.c:1310
msgid "Create Printer"
msgstr "Luo tulostin"

#: ../web/statuspage.c:139
msgid "RDWR       "
msgstr "Luku+kirj. "

#: ../web/statuspage.c:141
msgid "WRONLY     "
msgstr "Vain kirj. "

#: ../web/statuspage.c:143
msgid "RDONLY     "
msgstr "Vain luku  "

#: ../web/statuspage.c:330
msgid "Server Status"
msgstr "Palvelimen tila"

#: ../web/statuspage.c:335
msgid "Auto Refresh"
msgstr "Automaattinen päivitys"

#: ../web/statuspage.c:336 ../web/statuspage.c:341
msgid "Refresh Interval: "
msgstr "Päivitysväli: "

#: ../web/statuspage.c:340
msgid "Stop Refreshing"
msgstr "Lopeta päivitys"

#: ../web/statuspage.c:355
msgid "version:"
msgstr "versio:"

#: ../web/statuspage.c:358
msgid "smbd:"
msgstr "smbd:"

#: ../web/statuspage.c:358 ../web/statuspage.c:371 ../web/statuspage.c:385
msgid "running"
msgstr "käynnissä"

#: ../web/statuspage.c:358 ../web/statuspage.c:371 ../web/statuspage.c:385
msgid "not running"
msgstr "pysäytetty"

#: ../web/statuspage.c:362
msgid "Stop smbd"
msgstr "Pysäytä smbd"

#: ../web/statuspage.c:364
msgid "Start smbd"
msgstr "Käynnistä smbd"

#: ../web/statuspage.c:366
msgid "Restart smbd"
msgstr "Käynnistä smbd uudelleen"

#: ../web/statuspage.c:371
msgid "nmbd:"
msgstr "nmbd:"

#: ../web/statuspage.c:375
msgid "Stop nmbd"
msgstr "Pysäytä nmbd"

#: ../web/statuspage.c:377
msgid "Start nmbd"
msgstr "Käynnistä nmbd"

#: ../web/statuspage.c:379
msgid "Restart nmbd"
msgstr "Käynnistä nmbd uudelleen"

#: ../web/statuspage.c:385
msgid "winbindd:"
msgstr "winbindd:"

#: ../web/statuspage.c:389
msgid "Stop winbindd"
msgstr "Pysäytä winbindd"

#: ../web/statuspage.c:391
msgid "Start winbindd"
msgstr "Käynnistä winbindd"

#: ../web/statuspage.c:393
msgid "Restart winbindd"
msgstr "Käynnistä winbindd uudelleen"

#. stop, restart all
#: ../web/statuspage.c:402
msgid "Stop All"
msgstr "Pysäytä kaikki"

#: ../web/statuspage.c:403
msgid "Restart All"
msgstr "Käynnistä kaikki uudelleen"

#. start all
#: ../web/statuspage.c:407
msgid "Start All"
msgstr "Käynnistä kaikki"

#: ../web/statuspage.c:414
msgid "Active Connections"
msgstr "Aktiiviset yhteydet"

#: ../web/statuspage.c:416 ../web/statuspage.c:429 ../web/statuspage.c:437
msgid "PID"
msgstr "PID"

#: ../web/statuspage.c:416 ../web/statuspage.c:429
msgid "Client"
msgstr "Asiakas"

#: ../web/statuspage.c:416
msgid "IP address"
msgstr "IP-osoite"

#: ../web/statuspage.c:416 ../web/statuspage.c:429 ../web/statuspage.c:437
msgid "Date"
msgstr "Aika"

#: ../web/statuspage.c:418
msgid "Kill"
msgstr "Sulje"

#: ../web/statuspage.c:426
msgid "Active Shares"
msgstr "Aktiiviset jaot"

#: ../web/statuspage.c:429
msgid "Share"
msgstr "Jako"

#: ../web/statuspage.c:429
msgid "User"
msgstr "Käyttäjä"

#: ../web/statuspage.c:429
msgid "Group"
msgstr "Ryhmä"

#: ../web/statuspage.c:435
msgid "Open Files"
msgstr "Avoimet tiedostot"

# Tämä on ilmeisesti palvelimen puolella vallitseva UID.
#: ../web/statuspage.c:437
msgid "Sharing"
msgstr "Jakaja"

#: ../web/statuspage.c:437
msgid "R/W"
msgstr "Luku/kirj."

# Selitys:
# "Oplocks is a unique Windows file locking feature. It is not really file 
# locking, but is included in most discussions of Windows file locking, so 
# is considered a de facto locking feature."
# Suomennos: ???
#: ../web/statuspage.c:437
msgid "Oplock"
msgstr "Oplock"

#: ../web/statuspage.c:437
msgid "File"
msgstr "Tiedosto"

#: ../web/statuspage.c:446
msgid "Show Client in col 1"
msgstr "Näytä asiakas 1. sarakkeessa"

#: ../web/statuspage.c:447
msgid "Show PID in col 1"
msgstr "Näytä PID 1. sarakkeessa"

#: ../param/loadparm.c:834
msgid "Base Options"
msgstr "Perusasetukset"

#: ../param/loadparm.c:853
msgid "Security Options"
msgstr "Turvallisuusasetukset"

#: ../param/loadparm.c:943
msgid "Logging Options"
msgstr "Lokiasetukset"

#: ../param/loadparm.c:959
msgid "Protocol Options"
msgstr "Protokolla-asetukset"

#: ../param/loadparm.c:1005
msgid "Tuning Options"
msgstr "Hienosäätöasetukset"

#: ../param/loadparm.c:1035
msgid "Printing Options"
msgstr "Tulostusasetukset"

#: ../param/loadparm.c:1072
msgid "Filename Handling"
msgstr "Tiedostonimien käsittely"

#: ../param/loadparm.c:1102
msgid "Domain Options"
msgstr "Toimialueasetukset"

#: ../param/loadparm.c:1106
msgid "Logon Options"
msgstr "Kirjautumisasetukset"

#: ../param/loadparm.c:1127
msgid "Browse Options"
msgstr "Selausasetukset"

#: ../param/loadparm.c:1141
msgid "WINS Options"
msgstr "WINS-asetukset"

#: ../param/loadparm.c:1150
msgid "Locking Options"
msgstr "Lukitusasetukset"

#: ../param/loadparm.c:1168
msgid "Ldap Options"
msgstr "LDAP-asetukset"

#: ../param/loadparm.c:1184
msgid "Miscellaneous Options"
msgstr "Sekalaiset asetukset"

#: ../param/loadparm.c:1189
msgid "EventLog Options"
msgstr "Tapahtumalokiasetukset"

#: ../param/loadparm.c:1257
msgid "VFS module options"
msgstr "VFS-moduulin asetukset"

#: ../param/loadparm.c:1267
msgid "Winbind options"
msgstr "Winbind-asetukset"
