/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef ADMINISTRATION_H
#define ADMINISTRATION_H

/* function declarations */
void init_administration(void);
FindVarMethod var_administration;
FindVarMethod var_mScanClientTable;
FindVarMethod var_mClientListTable;
    WriteMethod write_operationMode;
    WriteMethod write_routerLoginName;
    WriteMethod write_newPassword;
    WriteMethod write_wpsButtonBehavior;
    WriteMethod write_remoteLogServer;
    WriteMethod write_timeZone;
    WriteMethod write_manuallySetDaylightSaveingTime;
    WriteMethod write_dstStartTimeMonth;
    WriteMethod write_dstStartTimeWeek;
    WriteMethod write_dstStartTimeWeekday;
    WriteMethod write_dstStartTimeHour;
    WriteMethod write_dstEndTimeMonth;
    WriteMethod write_dstEndTimeWeek;
    WriteMethod write_dstEndTimeWeekday;
    WriteMethod write_dstEndTimeHour;
    WriteMethod write_ntpServer;
    WriteMethod write_enableTelnet;
    WriteMethod write_authenticationMethod;
    WriteMethod write_httpsLanPort;
    WriteMethod write_enableWebAccessfromWAN;
    WriteMethod write_httpPortWebAccessfromWAN;
    WriteMethod write_httpsPortWebAccessfromWAN;
    WriteMethod write_autoLogout;
    WriteMethod write_onlyAllowSpecificIP;
    WriteMethod write_mScanClientListAct;
    WriteMethod write_fTftpSrv;
    WriteMethod write_fTftpFile;
    WriteMethod write_fFirmwareUpgrade;
    WriteMethod write_sTftpSrv;
    WriteMethod write_sTftpFile;
    WriteMethod write_sTftpAction;
    WriteMethod write_snmpEnable;
    WriteMethod write_snSystemName;
    WriteMethod write_snLocation;
    WriteMethod write_snContact;
    WriteMethod write_snGetCommunity;
    WriteMethod write_snSetCommunity;
    WriteMethod write_authProtocol;
    WriteMethod write_authPass;
    WriteMethod write_privProtocol;
    WriteMethod write_privPass;
    WriteMethod write_systemCommand;
    WriteMethod write_mClientListClient;
    WriteMethod write_mClientListDelEntry;

#endif /* ADMINISTRATION_H */
