.\" tailf.1 -- 
.\" Created: Thu Jan 11 16:43:10 1996 by faith@acm.org
.\" Copyright 1996, 2003 Rickard E. Faith (faith@acm.org)
.\" 
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\" 
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" 
.TH TAILF 1 "February 2003" "util-linux" "User Commands"
.SH NAME
tailf \- follow the growth of a log file
.SH SYNOPSIS
.B tailf
[\fIOPTION\fR] \fIfile\fR
.SH DESCRIPTION
.B tailf
will print out the last 10 lines of a file and then wait for the file to
grow.  It is similar to
.B tail -f
but does not access the file when it is not growing.  This has the side
effect of not updating the access time for the file, so a filesystem flush
does not occur periodically when no log activity is happening.
.PP
.B tailf
is extremely useful for monitoring log files on a laptop when logging is
infrequent and the user desires that the hard disk spin down to conserve
battery life.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB\-n\fR, \fB\-\-lines\fR=\fIN\fR, \fB\-N\fR
output the last
.I N
lines, instead of the last 10.
.TP
\fB\-V\fR, \fB\-\-version
Output version information and exit.
.TP
\fB\-h\fR, \fB\-\-help
Display help and exit.

.SH AUTHOR
This program was originally written by Rik Faith (faith@acm.org) and may be freely
distributed under the terms of the X11/MIT License.  There is ABSOLUTELY
NO WARRANTY for this program.

The latest inotify based implementation was written by Karel Zak (kzak@redhat.com).
.SH "SEE ALSO"
.BR tail "(1), " less "(1)"
.SH AVAILABILITY
The tailf command is part of the util-linux package and is available from
ftp://ftp.kernel.org/pub/linux/utils/util-linux/.
