#!/bin/sh
# Test "ln -sf".

# Copyright (C) 1997-2000, 2007-2011 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. "${srcdir=.}/init.sh"; path_prepend_ ../src
print_ver_ ln

echo foo > a || framework_failure_
ln -s . b || framework_failure_

ln -sf a b > err 2>&1 && fail=1
case `cat err` in
  *'are the same file') ;;
  *) fail=1 ;;
esac

Exit $fail
