[SUBSYSTEM::LIBCLI_LDAP_MESSAGE]
PUBLIC_DEPENDENCIES = LIBSAMBA-ERRORS LIBTALLOC LIBLDB
PRIVATE_DEPENDENCIES = LIBSAMBA-UTIL ASN1_UTIL

LIBCLI_LDAP_MESSAGE_OBJ_FILES = $(addprefix ../libcli/ldap/, \
						ldap_message.o)
PUBLIC_HEADERS += ../libcli/ldap/ldap_message.h ../libcli/ldap/ldap_errors.h

[SUBSYSTEM::LIBCLI_LDAP_NDR]
PUBLIC_DEPENDENCIES = LIBSAMBA-ERRORS LIBTALLOC
PRIVATE_DEPENDENCIES = LIBSAMBA-UTIL LIBLDB NDR_MISC NDR_SECURITY

LIBCLI_LDAP_NDR_OBJ_FILES = ../libcli/ldap/ldap_ndr.o
PUBLIC_HEADERS += ../libcli/ldap/ldap_ndr.h

