.\" Jean Tourrilhes - HPL - 2002 - 2004
.\" wireless.7
.\"
.TH WIRELESS 7 "4.duben 2004" "wireless-tools" "Linux - Manuál programátora"
.\"
.\" NAME part
.\"
.SH JMÉNO
wireless \- Wireless Tools a Wireless Extensions
.\"
.\" SYNOPSIS part
.\"
.SH SYNTAXE
.B iwconfig
.br
.B iwpriv \-a
.br
.\"
.\" DESCRIPTION part
.\"
.SH POPIS
.B Wireless Extensions
jsou API, které umo¾òují manipulovat s bezdrátovými sí»ovými rozhraními.
Skládají se ze souboru nástrojù a konfiguraèních souborù. Podrobnìji
jsou popsány v Linux Wireless LAN Howto.
.br
.B Wireless Tools
se pou¾ívají ke zmìnì konfigurace bezdrátových sí»ových rozhraní za bìhu,
k získání jejich aktuální konfigurace, statistik a diagnostice.
Popisují je jejich vlastní manuálové stránky, viz odkazy ní¾e.
.br
.B Nastavení bezdrátového pøipojení
se v ka¾dé distribuci linuxu li¹í. Tato manuálová stránka bude obsahovat
postup nastavení pro nìkolik bì¾ných distribucí. Prozatím se podívejte do 
souboru DISTRIBUTIONS.txt, který je souèástí balíèku Wireless Tools.
.\"
.\" DEBIAN 3.0 part
.\"
.SH DEBIAN 3.0
V Debianu 3.0 (a vy¹¹ím) je mo¾né nastavit bezdrátová sí»ová zaøízení
nástrojem pro nastavení sítì
.BR ifupdown (8).
.TP
.B Soubor:
.I /etc/network/interfaces
.TP
.B Forma:
.RI wireless\- "<funkce> <hodnota>"
.br
wireless\-essid Home
.br
wireless\-mode Ad\-Hoc
.TP
.B Dal¹í informace:
.I /etc/network/if\-pre\-up.d/wireless\-tools
.br
.I /usr/share/doc/wireless\-tools/README.Debian
.\"
.\" SuSE 8.0 part
.\"
.SH SuSE 8.0
SuSE 8.0 (a vy¹¹í) integrovalo nastavení bezdrátového pøipojení do svých
sí»ových skriptù.
.TP
.B Nástroj:
.B Yast2
.TP
.B Soubor:
.I /etc/sysconfig/network/wireless
.br
.I /etc/sysconfig/network/ifcfg\-*
.TP
.B Forma:
.RI WIRELESS_ "<funkce>" = "<hodnota>"
.br
WIRELESS_ESSID="Home"
.br
WIRELESS_MODE=Ad\-Hoc
.TP
.B Dal¹í informace:
man ifup
.br
info scpm
.\"
.\" PCMCIA part
.\"
.SH PÙVODNÍ PCMCIA SKRIPTY
Pokud pou¾íváte pùvodní konfiguraèní skripty z balíèku Pcmcia,
Mù¾ete pou¾ít tuto metodu.
.TP
.B Soubor:
.I /etc/pcmcia/wireless.opts
.TP
.B Forma:
*,*,*,*)
.br
ESSID="Home"
.br
MODE="Ad-Hoc"
.br
;;
.TP
.B Dal¹í informace:
.I /etc/pcmcia/wireless
.br
Soubor
.IR "PCMCIA.txt" ,
který je souèástí balíèku Wireless Tools
.\"
.\" AUTHOR part
.\"
.SH AUTOR
Jean Tourrilhes \- jt@hpl.hp.com
.br
.I http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/
.\"
.\" TRANSLATION part
.\"
.SH PØEKLAD
Pavel Heimlich \- tropikhajma@seznam.cz, bøezen 2005 (wireless_tools.28pre4).
.\"
.\" SEE ALSO part
.\"
.SH DAL©Í INFORMACE
.BR iwconfig (8),
.BR iwlist (8),
.BR iwspy (8),
.BR iwpriv (8),
.BR iwevent (8).
