.TH TESTPRNS 1 "23 Jun 2001" "testprns 2.0.10"
.PP 
.SH "NAME" 
testprns \- check printer name for validity with smbd 
.PP 
.SH "SYNOPSIS" 
.PP 
\fBtestprns\fP printername [printcapname]
.PP 
.SH "DESCRIPTION" 
.PP 
This program is part of the \fBSamba\fP suite\&.
.PP 
\fBtestprns\fP is a very simple test program to determine whether a
given printer name is valid for use in a service to be provided by
\fBsmbd\fP\&.
.PP 
"Valid" in this context means "can be found in the printcap
specified"\&. This program is very stupid - so stupid in fact that it
would be wisest to always specify the printcap file to use\&.
.PP 
.SH "OPTIONS" 
.PP 
.IP 
.IP "\fBprintername\fP" 
The printer name to validate\&.
.IP 
Printer names are taken from the first field in each record in the
printcap file, single printer names and sets of aliases separated by
vertical bars ("|") are recognized\&. Note that no validation or
checking of the printcap syntax is done beyond that required to
extract the printer name\&. It may be that the print spooling system is
more forgiving or less forgiving than \fBtestprns\fP\&. However, if
\fBtestprns\fP finds the printer then \fBsmbd\fP should
do so as well\&.
.IP 
.IP "\fBprintcapname\fP" 
This is the name of the printcap file within
which to search for the given printer name\&.
.IP 
If no printcap name is specified \fBtestprns\fP will attempt to scan the
printcap file name specified at compile time\&.
.IP 
.PP 
.SH "FILES" 
.PP 
\fB/etc/printcap\fP This is usually the default printcap file to
scan\&. See \fBprintcap (5)\fP\&.
.PP 
.SH "DIAGNOSTICS" 
.PP 
If a printer is found to be valid, the message "Printer name
<printername> is valid" will be displayed\&.
.PP 
If a printer is found to be invalid, the message "Printer name
<printername> is not valid" will be displayed\&.
.PP 
All messages that would normally be logged during operation of the
\fBSamba\fP daemons are logged by this program to the
file \f(CWtest\&.log\fP in the current directory\&. The program runs at
debuglevel 3, so quite extensive logging information is written\&. The
log should be checked carefully for errors and warnings\&.
.PP 
Other messages are self-explanatory\&.
.PP 
.SH "SEE ALSO" 
.PP 
\fBprintcap (5)\fP, \fBsmbd (8)\fP, \fBsmbclient
(1)\fP
.PP 
.SH "AUTHOR" 
.PP 
The original Samba software and related utilities were created by
Andrew Tridgell samba@samba\&.org\&. Samba is now developed
by the Samba Team as an Open Source project similar to the way the
Linux kernel is developed\&.
.PP 
The original Samba man pages were written by Karl Auer\&. The man page
sources were converted to YODL format (another excellent piece of Open
Source software, available at
\fBftp://ftp\&.icce\&.rug\&.nl/pub/unix/\fP)
and updated for the Samba2\&.0 release by Jeremy Allison\&.
samba@samba\&.org\&.
.PP 
See \fBsamba (7)\fP to find out how to get a full
list of contributors and details on how to submit bug reports,
comments etc\&.
