#!/bin/bash

#
# Copyright (C) 2010 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

TS_TOPDIR="$(dirname $0)/../.."
TS_DESC="MD raid0 (whole-disks)"

. $TS_TOPDIR/functions.sh
ts_init "$*"
ts_skip_nonroot
[ -x /sbin/mdadm ] || ts_skip "missing mdadm"

set -o pipefail

ts_log "Initialize devices"
IMGNAME="${TS_OUTDIR}/${TS_TESTNAME}"

DEVICE1=$(ts_device_init 50 ${IMGNAME}1.img)
[ "$?" == 0 ] || ts_die "Cannot init device1"

DEVICE2=$(ts_device_init 50 ${IMGNAME}2.img)
[ "$?" == 0 ] || ts_die "Cannot init device2" $DEVICE1

MD_DEVNAME=md8
MD_DEVICE=/dev/${MD_DEVNAME}

/sbin/mdadm -q -S ${MD_DEVICE} &> /dev/null

ts_log "Create RAID device"
/sbin/mdadm -q --create ${MD_DEVICE} --metadata=0.90 --chunk=64 --level=0 \
	    --raid-devices=2 ${DEVICE1} ${DEVICE2} >> $TS_OUTPUT 2>&1

ts_log "Create partitions on RAID device"
$TS_CMD_FDISK ${MD_DEVICE} >> $TS_OUTPUT 2>&1 <<EOF
n
p
1

+10M
n
p
2


p
w
q
EOF

sleep 3

ts_log "Probe first RAID member"
$TS_CMD_BLKID -p -o udev $DEVICE1 2>&1 | sort >> $TS_OUTPUT

ts_log "Probe second RAID member"
$TS_CMD_BLKID -p -o udev $DEVICE1 2>&1 | sort >> $TS_OUTPUT

ts_log "Stop RAID device"
/sbin/mdadm -q -S ${MD_DEVICE} >> $TS_OUTPUT 2>&1

sleep 3

ts_log "Deinitialize devices"
ts_device_deinit $DEVICE1
ts_device_deinit $DEVICE2

ts_fdisk_clean
# remove generated UUIDs
sed -i -e 's/ID_FS_UUID.*//g' $TS_OUTPUT

ts_finalize
