#!/bin/bash

#
# Copyright (C) 2010 Karel Zak <kzak@redhat.com>
#
# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

TS_TOPDIR="$(dirname $0)/../.."
TS_DESC="MD raid1 (last partition)"

. $TS_TOPDIR/functions.sh
ts_init "$*"
ts_skip_nonroot

modprobe --dry-run --quiet scsi_debug
[ "$?" == 0 ] || ts_skip "missing scsi_debug module"
[ -x /sbin/mdadm ] || ts_skip "missing mdadm"

rmmod scsi_debug &> /dev/null
modprobe scsi_debug dev_size_mb=51 sector_size=512
[ "$?" == 0 ] || ts_die "Cannot init device"

sleep 3

DEVNAME=$(grep scsi_debug /sys/block/*/device/model | awk -F '/' '{print $4}')
[ "x${DEVNAME}" == "x" ] && ts_die "Cannot find device"

DEVICE="/dev/${DEVNAME}"

ts_log "Create partitions"
$TS_CMD_FDISK ${DEVICE} >> $TS_OUTPUT 2>&1 <<EOF
n
p
1

+25M
n
p
2


p
w
q
EOF

sleep 3
MD_DEVNAME=md8
MD_DEVICE=/dev/${MD_DEVNAME}

###exit 1

ts_log "Create RAID1 device"
/sbin/mdadm -q -S ${MD_DEVICE} &> /dev/null
/sbin/mdadm -q --create ${MD_DEVICE} --metadata=0.90 --chunk=64 --level=1 \
	    --raid-devices=2 ${DEVICE}1 ${DEVICE}2 >> $TS_OUTPUT 2>&1

sleep 3

ts_log "Probe whole-disk"
$TS_CMD_BLKID -p -o udev ${DEVICE} 2>&1 | sort >> $TS_OUTPUT

ts_log "Probe first RAID member"
$TS_CMD_BLKID -p -o udev ${DEVICE}1 2>&1 | sort >> $TS_OUTPUT

ts_log "Probe second RAID member"
$TS_CMD_BLKID -p -o udev ${DEVICE}2 2>&1 | sort >> $TS_OUTPUT

/sbin/mdadm -q -S ${MD_DEVICE} >> $TS_OUTPUT 2>&1

sleep 3
rmmod scsi_debug

ts_fdisk_clean
# remove generated UUIDs
sed -i -e 's/ID_FS_UUID.*//g' $TS_OUTPUT

ts_finalize
