#!/usr/bin/env python


bld.SAMBA_MODULE('service_winbind',
	source='wb_server.c wb_irpc.c wb_samba3_protocol.c wb_samba3_cmd.c wb_init_domain.c wb_dom_info.c wb_dom_info_trusted.c wb_sid2domain.c wb_name2domain.c wb_sids2xids.c wb_xids2sids.c wb_gid2sid.c wb_sid2uid.c wb_sid2gid.c wb_uid2sid.c wb_connect_lsa.c wb_connect_sam.c wb_cmd_lookupname.c wb_cmd_lookupsid.c wb_cmd_getdcname.c wb_cmd_getgrnam.c wb_cmd_getgrgid.c wb_cmd_getpwnam.c wb_cmd_getpwuid.c wb_cmd_userdomgroups.c wb_cmd_usersids.c wb_cmd_list_groups.c wb_cmd_list_trustdom.c wb_cmd_list_users.c wb_cmd_setpwent.c wb_cmd_getpwent.c wb_cmd_getgrent.c wb_cmd_setgrent.c wb_cmd_getgroups.c wb_pam_auth.c wb_sam_logon.c wb_update_rodc_dns.c',
	autoproto='wb_proto.h',
	subsystem='service',
	init_function='server_service_winbind_init',
	deps='WB_HELPER IDMAP NDR_WINBIND process_model RPC_NDR_LSA dcerpc-samr PAM_ERRORS cli-ldap samba-net LIBSAMBA_TSOCKET',
	internal_module=False,
	)


bld.SAMBA_SUBSYSTEM('WB_HELPER',
	source='wb_async_helpers.c wb_utils.c',
	autoproto='wb_helper.h',
	public_deps='RPC_NDR_LSA dcerpc-samr'
	)


bld.SAMBA_SUBSYSTEM('IDMAP',
	source='idmap.c',
	autoproto='idmap_proto.h',
	public_deps='samdb-common ldbsamba'
	)

bld.SAMBA_BINARY('wbinfo',
	source='../../nsswitch/wbinfo.c',
	deps='samba-util LIBCLI_AUTH popt POPT_SAMBA winbind-client wbclient tevent UTIL_TEVENT LIBASYNC_REQ security ndr NDR_SECURITY'
	)
