#!/bin/bash

# Copyright (C) 2011 Karel Zak <kzak@redhat.com>

TS_TOPDIR="$(dirname $0)/../.."
TS_DESC="table diffs"

. $TS_TOPDIR/functions.sh
ts_init "$*"

TESTPROG="$TS_HELPER_LIBMOUNT_TABDIFF"

[ -x $TESTPROG ] || ts_skip "test not compiled"

ts_init_subtest "mount"
$TESTPROG --diff $TS_SELF/files/mountinfo_u $TS_SELF/files/mountinfo &> $TS_OUTPUT
ts_finalize_subtest

ts_init_subtest "umount"
$TESTPROG --diff $TS_SELF/files/mountinfo $TS_SELF/files/mountinfo_u  &> $TS_OUTPUT
ts_finalize_subtest

ts_init_subtest "remount"
$TESTPROG --diff $TS_SELF/files/mountinfo $TS_SELF/files/mountinfo_re  &> $TS_OUTPUT
ts_finalize_subtest

ts_init_subtest "move"
$TESTPROG --diff $TS_SELF/files/mountinfo $TS_SELF/files/mountinfo_mv  &> $TS_OUTPUT
ts_finalize_subtest

ts_finalize
