#!/bin/sh
# Modified version of tridge's backtrace script.
# we want everything on stderr, so the program is not disturbed
exec 1>&2

PID=$1
TMPFILE=$prefix/backtrace.$$
cat << EOF  > $TMPFILE
set height 0
up 8
bt full
quit
EOF
gdb -x $TMPFILE $prefix/sbin/smbd $PID
/bin/rm -f $TMPFILE
