/*
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */
#ifndef DONGLES
#define DONGLES

enum DONGLE_LIST_T {
	UNKNOWNDEV				,
	SN_MU_Q101				,
	SN_OPTION_ICON225			,
	SN_Option_GlobeSurfer_Icon		,
	SN_Option_GlobeSurfer_Icon72		,
	SN_Option_GlobeTrotter_GT_MAX36		,
	SN_Option_GlobeTrotter_GT_MAX72 	,
	SN_Option_GlobeTrotter_EXPRESS72	,
	SN_Option_iCON210			,
	SN_Option_GlobeTrotter_HSUPA_Modem	,
	SN_Option_iCON401			,
	SN_Vodafone_K3760			,
	SN_ATT_USBConnect_Quicksilver		,
	SN_Huawei_EC156				,
	SN_Huawei_E169				,
	SN_Huawei_E220				,
	SN_Huawei_E180				,
	SN_Huawei_Exxx				,
	SN_Huawei_E173				,
	SN_Huawei_E630				,
	SN_Huawei_E270				,
	SN_Huawei_E1550				,
	SN_Huawei_E1612				,
	SN_Huawei_E1690				,
	SN_Huawei_K3765				,
	SN_Huawei_K4505				,
	SN_ZTE_MF620				,
	SN_ZTE_MF622				,
	SN_ZTE_MF628				,
	SN_ZTE_MF626				,
	SN_ZTE_AC8710				,
	SN_ZTE_AC2710				,
	SN_ZTE6535_Z				,
	SN_ZTE_K3520_Z				,
	SN_ZTE_MF110				,
	SN_ZTE_K3565				,
	SN_ONDA_MT503HS				,
	SN_ONDA_MT505UP				,
	SN_Novatel_Wireless_Ovation_MC950D	,
	SN_Novatel_U727				,
	SN_Novatel_MC990D			,
	SN_Novatel_U760				,
	SN_Alcatel_X020				,
	SN_Alcatel_X200				,
	SN_AnyDATA_ADU_500A			,
	SN_BandLuxe_C120			,
	SN_BandLuxe_C270			,
	SN_Solomon_S3Gm660			,
	SN_C_motechD50				,
	SN_C_motech_CGU628			,
	SN_Toshiba_G450				,
	SN_UTStarcom_UM175			,
	SN_Hummer_DTM5731			,
	SN_A_Link_3GU				,
	SN_Sierra_Wireless_Compass597		,
	SN_Sierra881U				,
	SN_Sony_Ericsson_MD400			,
	SN_LG_LDU_1900D				,
	SN_Samsung_SGH_Z810			,
	SN_MobiData_MBD_200HU			,
	SN_ST_Mobile				,
	SN_BSNL_310G				,
	SN_BSNL_LW272				,
	SN_MyWave_SW006				,
	SN_Cricket_A600				,
	SN_EpiValley_SEC7089			,
	SN_Samsung_U209				,
	SN_D_Link_DWM162_U5			,
	SN_Novatel_MC760			,
	SN_Philips_TalkTalk			,
	SN_HuaXing_E600				,
	SN_C_motech_CHU_629S			,
	SN_Sagem9520				,
	SN_Nokia_CS15				,
	SN_Vodafone_MD950			,
	SN_Siptune_LM75				,
/* since 0715 */
	SN_SU9800				,
	SN_ZTEAX226				,
	SN_OPTION_ICON_461			,
	SN_Huawei_K3771				,
	SN_Huawei_K3770				,
	SN_Mobile_Action			,
	SN_HP_P1102				,
	SN_Visiontek_82GH			,
	SN_ZTE_MF190_var			,
	SN_ZTE_MF192				,
	SN_ZTE_MF691				,
	SN_CHU_629S				,
	SN_JOA_LM_700r				,
	SN_ZTE_MF190				,
	SN_ZTE_ffe				,
	SN_SE_MD400G				,
	SN_DLINK_DWM_156_A1			,
	SN_DLINK_DWM_156_A3			,
	SN_DLINK_DWM_156_A7_1			,
	SN_DLINK_DWM_156_A7_2			,
	SN_DLINK_DWM_156_A7_3			,
	SN_Huawei_U8220				,
	SN_Huawei_T_Mobile_NL			,
	SN_ZTE_K3806Z				,
	SN_Vibe_3G				,
	SN_ZTE_MF637				,
	SN_ONDA_MW836UP_K			,
	SN_Huawei_V725				,
	SN_Huawei_ET8282			,
	SN_Huawei_E352				,
	SN_Huawei_BM358				,
	SN_Haier_CE_100				,
	SN_Franklin_Wireless_U210_var		,
	SN_Exiss_E_190				,
	SN_dealextreme				,
	SN_CHU_628S				,
	SN_MediaTek_Wimax_USB			,
	SN_AirPlus_MCD_800			,
	SN_UMW190				,
	SN_LG_AD600				,
	SN_GW_D301				,
	SN_Qtronix_EVDO_3G			,
	SN_Nokia_CS18				,
	SN_Nokia_CS17				,
	SN_Huawei_EC168C			,
	SN_Olicard_145				,
	SN_ONDA_MW833UP				,
	SN_Kobil_mIdentity_3G_2			,
	SN_Kobil_mIdentity_3G_1			,
	SN_Samsung_GT_B3730			,
	SN_BSNL_Capitel				,
	SN_ZTE_WCDMA_from_BNSL			,
	SN_Nokia_CS10				,
	SN_Huawei_U8110				,
	SN_ONDA_MW833UP_2			,
	SN_Netgear_WNDA3200			,
	SN_Huawei_R201				,
	SN_Huawei_K4605				,
	SN_LG_LUU_2100TI			,
	SN_LG_L_05A				,
	SN_ZTE_MU351				,
	SN_ZTE_MF110_var			,
	SN_Olicard_100				,
	SN_ZTE_MF112				,
	SN_Alcatel_X220L			,
	SN_Franklin_Wireless_U210		,
	SN_ZTE_K3805_Z				,
	SN_SE_MD300				,
	SN_Digicom_8E4455			,
	SN_Kyocera_W06K				,
	SN_LG_HDM_2100				,
	SN_Beceem_BCSM250			,
	SN_Huawei_U7510				,
	SN_ZTE_AC581				,
	SN_UTStarcom_UM185E			,
	SN_AVM_Fritz				,
	SN_Beceem_BCSM250_ASUS			,
	SN_ZTEAX320				,
/* since 0818 */
	SN_SU_8000U                             ,
	SN_Cisco_AM10                           ,
	SN_Huawei_EC122                         ,
	SN_Huawei_EC306                         ,
	SN_Sierra_U598                          ,
	SN_NovatelU720                          ,
	SN_Pantech_UM150                        ,
	SN_Pantech_UM175                        ,
	SN_Sierra_U595                          ,
	SN_Huawei_EC1262                        ,
/* since 120703 */
	SN_Qisda_H21                            ,
	SN_StrongRising_Air_FlexiNet            ,
	SN_BandLuxe_C339                        ,
	SN_Celot_CT680                          ,
	SN_Huawei_E353                          ,
	SN_Haier_CE682                          ,
	SN_LG_L_02C_LTE                         ,
	SN_LG_SD711                             ,
	SN_LG_L_08C                             ,
	SN_IODATA_WMX2_U                        ,
	SN_Option_GI1515                        ,
	SN_LG_L_07A                             ,
	SN_ZTE_A371B                            ,
	SN_ZTE_MF652                            ,
	SN_ZTE_MF652_VAR                        ,
	SN_T_W_WU160                            ,
	SN_Nokia_CS_21M_02                      ,
	SN_Telewell_TW_3G                       ,
	SN_ZTE_MF637_2                          ,
	SN_Samsung_GT_B1110                     ,
	SN_ZTE_MF192_VAR                        ,
	SN_MediaTek_MT6276M                     ,
	SN_Tata_Photon_plus                     ,
	SN_Option_Globetrotter                  ,
	SN_Option_ICON_711                      ,
	SN_Celot_K300                           ,
	SN_HISENSE_E910                         ,
	SN_Huawei_K5005                         ,
	SN_Huawei_E173_MoiveStar                ,
	SN_Onda_MSA14_4                         ,
	SN_WeTelecom_WMD300                     ,
	SN_Huawei_K5150                         ,
	SN_ZTE_MF823				,
	SN_Huawei_E3276S150			,
/* since 141112 */
	SN_Alcatel_TL131			,
	SN_AVM_Fritz_V2				,
	SN_Quanta_MobileGenie_4G_lte		,
	SN_Pantech_LTE				,
	SN_BlackBerry_Q10			,
	SN_Huawei_K4305				,
	SN_Huawei_E3276s			,
	SN_Teracom_LW272			,
	SN_TP_Link_MA260			,
	SN_Quanta_1K3_LTE			,
	SN_WeTelecom_WMD200			,
	SN_ZTE_MF680				,
	SN_ZTE_MF656A				,
	SN_ZTE_MF196				,
	SN_Mediatek_MT6229			,
	SN_DLINK_DWR_510			,
	SN_Novatel_MC996D			,
	SN_Pantech_UML290			,
	SN_Onda_MT8205_LTE			,
	SN_Axesstel_Modems			,
	SN_Nokia_CS_12				,
	SN_Onda_WM301				,
	SN_Onda_TM201_14_4			,
	SN_Huawei_E3131				,
	SN_Huawei_E3372				,
	SN_Huawei_E303u				,
	SN_Huawei_E3531s			,
	SN_END
};





#endif
