#!/bin/bash

# Copyright (C) 2011 Karel Zak <kzak@redhat.com>

TS_TOPDIR="$(dirname $0)/../.."
TS_DESC="config"

# Don't execute this test by default, --force required
TS_OPTIONAL="yes"

. $TS_TOPDIR/functions.sh
ts_init "$*"

[ -x /usr/bin/readelf ] || ts_skip "readelf(1) not found"
[ -x /usr/bin/file ] || ts_skip "file(1) not found"

config_gen_dir="$top_srcdir/tools"
. $config_gen_dir/config-gen-functions.sh

[ -n "$CFLAGS" ] && export CFLAGS="$CFLAGS"

cd $top_builddir && make -j clean &> /dev/null

for conf in $config_gen_dir/config-gen.d/*.conf; do
	ts_init_subtest $(basename $conf | sed 's/\.conf//')

	opts=$(ul_get_configuration $conf)

	olddir=$(pwd)
	cd $top_builddir

	./configure $opts &> /dev/null
	make -j &> /dev/null

	bins=$(find . -type f -perm /a+x | sort)
	for b in $bins; do
		libs=$(readelf --dynamic $b 2> /dev/null   | \
			awk '/NEEDED/ { print $5 }' | \
			sed 's:\[::g; s:\..*::g; s:libc::g' | \
			sort -u | tr '\n' ' ')

		if [ -n "$libs" ]; then
			echo "$(basename $b): $libs" >> $TS_OUTPUT
		else
			fres=$(file $b)
			case $fres in
			*statically*)
				echo "$(basename $b): STATIC" >> $TS_OUTPUT
				;;
			*) # ignore scripts, ...etc.
				;;
			esac
		fi
	done
	make -j clean &> /dev/null
	cd $olddir

	ts_finalize_subtest
done

ts_finalize
