.\"             -*-Nroff-*-
.\"  This page Copyright (C) 1993 Matt Welsh, mdw@sunsite.unc.edu.
.\"  Freely distributable under the terms of the GPL
.TH FREE 1 "20 Mar 1993 " "Cohesive Systems" "Linux User's Manual"
.SH NAME
free \- Display amount of free and used memory in the system
.SH SYNOPSIS
.BR "free " [ "\-b" " | " "\-k" " | " "\-m" "] [" "\-o" "] [" "\-s"
.I delay
.RB "] [" "\-t" "] [" "\-V" ]
.SH DESCRIPTION
\fBfree\fP displays the total amount of free and used physical and swap 
memory in the system, as well as the buffers used by the kernel.
The shared memory column should be ignored; it is obsolete.
.SS Options
The \fB-b\fP switch displays the amount of memory in bytes; the 
\fB-k\fP switch (set by default) displays it in kilobytes; the \fB-m\fP
switch displays it in megabytes.
.PP
The \fB-t\fP switch displays a line containing the totals.
.PP
The \fB-o\fP switch disables the display of a "buffer adjusted" line.
If the -o option is not specified, \fBfree\fP subtracts buffer memory
from the used memory and adds it to the free memory reported.
.PP
The \fB-s\fP switch activates continuous polling \fIdelay\fP seconds apart. You
may actually specify any floating point number for \fIdelay\fP, 
.BR usleep (3)
is used for microsecond resolution delay times.
.PP
The \fB\-V\fP displays version information.
.SH FILES
.ta
.IR /proc/meminfo "\-\- memory information"
.fi

.SH "SEE ALSO"
.BR ps (1),
.BR slabtop (1),
.BR vmstat (8),
.BR top(1)

.SH AUTHORS
Written by Brian Edmonds. 

Send bug reports to <albert@users.sf.net>

