.\"             -*-Nroff-*-
.\"  This page Copyright (C) 1993 Matt Welsh, mdw@tc.cornell.edu.
.\"  Freely distributable under the terms of the GPL
.TH TLOAD 1 "20 Mar 1993 " "Cohesive Systems" "Linux User's Manual"
.SH NAME
tload \- graphic representation of system load average
.SH SYNOPSIS
.B tload
.RB [ "\-V" "] [" "\-s"
.IR scale "] ["
.BI "\-d" " delay"
.RI "] [" tty ]
.SH DESCRIPTION
\fBtload\fP prints a graph of the current system load average to the 
specified \fItty\fP (or the tty of the tload process if none is specified).
.SS Options
The
.BI "\-s" " scale"
option allows a vertical scale to be specified for the
display (in characters between graph ticks); thus, a smaller value
represents a larger scale, and vice versa.

The
.BI "\-d" " delay"
sets the delay between graph updates in seconds.
.PP
.SH FILES
.I /proc/loadavg
load average information

.SH "SEE ALSO"
.BR ps (1),
.BR top (1),
.BR uptime (1),
.BR w (1)

.SH BUGS
The
.BI "\-d" " delay"
option sets the time argument for an
.BR alarm (2);
if -d 0 is specified, the alarm is set to 0, which will never send the
.B SIGALRM
and update the display.

.SH AUTHORS
Branko Lankester, David Engel <david@ods.com>, and 
Michael K. Johnson <johnsonm@redhat.com>.

Please send bug reports to <albert@users.sf.net>
