.\"             -*-Nroff-*-
.\"
.TH UPTIME 1 "26 Jan 1993" "Cohesive Systems" "Linux User's Manual"
.SH NAME
uptime \- Tell how long the system has been running.
.SH SYNOPSIS
.B uptime
.br
.BR uptime " [" "\-V" ]
.SH DESCRIPTION
.B uptime
gives a one line display of the following information.
The current time,
how long the system has been running,
how many users are currently logged on,
and the system load averages for the past 1, 5, and 15 minutes.
.sp
This is the same information contained in the header line displayed by 
.BR w (1).
.SH FILES
.IR /var/run/utmp "	information about who is currently logged on"
.br
.IR /proc "	process information"
.SH AUTHORS
.B uptime
was written by Larry Greenfield <greenfie@gauss.rutgers.edu> and
Michael K. Johnson <johnsonm@sunsite.unc.edu>.

Please send bug reports to <albert@users.sf.net>
.SH "SEE ALSO"
.BR ps (1),
.BR top (1),
.BR utmp (5),
.BR w (1)
