.\"             -*-Nroff-*-
.\"
.TH W 1 "8 Dec 1993 " " " "Linux User's Manual"
.SH NAME
w \- Show who is logged on and what they are doing.
.SH SYNOPSIS
.B w \-
.RB [ husfV ]
.RI [ user ]
.SH DESCRIPTION
.B "w "
displays information about the users currently on the machine,
and their processes.
The header shows, in this order,  the current time,
how long the system has been running,
how many users are currently logged on,
and the system load averages for the past 1, 5, and 15 minutes.
.sp
The following entries are displayed for each user:
login name, the tty name, the remote host, login time, idle time, JCPU, PCPU,
and the command line of their current process.
.sp
The JCPU time is the time used by all processes attached to the tty.  It
does not include past background jobs, but does include currently
running background jobs.
.sp
The PCPU time is the time used by the current process, named in the "what"
field.

.PP
.SH "COMMAND\-LINE OPTIONS"
.TP 0.5i
.B "\-h "
Don't print the header.
.TP 0.5i
.B "\-u "
Ignores the username while figuring out the current process and cpu
times.  To demonstrate this, do a "su" and do a "w" and a "w -u".
.TP 0.5i
.B "\-s "
Use the short format.
Don't print the login time, JCPU or PCPU times.
.TP 0.5i
.B "\-f "
Toggle printing the
.B from
(remote hostname) field.  The default as
released is for the
.B from
field to not be printed, although your system administrator or
distribution maintainer may have compiled a version in which the
.B from
field is shown by default.
.TP 0.5i
.B "\-V "
Display version information.
.TP 0.5i
.B "user "
Show information about the specified user only.

.SH FILES
.TP
.I /var/run/utmp
information about who is currently logged on
.TP
.I /proc
process information
.PP

.SH "SEE ALSO"
.BR free (1),
.BR ps (1),
.BR top (1),
.BR uptime (1),
.BR utmp (5),
.BR who (1)

.SH AUTHORS
.B w
was re-written almost entirely by Charles Blake, based on the version by Larry
Greenfield <greenfie@gauss.rutgers.edu> and Michael K. Johnson
<johnsonm@redhat.com>.

Please send bug reports to <albert@users.sf.net>
