.TH bon_csv2html 1 
.SH "NAME"
.BR bon_csv2html
program to convert CSV format Bonnie++ data to a HTML form
using tables suitable for display on a web page. NB Lynx can't display this
properly, and due to the size it probably requires 1024x768 monitor to display
properly.
.P
.BR bon_csv2txt
program to convert CSV format Bonnie++ data to plain\-text format
suitable for pasting into an email or reading on a Braille display.

.SH "DESCRIPTION"
They take CSV format (comma\-delimited spreadsheet files AKA Comma Seperated
Values in MS land) data on standard input and produce HTML or plain text on
standard output respectively.

.SH "AUTHOR"
These programs were written by Russell Coker <russell@coker.com.au>. May be
freely used and distributed without restriction.

.SH "AVAILABILITY"
The source is available from http://www.coker.com.au/bonnie++ .
.P
See http://etbe.coker.com.au/category/benchmark for further information.
