.\"
.\"  chfn.1 -- change your finger information
.\"  (c) 1994 by salvatore valente <svalente@athena.mit.edu>
.\"
.\"  this program is free software.  you can redistribute it and
.\"  modify it under the terms of the gnu general public license.
.\"  there is no warranty.
.\"
.\"  $Author: faith $
.\"  $Revision: 1.1 $
.\"  $Date: 1995/03/12 01:29:16 $
.\"
.TH CHFN 1 "July 2009" "util-linux" "User Commands"
.SH NAME
chfn \- change your finger information
.SH SYNOPSIS
.B chfn
.RB [ \-f
.IR full-name ]
.RB [ \-o
.IR office ]
,RB [ \-p
.IR office-phone ]
.RB [ \-h
.IR home-phone ]
.BR \-u ]
.RB [ \-v ]
.RI [ username ]
.SH DESCRIPTION
.B chfn
is used to change your finger information.  This information is
stored in the
.I /etc/passwd
file, and is displayed by the
.B finger
program.  The Linux
.B finger
command will display four pieces of information that can be changed by
.BR chfn :
your real name, your work room and phone, and your home phone.

.B chfn
is used to change local entries only. Use ypchfn, lchfn or any other
implementation for non-local entries.
.SS COMMAND LINE
Any of the four pieces of information can be specified on the command
line.  If no information is given on the command line,
.B chfn
enters interactive mode.
.SS INTERACTIVE MODE
In interactive mode,
.B chfn
will prompt for each field.  At a prompt, you can enter the new information,
or just press return to leave the field unchanged.  Enter the keyword
"none" to make the field blank.
.SH OPTIONS
.TP
.BI "\-f, \-\-full-name " full-name
Specify your real name.
.TP
.BI "\-o, \-\-office " office
Specify your office room number.
.TP
.BI "\-p, \-\-office-phone " office-phone
Specify your office phone number.
.TP
.BI "\-h, \-\-home-phone " home-phone
Specify your home phone number.
.TP
.B "\-u, \-\-help"
Print a usage message and exit.
.TP
.B "-v, \-\-version"
Print version information and exit.
.SH "SEE ALSO"
.BR finger (1),
.BR passwd (5)
.SH AUTHOR
Salvatore Valente <svalente@mit.edu>
.SH AVAILABILITY
The chfn command is part of the util-linux package and is available from
ftp://ftp.kernel.org/pub/linux/utils/util-linux/.
