#!/usr/bin/env python

bld.SAMBA_LIBRARY('credentials',
	source='credentials.c',
	autoproto='credentials_proto.h',
	public_headers='credentials.h',
	deps='LIBCRYPTO errors events LIBCLI_AUTH security CREDENTIALS_SECRETS CREDENTIALS_KRB5',
	private_library=True
	)

bld.SAMBA_SUBSYSTEM('CREDENTIALS_KRB5',
	source='credentials_krb5.c',
	deps='KERBEROS_UTIL gssapi credentials',
	public_deps='com_err authkrb5',
	)

bld.SAMBA_SUBSYSTEM('CREDENTIALS_SECRETS',
	source='credentials_secrets.c',
	deps='CREDENTIALS_KRB5 CREDENTIALS_NTLM ldb samdb-common',
	)

bld.SAMBA_SUBSYSTEM('CREDENTIALS_NTLM',
	source='credentials_ntlm.c',
	deps='credentials')

bld.SAMBA_PYTHON('pycredentials',
	source='pycredentials.c',
	public_deps='credentials cmdline-credentials pytalloc-util pyparam_util CREDENTIALS_KRB5 CREDENTIALS_SECRETS',
	realname='samba/credentials.so'
	)

