#!/bin/sh

# find object files containing a symbol
# for example:
#   nmfind foo_function $(find bin/default -name '*.o')

TARGET=$1
shift
for f in $*; do
if nm $f 2>&1 | grep $TARGET > /dev/null; then
  echo [$f]
  nm $f | grep $TARGET
  echo
fi
done
