'\" t
.\"     Title: winbindd
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 09/18/2013
.\"    Manual: System Administration tools
.\"    Source: Samba 3.6
.\"  Language: English
.\"
.TH "WINBINDD" "8" "09/18/2013" "Samba 3\&.6" "System Administration tools"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
winbindd \- Name Service Switch daemon for resolving names from NT servers
.SH "SYNOPSIS"
.HP \w'\ 'u
winbindd [\-D] [\-F] [\-S] [\-i] [\-d\ <debug\ level>] [\-s\ <smb\ config\ file>] [\-n]
.SH "DESCRIPTION"
.PP
This program is part of the
\fBsamba\fR(7)
suite\&.
.PP
winbindd
is a daemon that provides a number of services to the Name Service Switch capability found in most modern C libraries, to arbitrary applications via PAM and
ntlm_auth
and to Samba itself\&.
.PP
Even if winbind is not used for nsswitch, it still provides a service to
smbd,
ntlm_auth
and the
pam_winbind\&.so
PAM module, by managing connections to domain controllers\&. In this configuration the
\m[blue]\fBidmap config * : range\fR\m[]
parameter is not required\&. (This is known as `netlogon proxy only mode\*(Aq\&.)
.PP
The Name Service Switch allows user and system information to be obtained from different databases services such as NIS or DNS\&. The exact behaviour can be configured through the
/etc/nsswitch\&.conf
file\&. Users and groups are allocated as they are resolved to a range of user and group ids specified by the administrator of the Samba system\&.
.PP
The service provided by
winbindd
is called `winbind\*(Aq and can be used to resolve user and group information from a Windows NT server\&. The service can also provide authentication services via an associated PAM module\&.
.PP
The
pam_winbind
module supports the
\fIauth\fR,
\fIaccount\fR
and
\fIpassword\fR
module\-types\&. It should be noted that the
\fIaccount\fR
module simply performs a getpwnam() to verify that the system can obtain a uid for the user, as the domain controller has already performed access control\&. If the
libnss_winbind
library has been correctly installed, or an alternate source of names configured, this should always succeed\&.
.PP
The following nsswitch databases are implemented by the winbindd service:
.PP
hosts
.RS 4
This feature is only available on IRIX\&. User information traditionally stored in the
hosts(5)
file and used by
gethostbyname(3)
functions\&. Names are resolved through the WINS server or by broadcast\&.
.RE
.PP
passwd
.RS 4
User information traditionally stored in the
passwd(5)
file and used by
getpwent(3)
functions\&.
.RE
.PP
group
.RS 4
Group information traditionally stored in the
group(5)
file and used by
getgrent(3)
functions\&.
.RE
.PP
For example, the following simple configuration in the
/etc/nsswitch\&.conf
file can be used to initially resolve user and group information from
/etc/passwd
and
/etc/group
and then from the Windows NT server\&.
.sp
.if n \{\
.RS 4
.\}
.nf
passwd:         files winbind
group:          files winbind
## only available on IRIX: use winbind to resolve hosts:
# hosts:        files dns winbind
## All other NSS enabled systems should use libnss_wins\&.so like this:
hosts:          files dns wins

.fi
.if n \{\
.RE
.\}
.PP
The following simple configuration in the
/etc/nsswitch\&.conf
file can be used to initially resolve hostnames from
/etc/hosts
and then from the WINS server\&.
.sp
.if n \{\
.RS 4
.\}
.nf
hosts:		files wins
.fi
.if n \{\
.RE
.\}
.SH "OPTIONS"
.PP
\-D
.RS 4
If specified, this parameter causes the server to operate as a daemon\&. That is, it detaches itself and runs in the background on the appropriate port\&. This switch is assumed if
winbindd
is executed on the command line of a shell\&.
.RE
.PP
\-F
.RS 4
If specified, this parameter causes the main
winbindd
process to not daemonize, i\&.e\&. double\-fork and disassociate with the terminal\&. Child processes are still created as normal to service each connection request, but the main process does not exit\&. This operation mode is suitable for running
winbindd
under process supervisors such as
supervise
and
svscan
from Daniel J\&. Bernstein\*(Aqs
daemontools
package, or the AIX process monitor\&.
.RE
.PP
\-S
.RS 4
If specified, this parameter causes
winbindd
to log to standard output rather than a file\&.
.RE
.PP
\-d|\-\-debuglevel=level
.RS 4
\fIlevel\fR
is an integer from 0 to 10\&. The default value if this parameter is not specified is 0\&.
.sp
The higher this value, the more detail will be logged to the log files about the activities of the server\&. At level 0, only critical errors and serious warnings will be logged\&. Level 1 is a reasonable level for day\-to\-day running \- it generates a small amount of information about operations carried out\&.
.sp
Levels above 1 will generate considerable amounts of log data, and should only be used when investigating a problem\&. Levels above 3 are designed for use only by developers and generate HUGE amounts of log data, most of which is extremely cryptic\&.
.sp
Note that specifying this parameter here will override the
\m[blue]\fBlog level\fR\m[]
parameter in the
smb\&.conf
file\&.
.RE
.PP
\-V|\-\-version
.RS 4
Prints the program version number\&.
.RE
.PP
\-s|\-\-configfile <configuration file>
.RS 4
The file specified contains the configuration details required by the server\&. The information in this file includes server\-specific information such as what printcap file to use, as well as descriptions of all the services that the server is to provide\&. See
smb\&.conf
for more information\&. The default configuration file name is determined at compile time\&.
.RE
.PP
\-l|\-\-log\-basename=logdirectory
.RS 4
Base directory name for log/debug files\&. The extension
\fB"\&.progname"\fR
will be appended (e\&.g\&. log\&.smbclient, log\&.smbd, etc\&.\&.\&.)\&. The log file is never removed by the client\&.
.RE
.PP
\-h|\-\-help
.RS 4
Print a summary of command line options\&.
.RE
.PP
\-i
.RS 4
Tells
winbindd
to not become a daemon and detach from the current terminal\&. This option is used by developers when interactive debugging of
winbindd
is required\&.
winbindd
also logs to standard output, as if the
\-S
parameter had been given\&.
.RE
.PP
\-n
.RS 4
Disable caching\&. This means winbindd will always have to wait for a response from the domain controller before it can respond to a client and this thus makes things slower\&. The results will however be more accurate, since results from the cache might not be up\-to\-date\&. This might also temporarily hang winbindd if the DC doesn\*(Aqt respond\&.
.RE
.SH "NAME AND ID RESOLUTION"
.PP
Users and groups on a Windows NT server are assigned a security id (SID) which is globally unique when the user or group is created\&. To convert the Windows NT user or group into a unix user or group, a mapping between SIDs and unix user and group ids is required\&. This is one of the jobs that
winbindd
performs\&.
.PP
As winbindd users and groups are resolved from a server, user and group ids are allocated from a specified range\&. This is done on a first come, first served basis, although all existing users and groups will be mapped as soon as a client performs a user or group enumeration command\&. The allocated unix ids are stored in a database and will be remembered\&.
.PP
WARNING: The SID to unix id database is the only location where the user and group mappings are stored by winbindd\&. If this store is deleted or corrupted, there is no way for winbindd to determine which user and group ids correspond to Windows NT user and group rids\&.
.SH "CONFIGURATION"
.PP
Configuration of the
winbindd
daemon is done through configuration parameters in the
\fBsmb.conf\fR(5)
file\&. All parameters should be specified in the [global] section of smb\&.conf\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\m[blue]\fBwinbind separator\fR\m[]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\m[blue]\fBidmap config * : range\fR\m[]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\m[blue]\fBidmap config * : backend\fR\m[]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\m[blue]\fBwinbind cache time\fR\m[]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\m[blue]\fBwinbind enum users\fR\m[]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\m[blue]\fBwinbind enum groups\fR\m[]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\m[blue]\fBtemplate homedir\fR\m[]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\m[blue]\fBtemplate shell\fR\m[]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\m[blue]\fBwinbind use default domain\fR\m[]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\m[blue]\fBwinbind: rpc only\fR\m[]
Setting this parameter forces winbindd to use RPC instead of LDAP to retrieve information from Domain Controllers\&.
.RE
.SH "EXAMPLE SETUP"
.PP
To setup winbindd for user and group lookups plus authentication from a domain controller use something like the following setup\&. This was tested on an early Red Hat Linux box\&.
.PP
In
/etc/nsswitch\&.conf
put the following:
.sp
.if n \{\
.RS 4
.\}
.nf
passwd: files winbind
group:  files winbind
.fi
.if n \{\
.RE
.\}
.PP
In
/etc/pam\&.d/*
replace the
\fI auth\fR
lines with something like this:
.sp
.if n \{\
.RS 4
.\}
.nf
auth  required    /lib/security/pam_securetty\&.so
auth  required	  /lib/security/pam_nologin\&.so
auth  sufficient  /lib/security/pam_winbind\&.so
auth  required    /lib/security/pam_unix\&.so \e
                  use_first_pass shadow nullok
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.PP
The PAM module pam_unix has recently replaced the module pam_pwdb\&. Some Linux systems use the module pam_unix2 in place of pam_unix\&.
.sp .5v
.RE
.PP
Note in particular the use of the
\fIsufficient \fR
keyword and the
\fIuse_first_pass\fR
keyword\&.
.PP
Now replace the account lines with this:
.PP
account required /lib/security/pam_winbind\&.so
.PP
The next step is to join the domain\&. To do that use the
net
program like this:
.PP
net join \-S PDC \-U Administrator
.PP
The username after the
\fI\-U\fR
can be any Domain user that has administrator privileges on the machine\&. Substitute the name or IP of your PDC for "PDC"\&.
.PP
Next copy
libnss_winbind\&.so
to
/lib
and
pam_winbind\&.so
to
/lib/security\&. A symbolic link needs to be made from
/lib/libnss_winbind\&.so
to
/lib/libnss_winbind\&.so\&.2\&. If you are using an older version of glibc then the target of the link should be
/lib/libnss_winbind\&.so\&.1\&.
.PP
Finally, setup a
\fBsmb.conf\fR(5)
containing directives like the following:
.sp
.if n \{\
.RS 4
.\}
.nf
[global]
	winbind separator = +
        winbind cache time = 10
        template shell = /bin/bash
        template homedir = /home/%D/%U
        idmap config * : range = 10000\-20000
        workgroup = DOMAIN
        security = domain
        password server = *
.fi
.if n \{\
.RE
.\}
.PP
Now start winbindd and you should find that your user and group database is expanded to include your NT users and groups, and that you can login to your unix box as a domain user, using the DOMAIN+user syntax for the username\&. You may wish to use the commands
getent passwd
and
getent group
to confirm the correct operation of winbindd\&.
.SH "NOTES"
.PP
The following notes are useful when configuring and running
winbindd:
.PP
\fBnmbd\fR(8)
must be running on the local machine for
winbindd
to work\&.
.PP
PAM is really easy to misconfigure\&. Make sure you know what you are doing when modifying PAM configuration files\&. It is possible to set up PAM such that you can no longer log into your system\&.
.PP
If more than one UNIX machine is running
winbindd, then in general the user and groups ids allocated by winbindd will not be the same\&. The user and group ids will only be valid for the local machine, unless a shared
\m[blue]\fBidmap config * : backend\fR\m[]
is configured\&.
.PP
If the the Windows NT SID to UNIX user and group id mapping file is damaged or destroyed then the mappings will be lost\&.
.SH "SIGNALS"
.PP
The following signals can be used to manipulate the
winbindd
daemon\&.
.PP
SIGHUP
.RS 4
Reload the
\fBsmb.conf\fR(5)
file and apply any parameter changes to the running version of winbindd\&. This signal also clears any cached user and group information\&. The list of other domains trusted by winbindd is also reloaded\&.
.RE
.PP
SIGUSR2
.RS 4
The SIGUSR2 signal will cause
winbindd
to write status information to the winbind log file\&.
.sp
Log files are stored in the filename specified by the log file parameter\&.
.RE
.SH "FILES"
.PP
/etc/nsswitch\&.conf(5)
.RS 4
Name service switch configuration file\&.
.RE
.PP
/tmp/\&.winbindd/pipe
.RS 4
The UNIX pipe over which clients communicate with the
winbindd
program\&. For security reasons, the winbind client will only attempt to connect to the winbindd daemon if both the
/tmp/\&.winbindd
directory and
/tmp/\&.winbindd/pipe
file are owned by root\&.
.RE
.PP
$LOCKDIR/winbindd_privileged/pipe
.RS 4
The UNIX pipe over which \*(Aqprivileged\*(Aq clients communicate with the
winbindd
program\&. For security reasons, access to some winbindd functions \- like those needed by the
ntlm_auth
utility \- is restricted\&. By default, only users in the \*(Aqroot\*(Aq group will get this access, however the administrator may change the group permissions on $LOCKDIR/winbindd_privileged to allow programs like \*(Aqsquid\*(Aq to use ntlm_auth\&. Note that the winbind client will only attempt to connect to the winbindd daemon if both the
$LOCKDIR/winbindd_privileged
directory and
$LOCKDIR/winbindd_privileged/pipe
file are owned by root\&.
.RE
.PP
/lib/libnss_winbind\&.so\&.X
.RS 4
Implementation of name service switch library\&.
.RE
.PP
$LOCKDIR/winbindd_idmap\&.tdb
.RS 4
Storage for the Windows NT rid to UNIX user/group id mapping\&. The lock directory is specified when Samba is initially compiled using the
\fI\-\-with\-lockdir\fR
option\&. This directory is by default
/usr/local/samba/var/locks\&.
.RE
.PP
$LOCKDIR/winbindd_cache\&.tdb
.RS 4
Storage for cached user and group information\&.
.RE
.SH "VERSION"
.PP
This man page is correct for version 3 of the Samba suite\&.
.SH "SEE ALSO"
.PP
nsswitch\&.conf(5),
\fBsamba\fR(7),
\fBwbinfo\fR(1),
\fBntlm_auth\fR(8),
\fBsmb.conf\fR(5),
\fBpam_winbind\fR(8)
.SH "AUTHOR"
.PP
The original Samba software and related utilities were created by Andrew Tridgell\&. Samba is now developed by the Samba Team as an Open Source project similar to the way the Linux kernel is developed\&.
.PP
wbinfo
and
winbindd
were written by Tim Potter\&.
.PP
The conversion to DocBook for Samba 2\&.2 was done by Gerald Carter\&. The conversion to DocBook XML 4\&.2 for Samba 3\&.0 was done by Alexander Bokovoy\&.
