.\" -*- tab-width: 4 -*-
.\" 
.\" Copyright (c) 2007 Apple Computer, Inc. All Rights Reserved.
.\" 
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\" 
.\"     http://www.apache.org/licenses/LICENSE-2.0
.\" 
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.\"
.\" $Log: mDNSResponderHelper.8,v $
.\" Revision 1.1  2007/08/08 22:34:59  mcguire
.\" <rdar://problem/5197869> Security: Run mDNSResponder as user id mdnsresponder instead of root
.\"
.\"
.\"
.Dd August 2007             \" Date
.Dt mDNSResponderHelper 8   \" Document Title
.Os Darwin                  \" Operating System
.\"
.Sh NAME
.Nm mDNSResponderHelper
.Nd mDNS privilege separation helper  \" Name Description for whatis database
.\" 
.Sh SYNOPSIS
.Nm
.\"
.Sh DESCRIPTION
.Nm
is an executable invoked by
.Nm launchd
to provide privilege separation
to the
.Nm mDNSResponder
daemon.
.Pp
.Nm
has no user-specifiable command-line arguments, and users should not run
.Nm
manually.
.Sh FILES
.Pa /usr/sbin/mDNSResponderHelper \" Pathname
.\"
.Sh SEE ALSO
.Xr mDNSResponder 8
.\"
.Sh BUGS
.Nm
bugs are tracked in Apple Radar component "mDNSResponder".
.\"
.Sh HISTORY
The
.Nm
first appeared in Mac OS X 10.5 (Leopard).
