.\" arch.1 -- 
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" Public domain: may be freely distributed.
.TH ARCH 1 "July 1997" "util-linux" "User Commands"
.SH NAME
arch \- print machine architecture
.SH SYNOPSIS
.B arch
.SH DESCRIPTION
.B arch
is a deprecated command since util-linux 2.13.  Use
.B "uname -m"
or use
.B arch
from the GNU coreutils package.

On current Linux systems,
.B arch
prints things such as "i386", "i486", "i586", "alpha", "sparc",
"arm", "m68k", "mips", "ppc".
.SH SEE ALSO
.BR uname (1),
.BR uname (2)
.SH AVAILABILITY
The arch command is part of the util-linux package and is available from
ftp://ftp.kernel.org/pub/linux/utils/util-linux/.
.\"
.\" Details:
.\" arch prints the machine part of the system_utsname struct
.\" This struct is defined in version.c, and this field is
.\" initialized with UTS_MACHINE, which is defined as $ARCH
.\" in the main Makefile.
.\" That gives the possibilities 
.\" alpha    arm      i386     m68k     mips     ppc      sparc    sparc64
.\"
.\" If Makefile is not edited, ARCH is guessed by
.\" ARCH := $(shell uname -m | sed -e s/i.86/i386/ -e s/sun4u/sparc64/)
.\" Then how come we get these i586 values?
.\" Well, the routine check_bugs() does system_utsname.machine[1] = '0' + x86;
.\" (called in init/main.c, defined in ./include/asm-i386/bugs.h)
