.\" Copyright 1992, 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH CTRLALTDEL 8 "October 1993" "util-linux" "System Administration"
.SH NAME
ctrlaltdel \- set the function of the Ctrl-Alt-Del combination
.SH SYNOPSIS
.BR "ctrlaltdel hard" | soft
.SH DESCRIPTION
Based on examination of the
.I linux/kernel/sys.c
code, it is clear that there are two supported functions that the
Ctrl-Alt-Del sequence can perform: a
.I hard
reset, which immediately reboots the computer without calling
.BR sync (2)
and without any other preparation; and a
.I soft
reset, which sends the SIGINT (interrupt) signal to the
.B init
process (this is always the process with PID 1).  If this option is used,
the
.BR init (8)
program must support this feature.  Since there are now several
.BR init (8)
programs in the Linux community, please consult the documentation for the
version that you are currently using.

.B ctrlaltdel
is usually used in the
.I /etc/rc.local
file.
.SH FILES
.I /etc/rc.local
.SH "SEE ALSO"
.BR simpleinit (8),
.BR init (8)
.SH AUTHOR
Peter Orbaek (poe@daimi.aau.dk)
.SH AVAILABILITY
The ctrlaltdel command is part of the util-linux package and is available from
ftp://ftp.kernel.org/pub/linux/utils/util-linux/.
