.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH IPCS "1" "September 2011" "util-linux" "User Commands"
.SH NAME
ipcs \- provide information on ipc facilities
.SH SYNOPSIS
.B ipcs
[resource] [...] [output\-format]
.br
.B ipcs
[resource]
.I \-i id
.SH DESCRIPTION
.B ipcs
provides information on the ipc facilities for which the calling process
has read access.
.SH OPTIONS
.TP
\fB\-i\fR, \fB\-\-id\fR \fIid\fR
Print details only on resource identified by
.IR id .
.TP
\fB\-h\fR, \fB\-\-help\fR
Display this help and exit.
.TP
\fB\-V\fR, \fB\-\-version\fR
Output version information and exit.
.SH "RESOURCE OPTIONS"
.TP
\fB\-m\fR, \fB\-\-shmems\fR
Write information about active shared memory segments.
.TP
\fB\-q\fR, \fB\-\-queues\fR
Write information about active message queues.
.TP
\fB\-s\fR, \fB\-\-semaphores\fR
Write information about active semaphore sets.
.TP
\fB\-a\fR, \fB\-\-all\fR
Write information about all resources (default).
.SH "OUTPUT FORMATS"
.TP
\fB\-t\fR, \fB\-\-time\fR
Write time information. Time of the last control operation that changed the
access permissions for all facilities, time of the last
.I msgsnd()
and
.I msgrcv()
operations on message queues, time of the last
.I shmat()
and
.I shmdt()
operations on shared memory, and time of the last
.I semop()
operation on semaphores.
.TP
\fB\-p\fR, \fB\-\-pid\fR
Show creator and last operations PIDs.
.TP
\fB\-c\fR, \fB\-\-creator\fR
Show creator and owner.
.TP
\fB\-l\fR, \fB\-\-limits\fR
Show resource limits.
.TP
\fB\-u\fR, \fB\-\-summary\fR
Show status summary.
.SH SEE ALSO
.BR ipcrm (1),
.BR ipcmk (1),
.BR msgrcv (2),
.BR msgsnd (2),
.BR semget (2),
.BR semop (2),
.BR shmat (2),
.BR shmdt (2),
.BR shmget (2)
.SH CONFORMING TO
The Linux ipcs utility is not fully compatible to the POSIX ipcs utility.
The Linux version does not support the
.B \-b
and
.B \-o
options, but does support the
.B \-l
and
.B \-u
options not defined by POSIX. The portable application shall not use the
.BR \-b ,
.BR \-o ,
.BR \-l ,
and
.B \-u
options.
.SH AUTHOR
.UR balasub@cis.ohio-state.edu
Krishna Balasubramanian
.UE
.SH AVAILABILITY
The ipcs command is part of the util-linux package and is available from
.UR ftp://\:ftp.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
