.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)renice.8   8.1 (Berkeley) 6/9/93
.\"
.TH RENICE "1" "September 2011" "util-linux" "User Commands"
.SH NAME
renice \- alter priority of running processes
.SH SYNOPSIS
.B renice
-n priority [options] <pid> [...]
.SH DESCRIPTION
.B Renice
alters the scheduling priority of one or more running processes.  The
following
.I who
parameters are interpreted as process ID's, process group ID's, or user
names.
.BR Renice 'ing
a process group causes all processes in the process group to have their
scheduling priority altered.
.BR Renice 'ing
a user causes all processes owned by the user to have their scheduling
priority altered.  By default, the processes to be affected are specified by
their process ID's.
.PP
.SH OPTIONS
.TP
\fB\-n\fR, \fB\-\-priority\fR \fIpriority\fR
The scheduling
.I priority
of the process, process group, or user.  Use of
.BR \-n " or " \-\-priority
can only exist as the first argument of
.B renice
command.
.TP
\fB\-g\fR, \fB\-\-pgrp\fR \fIpgid\fR
Force
.I who
parameters to be interpreted as \fIprocess group ID\fR's.
.TP
\fB\-u\fR, \fB\-\-user\fR \fIname\fR or \fIuid\fR
Force the
.I who
parameters to be interpreted as \fIuser name\fR or \fIid\fR.
.TP
\fB\-p\fR, \fB\-\-pid\fR \fIprocess id\fR
Resets the
.I who
interpretation to be (the default) \fIprocess ID\fR's.
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help.
.SH EXAMPLES
.TP
.B renice +1 987 -u daemon root -p 32
would change the priority of process ID's 987 and 32, and all processes owned
by users daemon and root.
.SH NOTES
Users other than the super-user may only alter the priority of processes they
own, and can only monotonically increase their ``nice value'' (for security
reasons) within the range 0 to
.BR PRIO_MAX \ (20),
unless a nice resource limit is set (Linux 2.6.12 and higher).  The
super-user may alter the priority of any process and set the priority to any
value in the range
.BR PRIO_MIN \ (\-20)
to
.BR PRIO_MAX .
Useful priorities are: 20 (the affected processes will run only when nothing
else in the system wants to), 0 (the ``base'' scheduling priority), anything
negative (to make things go very fast).
.SH FILES
.TP
.B /etc/passwd
to map user names to user ID's
.SH SEE ALSO
.BR getpriority (2),
.BR setpriority (2)
.SH BUGS
Non super-users can not increase scheduling priorities of their own processes,
even if they were the ones that decreased the priorities in the first place.
.PP
The Linux kernel (at least version 2.0.0) and linux libc (at least version
5.2.18) does not agree entirely on what the specifics of the systemcall
interface to set nice values is.  Thus causes renice to report bogus previous
nice values.
.SH HISTORY
The
.B renice
command appeared in 4.0BSD.
.SH AVAILABILITY
The renice command is part of the util-linux package and is available from
.UR ftp://\:ftp.kernel.org\:/pub\:/linux\:/utils\:/util-linux/
Linux Kernel Archive
.UE .
