.TH avahi-discover 1 User Manuals
.SH NAME
avahi-discover \- Browse for mDNS/DNS-SD services using the Avahi daemon
.SH SYNOPSIS
\fBavahi-discover
\f1
.SH DESCRIPTION
Show a real-time graphical browse list for mDNS/DNS-SD network services running on the local LAN using the Avahi daemon.
.SH OPTIONS
avahi-discover takes no command line arguments at the moment.
.SH AUTHORS
The Avahi Developers <avahi (at) lists (dot) freedesktop (dot) org>; Avahi is available from \fBhttp://avahi.org/\f1
.SH SEE ALSO
\fBavahi-daemon(8)\f1, \fBavahi-browse(1)\f1
.SH COMMENTS
This man page was written using \fBxml2man(1)\f1 by Oliver Kurth.
