.TH avahi.service 5 User Manuals
.SH NAME
avahi.service \- avahi-daemon static service file
.SH SYNOPSIS
\fB/home/lennart/tmp/avahi/etc/avahi/services/*.service
\f1
.SH DESCRIPTION
\fI/home/lennart/tmp/avahi/etc/avahi/services/*.service\f1 are XML fragments containing static DNS-SD service data. Every service file can contain multiple service definitions which share the same name. This is useful for publishing service data for services which implement multiple protocols. (i.e. a printer implementing _ipp._tcp and _printer._tcp)
.SH XML TAGS
.TP
\fB<service-group>\f1 The document tag of avahi service files. Should contain one \fB<name>\f1 and one or more \fB<service>\f1 elements.
.TP
\fB<name replace-wildcards="yes|no">\f1 The service name. If \fBreplace-wildcards\f1 is "yes", any occurence of the string "%h" will be replaced by the local host name. This can be used for service names like "Remote Terminal on %h". If \fBreplace-wildcards\f1 is not specified, defaults to "no".
.TP
\fB<service protocol="ipv4|ipv6|any">\f1 Contains the service information for exactly one service type. Should contain one \fB<type>\f1 and one \fB<port>\f1 element. Optionally it may contain one \fB<domain-name>\f1, one \fB<host-name>\f1, any number of \fB<subtype>\f1 and any number of \fB<txt-record>\f1 elements. The attribute \fBprotocol\f1 specifies the protocol to advertise the service on. If \fBany\f1 is used (which is the default), the service will be advertised on both IPv4 and IPv6.
.TP
\fB<type>\f1 Contains the DNS-SD service type for this service. e.g. "_http._tcp".
.TP
\fB<subtype>\f1 Contains an additional DNS-SD service subtype for this service. e.g. "_anon._sub._ftp._tcp".
.TP
\fB<domain-name>\f1 The domain name this service should be registered. If omited defaults to the default domain of the avahi daemon. (probably .local)
.TP
\fB<host-name>\f1 The host name of the host that provides this service. This should be a host that is resolvable by multicast or unicast DNS. Please note that you need to specify a fully-qualified domain name (FQDN) here, i.e. .local is not appended implicitly! The host name doesn't need to be part of the domain specified in \fB<domain-name>\f1. See \fBavahi.hosts(5)\f1 for more information how to publish additional host name mappings.
.TP
\fB<port>\f1 The IP port number the service listens on.
.TP
\fB<txt-record>\f1 DNS-SD TXT record data.
.SH AUTHORS
The Avahi Developers <avahi (at) lists (dot) freedesktop (dot) org>; Avahi is available from \fBhttp://avahi.org/\f1
.SH SEE ALSO
\fBavahi-daemon(8)\f1, \fBavahi.hosts(5)\f1
.SH COMMENTS
This man page was written using \fBxml2man(1)\f1 by Oliver Kurth.
