all:

install: all
	install -d $(INSTALLDIR)/bin
	install start_endpoint $(INSTALLDIR)/bin
	install endpoint $(INSTALLDIR)/bin
	install echr.msg $(INSTALLDIR)/bin
	install endpoint.ini $(INSTALLDIR)/bin

clean:
