/* Works over UDP */

[
	uuid("17fdd703-1827-4e34-79d4-24a55c53bb37"),
	version(1.0),
	pointer_default(unique),
	helpstring("Messaging Service")
] interface msgsvc
{
	[todo] void NetrMessageNameAdd();
	[todo] void NetrMessageNameEnum();
	[todo] void NetrMessageNameGetInfo();
	[todo] void NetrMessageNameDel();
}

[
	uuid("5a7b91f8-ff00-11d0-a9b2-00c04fb6e6fc"),
	version(1.0)
] interface msgsvcsend
{
	[todo] void NetrSendMessage();
}
