
#
# This is just a Makefile fragment -- it is included by the master
# makefile, cfe.mk
#
# This file should just append object file names to "ALLOBJS"
#

BSPOBJS +=  bcm91125c_init.o bcm91125c_devs.o
ALLOBJS +=  ui_bcm91125c.o 
