.TH RIPNGD 8 "25 November 2004" "Quagga RIPNG daemon" "Version 0.97.3"
.SH NAME
ripngd \- a RIPNG routing engine for use with Quagga routing software.
.SH SYNOPSIS
.B ripngd
[
.B \-dhlrv
] [
.B \-f
.I config-file
] [
.B \-i
.I pid-file
] [
.B \-P
.I port-number
] [
.B \-A
.I vty-address
] [
.B \-u
.I user
] [
.B \-g
.I group
]
.SH DESCRIPTION
.B ripngd
is a routing component that works with the
.B Quagga
routing engine.
.SH OPTIONS
Options available for the
.B ripngd
command:
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-daemon\fR
Runs in daemon mode, forking and exiting from tty.
.TP
\fB\-f\fR, \fB\-\-config-file \fR\fIconfig-file\fR 
Specifies the config file to use for startup. If not specified this
option will likely default to \fB\fI/usr/local/etc/ripngd.conf\fR.
.TP
\fB\-g\fR, \fB\-\-group \fR\fIgroup\fR
Specify the group to run as. Default is \fIquagga\fR.
.TP
\fB\-h\fR, \fB\-\-help\fR
A brief message.
.TP
\fB\-i\fR, \fB\-\-pid_file \fR\fIpid-file\fR
When ripngd starts its process identifier is written to
\fB\fIpid-file\fR.  The init system uses the recorded PID to stop or
restart ripngd.  The likely default is \fB\fI/var/run/ripngd.pid\fR.
.TP
\fB\-P\fR, \fB\-\-vty_port \fR\fIport-number\fR 
Specify the port that the ripngd VTY will listen on. This defaults to
2603, as specified in \fB\fI/etc/services\fR.
.TP
\fB\-A\fR, \fB\-\-vty_addr \fR\fIvty-address\fR
Specify the address that the ripngd VTY will listen on. Default is all
interfaces.
.TP
\fB\-u\fR, \fB\-\-user \fR\fIuser\fR
Specify the user to run as. Default is \fIquagga\fR.
.TP
\fB\-r\fR, \fB\-\-retain\fR 
When the program terminates, retain routes added by \fBripd\fR.
.TP
\fB\-v\fR, \fB\-\-version\fR
Print the version and exit.
.SH FILES
.TP
.BI /usr/local/sbin/ripngd
The default location of the 
.B ripngd
binary.
.TP
.BI /usr/local/etc/ripngd.conf
The default location of the 
.B ripngd
config file.
.TP
.BI $(PWD)/ripngd.log 
If the 
.B ripngd
process is config'd to output logs to a file, then you will find this
file in the directory where you started \fBripngd\fR.
.SH WARNING
This man page is intended to be a quick reference for command line
options. The definitive document is the Info file \fBQuagga\fR.
.SH DIAGNOSTICS
The ripngd process may log to standard output, to a VTY, to a log
file, or through syslog to the system logs. \fBripngd\fR supports many
debugging options, see the Info file, or the source for details.
.SH "SEE ALSO"
.BR bgpd (8),
.BR ripd (8),
.BR ospfd (8),
.BR ospf6d (8),
.BR isisd (8),
.BR zebra (8),
.BR vtysh (1)
.SH BUGS
.B ripngd
eats bugs for breakfast. If you have food for the maintainers try
.BI http://bugzilla.quagga.net
.SH AUTHORS
See
.BI http://www.zebra.org
and
.BI http://www.quagga.net
or the Info file for an accurate list of authors.

