
#define PJ_DEBUG 1
//#define PJ_SAFE_POOL 1

#define TURN_FLAG_USE_RESPECTIVE_TURN 1
#define TURN_FLAG_USE_UAC_TURN 2
#define TURN_FLAG_USE_TCP_TURN 4
#define PJ_GETHOSTIP_DISABLE_LOCAL_RESOLUTION 1

//#define PJ_CONFIG_IPHONE 1
#define MAX_SIP_SERVER_COUNT 8
#define MAX_STUN_SERVER_COUNT 8
#define MAX_TURN_SERVER_COUNT 8
#define NATNL_UDT_HEADER_SIZE 4  // Discarded, for tunnel type TCP use.
#define UDT_HEADER_SIZE 16       // Discarded, for tunnel type TCP use.
#define SCTP_HEADER_SIZE 28
#define NATNL_DTLS_HEADER_SIZE 13  // Discarded, for tunnel type TCP use.


#define NATNL_PKT_MAX_LEN 1300
#define NATNL_DTLS_MAX_RECV_LEN 4096 // For DTLS recv buffer.
#define NATNL_DTLS_MAX_SEND_LEN 4096 // For DTLS send buffer.

#define TCP_SESS_MSG_TYPE_INDEX 28  // Discarded, for tunnel type TCP use.

#define TCP_OR_UDP_TOTAL_HEADER_SIZE (NATNL_UDT_HEADER_SIZE+UDT_HEADER_SIZE+SESS_MGR_HEADER_SIZE)  // Discarded, for tunnel type TCP use.

// Session manager related
#define SESS_MGR_HEADER_SIZE 20
#define SESS_MGR_MSG_TYPE_INDEX 8

// No flow control related
#define NO_FLOW_CTL_SESS_MGR_HEADER_MAGIC 0XFFFEFDFC
#define NO_FLOW_CTL_SESS_MGR_HEADER_MAGIC_SIZE sizeof(NO_FLOW_CTL_SESS_MGR_HEADER_MAGIC)  //4
#define NO_FLOW_CTL_TOTAL_HEADER_SIZE (NO_FLOW_CTL_SESS_MGR_HEADER_MAGIC_SIZE+SESS_MGR_HEADER_SIZE)  //24
#define NO_FLOW_CTL_SESS_MSG_TYPE_INDEX (NO_FLOW_CTL_SESS_MGR_HEADER_MAGIC_SIZE+SESS_MGR_MSG_TYPE_INDEX)  //12
#define NO_FLOW_CTL_SESS_MSG_DISABLE_FLOW_CTL_INDEX 15

// UDT related
#define UDT_DATA_CHUNK_TOTAL_HEADER_SIZE (NATNL_UDT_HEADER_SIZE+UDT_HEADER_SIZE+SESS_MGR_HEADER_SIZE)  //40
#define UDT_DATA_CHUNK_TYPE_INDEX 0
#define UDT_SESS_MSG_TYPE_INDEX (NATNL_UDT_HEADER_SIZE+UDT_HEADER_SIZE+SESS_MGR_MSG_TYPE_INDEX)  //28

// SCTP related
#define SCTP_DATA_CHUNK_TOTAL_HEADER_SIZE (SCTP_HEADER_SIZE+SESS_MGR_HEADER_SIZE)  //48
#define SCTP_DATA_CHUNK_TYPE_INDEX 12
#define SCTP_SESS_MSG_TYPE_INDEX (SCTP_HEADER_SIZE+SESS_MGR_MSG_TYPE_INDEX)  //36

#define NATNL_UDT_HEADER_MAGIC 0x00FF  // Discarded, for tunnel type TCP use.

#define SDK_INIT_TIMEOUT_MSEC 30000
#define SIP_TCP_TIMEOUT_SEC 120

// DEAN determine to use udp's packet length threshold.
#define PJSIP_UDP_SIZE_THRESHOLD 0
#define PJSUA_REG_RETRY_INTERVAL 60

#if defined(WIN32)
#define PJSUA_MAX_INSTANCES	1026
#elif defined(PJ_ANDROID)
#define PJSUA_MAX_INSTANCES	64
#else
#define PJSUA_MAX_INSTANCES	4
#endif

#define PJ_LOG_MAX_LEVEL		 6

#ifndef MAX_USER_PORT_COUNT
#define MAX_USER_PORT_COUNT		15
#endif

#define PJMEDIA_HAS_SRTP		0

#define PJMEDIA_HAS_DTLS		1

#define PJMEDIA_ADVERTISE_RTCP	0

#define PJ_ICE_MAX_CAND			32
#define PJ_ICE_ST_MAX_CAND		16

#define PJ_ICE_MAX_CHECKS		1024
#define PJ_ICE_CANCEL_ALL		1
#define PJ_HAS_SSL_SOCK			1
#if PJ_CONFIG_IPHONE==1
#include <pj/config_site_sample.h>
//#define PJ_TCP_MAX_PKT_LEN	 	8192	
#define PJ_TCP_MAX_PKT_LEN	 	1460*64	
#define PJ_SOCKET_SND_BUFFER_SIZE		1460*8   //1460*64
//#define PJ_STUN_SOCK_PKT_LEN		8192
#define PJ_STUN_SOCK_PKT_LEN		1460*64
#define PJ_STUN_MAX_PKT_LEN		800
#define UDT_MAX_PKT_LEN			3000
//#define PJ_KEEP_BUFFER_SIZE	  	5*8192	
#define PJ_KEEP_BUFFER_SIZE		((1460*576) + (1460*2048) + (1460*576))
#else
#define PJ_TCP_MAX_PKT_LEN		1460*64 //1460*1024
#define PJ_SOCKET_SND_BUFFER_SIZE		1460*8   //1460*64
#define PJ_STUN_SOCK_PKT_LEN	1460*64 //1460*1024
#define PJ_STUN_MAX_PKT_LEN		1500
#define UDT_MAX_PKT_LEN			3000
#define PJ_KEEP_BUFFER_SIZE		((1460*1088) + (1460*2048) + (1460*1088))

#endif

// tunnel keep alive time in second
#define MAX_TNL_TIMEOUT_SEC			180
#define MAX_TCP_ACCEPT_SESS			8
#define MAX_TCP_CLIENT_SESS			16

// TURN refresh
#if 1
#define PJ_TURN_PERM_TIMEOUT		30
#define PJ_TURN_CHANNEL_TIMEOUT		60
#define PJ_TURN_REFRESH_SEC_BEFORE	570
#   define PJ_STUN_RTO_VALUE			    100
#endif

#   define PJ_ICE_UFRAG_LEN			    16
#   define PJ_ICE_PWD_LEN			    24
