mkinclude dynconfig/config.mk
mkinclude config.mk
mkinclude dsdb/config.mk
mkinclude smbd/config.mk
mkinclude cluster/config.mk
mkinclude smbd/process_model.mk
mkinclude libnet/config.mk
mkinclude auth/config.mk
mkinclude ../nsswitch/config.mk
mkinclude ../nsswitch/libwbclient/config.mk
mkinclude lib/samba3/config.mk
mkinclude lib/socket/config.mk
mkinclude ../lib/util/charset/config.mk
mkinclude lib/ldb-samba/config.mk
mkinclude lib/tls/config.mk
mkinclude lib/registry/config.mk
mkinclude lib/messaging/config.mk
mkinclude lib/events/config.mk
mkinclude lib/cmdline/config.mk
mkinclude ../lib/socket_wrapper/config.mk
mkinclude ../lib/nss_wrapper/config.mk
mkinclude ../lib/uid_wrapper/config.mk
mkinclude lib/stream/config.mk
mkinclude ../lib/util/config.mk
mkinclude ../lib/tdr/config.mk
mkinclude ../lib/tsocket/config.mk
mkinclude ../lib/crypto/config.mk
mkinclude ../lib/torture/config.mk
mkinclude lib/basic.mk
mkinclude lib/com/config.mk
# WMI fails at the moment
# mkinclude lib/wmi/config.mk
mkinclude param/config.mk
mkinclude smb_server/config.mk
mkinclude rpc_server/config.mk
mkinclude ldap_server/config.mk
mkinclude web_server/config.mk
mkinclude winbind/config.mk
mkinclude nbt_server/config.mk
mkinclude wrepl_server/config.mk
mkinclude cldap_server/config.mk
mkinclude ntp_signd/config.mk
mkinclude utils/net/config.mk
mkinclude utils/config.mk
mkinclude ntvfs/config.mk
mkinclude ntptr/config.mk
mkinclude torture/config.mk
mkinclude librpc/config.mk
mkinclude client/config.mk
mkinclude libcli/config.mk
mkinclude ../libcli/smb/config.mk
mkinclude ../libcli/cldap/config.mk
mkinclude scripting/python/config.mk
mkinclude kdc/config.mk
mkinclude ../lib/smbconf/config.mk
mkinclude ../lib/async_req/config.mk
mkinclude ../libcli/security/config.mk
mkinclude ../libcli/ldap/config.mk
mkinclude ../libcli/nbt/config.mk
mkinclude ../libcli/auth/config.mk
mkinclude ../libcli/drsuapi/config.mk
mkinclude ../libcli/samsync/config.mk
mkinclude ../libgpo/config.mk
mkinclude ../libcli/named_pipe_auth/config.mk
