# SHmedia testsuite.

if [istarget sh64-*-*] {
    # load support procs (none yet)
    # load_lib cgen.exp

    # all machines
    set all_machs "sh5"

    # The .cgs suffix is for "cgen .s".
    foreach src [lsort [glob -nocomplain $srcdir/$subdir/media/*.cgs]] {
       # If we're only testing specific files and this isn't one of them,
       # skip it.
       if ![runtest_file_p $runtests $src] {
  	  continue
	}
    run_sim_test $src $all_machs
    }
}
