name: Parse-Pidl
abstract: Generate parsers / DCE/RPC-clients from IDL
author:
    - Andrew Tridgell <tridge@samba.org>
    - Jelmer Vernooij <jelmer@samba.org>
    - Stefan Metzmacher <metze@samba.org>
    - Tim Potter <tpot@samba.org>
license: gplv3
installdirs:  site
homepage: http://www.samba.org/
bugtracker: http://bugzilla.samba.org/
requires:
    Parse::Yapp: 0    
recommends:
    Data::Dumper: 0
meta-spec:
    version: 1.3
    url: http://module-build.sourceforge.net/META-spec-v1.3.html
