.TH PPPGETPASS 8 "26 Sep 1999"
.SH NAME
pppgetpass \- prompt for PAP password
.SH SYNOPSIS
.B pppgetpass
.I client server fd
.SH DESCRIPTION
.B pppgetpass
the outer half of a plugin for PAP password prompting in pppd.
If the peer requires PAP, and the
.B passprompt.so
plugin is loaded into pppd, it will run
.B /usr/sbin/pppgetpass
(or another program specified by the
.B promptprog
option) to prompt the user for the password.
.SH SEE ALSO
pppd(8)
