#!/usr/bin/env python

bld.SAMBA_LIBRARY('policy',
	source='gp_ldap.c gp_filesys.c gp_manage.c gp_ini.c',
	pc_files='policy.pc',
	public_deps='ldb samba-net',
	vnum='0.0.1',
	pyembed=True
	)

bld.SAMBA_PYTHON('py_policy',
	source='pypolicy.c',
	public_deps='policy pytalloc-util',
	realname='samba/policy.so'
	)
