.TH UDHCPD.CONF 5 2001-09-26 GNU/Linux "GNU/Linux Administrator's Manual"
.SH NAME
udhcpd.conf \- udhcp server configuration file
.SH DESCRIPTION
The file
.I /etc/udhcpd.conf
contains configuration information specific to the udhcp server.
It should contain one configuration keyword per line, followed by
appropriate configuration information.
.SH OPTIONS
.TP
.BI start\  ADDRESS
The starting address of the IP lease block is
.IR ADDRESS .
The default is
.BR 192.168.0.20 .
.TP
.BI end\  ADDRESS
The ending address of the IP lease block is
.IR ADDRESS .
The default is
.BR 192.168.0.254 .
.TP
.BI interface\  INTERFACE
The udhcp server should listen on
.IR INTERFACE .
The default is
.BR eth0 .
.TP
.BI max_leases\  LEASES
Offer at most
.I LEASES
leases (including those reserved by OFFERs, DECLINEs, and ARP
conflicts).  The default is
.BR 254 .
.TP 
.BI remaining\  REMAINING
If
.I REMAINING
is
.BR yes ,
store the time remaining for each lease.  If it is
.BR no ,
store the expiration time for each lease.  The default is
.BR yes .
.TP
.BI auto_time\  SECONDS
Write the lease information to a file every
.I SECONDS
seconds.  The default is
.BR 7200 .
.TP
.BI decline_time\  SECONDS
Reserve an IP for
.I SECONDS
seconds if a DHCP decline message is received.  The default is
.BR 3600 .
.TP
.BI conflict_time\  SECONDS
Reserve an IP for
.I SECONDS
seconds if an ARP conflict occurs.  The default is
.BR 3600 .
.TP
.BI offer_time\  SECONDS
Reserve an IP for
.I SECONDS
seconds if it is offered.  The default is
.BR 60 .
.TP
.BI min_lease\  SECONDS
Reserve an IP for the full lease time if the lease to be given is less than
.I SECONDS
seconds.  The default is
.BR 60 .
.TP
.BI lease_file\  FILE
Write the lease information to
.IR FILE .
The default is
.BR /var/lib/misc/udhcpd.leases .
.TP
.BI pidfile\  FILE
Write the process ID to
.IR FILE .
The default is
.BR /var/run/udhcpd.pid .
.TP
.BI notify_file\  FILE
Execute
.I FILE
after the lease information is written.  By default, no file is executed.
.TP
.BI siaddr\  ADDRESS
BOOTP specific option.  The default is
.BR 0.0.0.0 .
.TP
.BI sname\  NAME
BOOTP specific option.  There is no default.
.TP
.BI boot_file\  FILE
BOOTP specific option.  There is no default.
.TP
.BI option\  OPTION
DHCP specific option.
.RS
.TP
.BI subnet\  ADDRESS
.TP
.BI timezone\  OFFSET
.TP
.BI router\  ADDRESS...
.TP
.BI timesvr\  ADDRESS...
.TP
.BI namesvr\  ADDRESS...
.TP
.BI dns\  ADDRESS...
.TP
.BI logsvr\  ADDRESS...
.TP
.BI cookiesvr\  ADDRESS...
.TP
.BI lprsvr\  ADDRESS...
.TP
.BI hostname\  HOSTNAME
.TP
.BI bootsize\  SIZE
.TP
.BI domain\  DOMAIN
.TP
.BI swapsvr\  ADDRESS
.TP
.BI rootpath\  PATH
.TP
.BI ipttl\  TTL
.TP
.BI mtu\  MTU
.TP
.BI broadcast\  ADDRESS
.TP
.BI ntpsrv\  ADDRESS...
.TP
.BI wins\  ADDRESS...
.TP
.BI requestip\  ADDRESS
.TP
.BI lease\  SECONDS
.TP
.BI dhcptype\  TYPE
.TP
.BI serverid\  ADDRESS
.TP
.BI tftp\  FILE
.TP
.BI bootfile\  FILE
The default for
.B lease
is
.BR 864000 .
There are no defaults for the other options.
.RE
.SH SEE ALSO
.BR udhcpd (8).
