.\" Copyright 1992, 1993, 1994 Rickard E. Faith (faith@cs.unc.edu)
.\" May be freely distributed.
.\" " for hilit19
.TH FSCK 8 "July 1996" "util-linux" "System Administration"
.SH NAME
fsck.minix \- check consistency of Minix filesystem
.SH SYNOPSIS
.B fsck.minix
.RB [ \-larvsmf ]
.I device
.SH DESCRIPTION
.B fsck.minix
performs a consistency check for the Linux MINIX filesystem.  The current
version supports the 14 character and 30 character filename options.

The program
assumes the filesystem is quiescent.
.B fsck.minix
should not be used on a mounted device unless you can be sure nobody is
writing to it (and remember that the kernel can write to it when it
searches for files).

The \fIdevice\fR name will usually have the following form:
.nf
.RS
/dev/hda[1-63] (IDE disk 1)
/dev/hdb[1-63] (IDE disk 2)
/dev/sda[1-15] (SCSI disk 1)
/dev/sdb[1-15] (SCSI disk 2)
.RE
.fi

If the filesystem was changed (i.e., repaired), then
.B fsck.minix
will print "FILE SYSTEM HAS CHANGED" and will
.BR sync (2)
three times before exiting.  Since Linux does not currently have raw
devices, there is
.I no
need to reboot at this time.
.SH WARNING
.B fsck.minix
should
.B not
be used on a mounted filesystem.  Using
.B fsck.minix
on a mounted filesystem is very dangerous, due to the possibility that
deleted files are still in use, and can seriously damage a perfectly good
filesystem!  If you absolutely have to run
.B fsck.minix
on a mounted filesystem (i.e., the root filesystem), make sure nothing is
writing to the disk, and that no files are "zombies" waiting for deletion.
.SH OPTIONS
.TP
.B \-l
List all filenames.
.TP
.B \-r
Perform interactive repairs.
.TP
.B \-a
Perform automatic repairs.  (This option implies
.B \-r
and serves to answer all of the questions asked with the default.)  Note
that this can be extremely dangerous in the case of extensive filesystem
damage.
.TP
.B \-v
Be verbose.
.TP
.B \-s
Output super-block information.
.TP
.B \-m
Activate MINIX-like "mode not cleared" warnings.
.TP
.B \-f
Force a filesystem check even if the filesystem was marked as valid (this
marking is done by the kernel when the filesystem is unmounted).
.SH "SEE ALSO"
.BR fsck (8),
.BR fsck.ext (8),
.BR fsck.ext2 (8),
.BR fsck.xiafs (8),
.BR mkfs (8),
.BR mkfs.minix (8),
.BR mkfs.ext (8),
.BR mkfs.ext2 (8),
.BR mkfs.xiafs (8),
.BR reboot (8)
.SH DIAGNOSTICS
There are numerous diagnostic messages.  The ones mentioned here are the
most commonly seen in normal usage.

If the device does not exist,
.B fsck.minix
will print "unable to read super block".  If the device exists, but is not
a MINIX filesystem,
.B fsck.minix
will print "bad magic number in super-block".
.SH "EXIT CODES"
The exit code returned by
.B fsck.minix
is the sum of the following:
.IP 0
No errors
.IP 3
Filesystem errors corrected, system should be rebooted if filesystem was
mounted
.IP 4
Filesystem errors left uncorrected
.IP 8
Operational error
.IP 16
Usage or syntax error
.PP
In point of fact, only 0, 3, 4, 7, 8, and 16 can ever be returned.
.SH AUTHOR
Linus Torvalds (torvalds@cs.helsinki.fi)
.br
Error code values by Rik Faith (faith@cs.unc.edu)
.br
Added support for filesystem valid flag: Dr. Wettstein
(greg%wind.uucp@plains.nodak.edu)
.br
Check to prevent fsck of mounted filesystem added by Daniel Quinlan
(quinlan@yggdrasil.com)
.br
Minix v2 fs support by Andreas Schwab
(schwab@issan.informatik.uni-dortmund.de), updated by Nicolai
Langfeldt (janl@math.uio.no)
.br
Portability patch by Russell King (rmk@ecs.soton.ac.uk).
.SH AVAILABILITY
The fsck.minix command is part of the util-linux package and is available from
ftp://ftp.kernel.org/pub/linux/utils/util-linux/.
