.\" Copyright 2010 Jason Borden <jborden@bluehost.com>
.\"
.\" This file may be copied under the terms of the GNU Public License.
.\"
.TH SWAPLABEL 8 "April 2010" "util-linux" "System Administration"
.SH NAME
swaplabel \- print or change the label or UUID of a swap area
.SH SYNOPSIS
.B swaplabel
.RB [ \-L
.IR label ]
.RB [ \-U
.IR UUID ]
.I device
.SH DESCRIPTION
.B swaplabel
will display or change the label or UUID of a swap partition located on
.IR device 
(or regular file).
.PP
If the optional arguments
.B \-L 
and
.B \-U 
are not given,
.B swaplabel
will simply display the current swap-area label and UUID of
.IR device .
.PP
If an optional argument is present, then
.B swaplabel
will change the appropriate value on
.IR device .
These values can also be set during swap creation using
.BR mkswap (8).
The
.B swaplabel
utility allows to change the label or UUID on an actively used swap device.
.SH OPTIONS
.TP
.BR \-h , " \-\-help"
Display help text and exit.
.TP
.BR \-L , " \-\-label " \fIlabel\fR
Specify a new \fIlabel\fR for the device.
Swap partition labels can be at most 16 characters long.  If
.I label
is longer than 16 characters,
.B swaplabel
will truncate it and print a warning message.
.TP
.BR \-U , " \-\-uuid " \fIUUID\fR
Specify a new \fIUUID\fR for the device.
The \fI UUID\fR
must be in the standard 8-4-4-4-12 character format, such as is output by
.BR uuidgen (1) .
.PP
.SH AUTHOR
.B swaplabel
was written by Jason Borden <jborden@bluehost.com> and Karel Zak <kzak@redhat.com>.
.SH AVAILABILITY
The swaplabel command is part of the util-linux package and is available from
ftp://ftp.kernel.org/pub/linux/utils/util-linux/.
.SH SEE ALSO
.BR mkswap (8),
.BR swapon (8),
.BR uuidgen (1)
