.TH VTYSH 1 "July 2000" "Zebra Beast - VTY shell" "Version 0.88"

.SH NAME
vtysh \- a integrated shell for Zebra routing software

.SH SYNOPSIS
.B vtysh
[
.B \-e command
]

.SH DESCBGPTION
.B vtysh
is a integrated shell for
.B Zebra
routing engine.


.SH OPTIONS

.TP
\fB\-e
Specify command to be executed under batch mode.


.SH COMMANDS

\fB Almost Zebra commands.

\fB ping
\fB traceroute
\fB telnnet

\fB start-shell
\fB start-shell bash
\fB start-shell zsh


.SH FILES

.TP
.BI /usr/local/etc/Zebra.conf
The default location of the 
.B vtysh
config file.


.SH WARNING
This man page is intended as a quick reference for command line
options, and for config file commands. The definitive document is the
Info file \fBZebra\fR.


.SH "SEE ALSO"
References to other related man pages:

bgpd(8), ripd(8), ripngd(8), ospfd(8), ospf6d(8), zebra(8)


.SH BUGS
.B vtysh
eats bugs for breakfast. If you have food for the maintainers try 
.BI <bug-zebra@gnu.org>


.SH AUTHOR[S]
See <\fBwww.zebra.org\fR>, or the Info file for an accurate list of authors.

