@node VTY shell
@comment  node-name,  next,  previous,  up
@chapter VTY shell

@command{vtysh} is integrated shell of Zebra software.

To use vtysh please specify ---enable-vtysh to configure script.  To use
PAM for authentication use ---with-libpam option to configure script.

vtysh only searches @value{INSTALL_PREFIX_ETC} path for vtysh.conf which
is the vtysh configuration file.  Vtysh does not search current
directory for configuration file because the file includes user
authentication settings.

Currently, vtysh.conf has only one command.

@example
!
username foo nopassword
!
@end example

With this set, user foo does not need password authentication for user vtysh.
With PAM vtysh uses PAM authentication mechanism.

If vtysh is compiled without PAM authentication, every user can use vtysh
without authentication.
