#!/bin/sh

. ../support/simple_eval_tools.sh

SKIPIFNOT NETSNMP_SECMOD_USM

DEFSECURITYLEVEL=authNoPriv

HEADER "SNMPv3 informs (authNoPriv) received and sent by tools"

#
# Begin test
#

. ./Sv3usmconfigtrapd
CONFIGTRAPD authuser log $TESTAUTHUSER $DEFSECURITYLEVEL
CONFIGTRAPD agentxsocket /dev/null

STARTTRAPD

CAPTURE "snmptrap -Ci -t $SNMP_SLEEP -d $TESTAUTHARGS $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPTRAPD_PORT 0 .1.3.6.1.6.3.1.1.5.1 .1.3.6.1.2.1.1.4.0 s received_inform_$DEFSECURITYLEVEL"

STOPTRAPD

CHECKTRAPD "received_inform_$DEFSECURITYLEVEL"

FINISHED
