[SUBSYSTEM::LIBCLI_CLDAP]
PUBLIC_DEPENDENCIES = LIBCLI_LDAP
PRIVATE_DEPENDENCIES = LIBTSOCKET LIBSAMBA-UTIL UTIL_TEVENT LIBLDB LIBCLI_NETLOGON

LIBCLI_CLDAP_OBJ_FILES = ../libcli/cldap/cldap.o
# PUBLIC_HEADERS += ../libcli/cldap/cldap.h

