#define UTS_VERSION "#1 2010-09-09 12:44:17 EDT"
#define LINUX_COMPILE_TIME "12:44:17"
#define LINUX_COMPILE_BY "root"
#define LINUX_COMPILE_HOST "tomato"
#define LINUX_COMPILE_DOMAIN "localdomain"
#define LINUX_COMPILER "gcc version 3.4.6"
