# Russian messages for international release of SWAT.
# Copyright (C) 2007 Yuri Kozlov <kozlov.y@gmail.com>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, see <http://www.gnu.org/licenses/>.
#
msgid ""
msgstr ""
"Project-Id-Version: swat\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2007-06-04 18:15+0200\n"
"PO-Revision-Date: 2007-06-27 22:00+0400\n"
"Last-Translator: Yuri Kozlov <kozlov.y@gmail.com>\n"
"Language-Team: Russian <debian-l10n-russian@lists.debian.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: KBabel 1.11.4\n"
"Plural-Forms:  nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"

#: ../web/swat.c:139
#, c-format
msgid "ERROR: Can't open %s"
msgstr "ОШИБКА: Не удалось открыть %s"

#: ../web/swat.c:223
msgid "Help"
msgstr "Справка"

#: ../web/swat.c:229 ../web/swat.c:254 ../web/swat.c:275 ../web/swat.c:285 ../web/swat.c:294 ../web/swat.c:303 ../web/swat.c:309 ../web/swat.c:315 ../web/swat.c:328
msgid "Set Default"
msgstr "Установить по умолчанию"

#: ../web/swat.c:450
#, c-format
msgid "failed to open %s for writing"
msgstr "не удалось открыть %s для записи"

#: ../web/swat.c:473
#, c-format
msgid "Can't reload %s"
msgstr "Невозможно перезагрузить %s"

#: ../web/swat.c:543
#, c-format
msgid "Logged in as <b>%s</b>"
msgstr "Осуществлён вход под именем <b>%s</b>"

#: ../web/swat.c:547
msgid "Home"
msgstr "Главная"

#: ../web/swat.c:549
msgid "Globals"
msgstr "Глобальные"

#: ../web/swat.c:550
msgid "Shares"
msgstr "Ресурсы"

#: ../web/swat.c:551
msgid "Printers"
msgstr "Принтеры"

#: ../web/swat.c:552
msgid "Wizard"
msgstr "Помощник"

#: ../web/swat.c:556
msgid "Status"
msgstr "Состояние"

#: ../web/swat.c:557
msgid "View Config"
msgstr "Настройки"

#: ../web/swat.c:559
msgid "Password Management"
msgstr "Пароли"

#: ../web/swat.c:569
msgid "Current View Is"
msgstr "Текущий вид"

#: ../web/swat.c:570 ../web/swat.c:573
msgid "Basic"
msgstr "Простой"

#: ../web/swat.c:571 ../web/swat.c:574
msgid "Advanced"
msgstr "Сложный"

#: ../web/swat.c:572
msgid "Change View To"
msgstr "Сменить вид на"

#: ../web/swat.c:601
msgid "Current Config"
msgstr "Текущий файл конфигурации"

#: ../web/swat.c:605
msgid "Normal View"
msgstr "Обычный вид"

#: ../web/swat.c:607
msgid "Full View"
msgstr "Полный вид"

#. Here we first set and commit all the parameters that were selected
#. in the previous screen.
#: ../web/swat.c:626
msgid "Wizard Parameter Edit Page"
msgstr "Страница редактирования параметров помощника"

#: ../web/swat.c:655
msgid "Note: smb.conf file has been read and rewritten"
msgstr "Замечание: файл smb.conf был прочитан и перезаписан"

#. Here we go ...
#: ../web/swat.c:763
msgid "Samba Configuration Wizard"
msgstr "Помощник настройки Samba"

#: ../web/swat.c:767
msgid "The \"Rewrite smb.conf file\" button will clear the smb.conf file of all default values and of comments."
msgstr ""
"По кнопке \"Перезаписать файл smb.conf\" в файл smb.conf записываются все "
"значения по умолчанию с комментариями."

#: ../web/swat.c:768
msgid "The same will happen if you press the commit button."
msgstr "То же самое произойдёт при нажатии кнопки сохранения."

#: ../web/swat.c:771
msgid "Rewrite smb.conf file"
msgstr "Перезаписать файл smb.conf"

#: ../web/swat.c:772
msgid "Commit"
msgstr "Сохранить"

#: ../web/swat.c:773
msgid "Edit Parameter Values"
msgstr "Редактировать значения параметров"

#: ../web/swat.c:779
msgid "Server Type"
msgstr "Тип сервера"

#: ../web/swat.c:780
msgid "Stand Alone"
msgstr "Независимый"

#: ../web/swat.c:781
msgid "Domain Member"
msgstr "Член домена"

#: ../web/swat.c:782
msgid "Domain Controller"
msgstr "Контроллер домена"

#: ../web/swat.c:785
msgid "Unusual Type in smb.conf - Please Select New Mode"
msgstr "Необычный тип в smb.conf - Выберите новый режим"

#: ../web/swat.c:787
msgid "Configure WINS As"
msgstr "Настроить WINS как"

#: ../web/swat.c:788
msgid "Not Used"
msgstr "Не использовать"

#: ../web/swat.c:789
msgid "Server for client use"
msgstr "Сервер для клиентов"

#: ../web/swat.c:790
msgid "Client of another WINS server"
msgstr "Клиент другого сервера WINS"

#: ../web/swat.c:792
msgid "Remote WINS Server"
msgstr "Удалённый сервер WINS"

#: ../web/swat.c:803
msgid "Error: WINS Server Mode and WINS Support both set in smb.conf"
msgstr "Ошибка: в smb.conf установлены одновременно режим сервера WINS и поддержка WINS"

#: ../web/swat.c:804
msgid "Please Select desired WINS mode above."
msgstr "Выберите желаемый режим WINS."

#: ../web/swat.c:806
msgid "Expose Home Directories"
msgstr "Сделать доступными домашние каталоги"

#: ../web/swat.c:821
msgid "The above configuration options will set multiple parameters and will generally assist with rapid Samba deployment."
msgstr ""
"Выбор параметров выше приводит к автоматической настройке большего числа "
"параметров, и помогает в сокращении времени развёртывания Samba."

#: ../web/swat.c:834
msgid "Global Parameters"
msgstr "Глобальные параметры"

#: ../web/swat.c:862 ../web/swat.c:966 ../web/swat.c:1318
msgid "Commit Changes"
msgstr "Сохранить изменения"

#: ../web/swat.c:866 ../web/swat.c:969 ../web/swat.c:1320
msgid "Reset Values"
msgstr "Реинициализировать значения"

#: ../web/swat.c:891
msgid "Share Parameters"
msgstr "Параметры общих ресурсов"

#: ../web/swat.c:934
msgid "Choose Share"
msgstr "Выбрать ресурс"

#: ../web/swat.c:951
msgid "Delete Share"
msgstr "Удалить ресурс"

#: ../web/swat.c:958
msgid "Create Share"
msgstr "Создать ресурс"

#: ../web/swat.c:994
msgid "password change in demo mode rejected"
msgstr "смена пароля в демо-режиме не работает"

#: ../web/swat.c:1007
msgid "Can't setup password database vectors."
msgstr "Не удалось настроить векторы базы данных паролей."

#: ../web/swat.c:1033
msgid " Must specify \"User Name\" "
msgstr " Должно быть указано \"Имя пользователя\" "

#: ../web/swat.c:1049
msgid " Must specify \"Old Password\" "
msgstr " Должен быть указан \"Старый пароль\" "

#: ../web/swat.c:1055
msgid " Must specify \"Remote Machine\" "
msgstr " Должна быть указана \"Удалённая машина\" "

#: ../web/swat.c:1062
msgid " Must specify \"New, and Re-typed Passwords\" "
msgstr "  Должен быть указан \"Новый пароль, введённый дважды\" "

#: ../web/swat.c:1068
msgid " Re-typed password didn't match new password "
msgstr " Повторно набранный новый пароль не совпадает с новым паролем "

#: ../web/swat.c:1101
#, c-format
msgid " The passwd for '%s' has been changed."
msgstr " Был изменён пароль для '%s'."

#: ../web/swat.c:1104
#, c-format
msgid " The passwd for '%s' has NOT been changed."
msgstr " Пароль для '%s' НЕ был изменён."

#: ../web/swat.c:1129
msgid "Server Password Management"
msgstr "Управление паролями сервера"

#.
#. * Create all the dialog boxes for data collection
#.
#: ../web/swat.c:1138 ../web/swat.c:1185
msgid "User Name"
msgstr "Имя пользователя"

#: ../web/swat.c:1141 ../web/swat.c:1187
msgid "Old Password"
msgstr "Старый пароль"

#: ../web/swat.c:1144 ../web/swat.c:1189
msgid "New Password"
msgstr "Новый пароль"

#: ../web/swat.c:1146 ../web/swat.c:1191
msgid "Re-type New Password"
msgstr "Новый пароль ещё раз"

#: ../web/swat.c:1154 ../web/swat.c:1202
msgid "Change Password"
msgstr "Сменить пароль"

#: ../web/swat.c:1157
msgid "Add New User"
msgstr "Добавить нового пользователя"

#: ../web/swat.c:1159
msgid "Delete User"
msgstr "Удалить пользователя"

#: ../web/swat.c:1161
msgid "Disable User"
msgstr "Заблокировать пользователя"

#: ../web/swat.c:1163
msgid "Enable User"
msgstr "Разблокировать пользователя"

#: ../web/swat.c:1176
msgid "Client/Server Password Management"
msgstr "Управление паролями в режиме клиент/сервер"

#: ../web/swat.c:1193
msgid "Remote Machine"
msgstr "Удалённая машина"

#: ../web/swat.c:1232
msgid "Printer Parameters"
msgstr "Параметры принтера"

#: ../web/swat.c:1234
msgid "Important Note:"
msgstr "Важное замечание:"

#: ../web/swat.c:1235
#, c-format
msgid "Printer names marked with [*] in the Choose Printer drop-down box "
msgstr "Имена принтеров, помеченные [*] в выпадающем списке принтеров, "

#: ../web/swat.c:1236
#, c-format
msgid "are autoloaded printers from "
msgstr "были автоматически загружены согласно параметру "

#: ../web/swat.c:1237
msgid "Printcap Name"
msgstr "Printcap Name"

#: ../web/swat.c:1238
msgid "Attempting to delete these printers from SWAT will have no effect."
msgstr ". Попытка удалить эти принтеры из SWAT ни к чему не приведёт."

#: ../web/swat.c:1284
msgid "Choose Printer"
msgstr "Выбрать принтер"

#: ../web/swat.c:1303
msgid "Delete Printer"
msgstr "Удалить принтер"

#: ../web/swat.c:1310
msgid "Create Printer"
msgstr "Создать принтер"

#: ../web/statuspage.c:139
msgid "RDWR       "
msgstr "RDWR       "

#: ../web/statuspage.c:141
msgid "WRONLY     "
msgstr "WRONLY     "

#: ../web/statuspage.c:143
msgid "RDONLY     "
msgstr "RDONLY     "

#: ../web/statuspage.c:330
msgid "Server Status"
msgstr "Состояние сервера"

#: ../web/statuspage.c:335
msgid "Auto Refresh"
msgstr "Включить автообновление"

#: ../web/statuspage.c:336 ../web/statuspage.c:341
msgid "Refresh Interval: "
msgstr "Интервал автообновления: "

#: ../web/statuspage.c:340
msgid "Stop Refreshing"
msgstr "Выключить автообновление"

#: ../web/statuspage.c:355
msgid "version:"
msgstr "версия:"

#: ../web/statuspage.c:358
msgid "smbd:"
msgstr "smbd:"

#: ../web/statuspage.c:358 ../web/statuspage.c:371 ../web/statuspage.c:385
msgid "running"
msgstr "работает"

#: ../web/statuspage.c:358 ../web/statuspage.c:371 ../web/statuspage.c:385
msgid "not running"
msgstr "не работает"

#: ../web/statuspage.c:362
msgid "Stop smbd"
msgstr "Остановить smbd"

#: ../web/statuspage.c:364
msgid "Start smbd"
msgstr "Запустить smbd"

#: ../web/statuspage.c:366
msgid "Restart smbd"
msgstr "Перезапустить smbd"

#: ../web/statuspage.c:371
msgid "nmbd:"
msgstr "nmbd:"

#: ../web/statuspage.c:375
msgid "Stop nmbd"
msgstr "Остановить nmbd"

#: ../web/statuspage.c:377
msgid "Start nmbd"
msgstr "Запустить nmbd"

#: ../web/statuspage.c:379
msgid "Restart nmbd"
msgstr "Перезапустить nmbd"

#: ../web/statuspage.c:385
msgid "winbindd:"
msgstr "winbindd:"

#: ../web/statuspage.c:389
msgid "Stop winbindd"
msgstr "Остановить winbindd"

#: ../web/statuspage.c:391
msgid "Start winbindd"
msgstr "Запустить winbindd"

#: ../web/statuspage.c:393
msgid "Restart winbindd"
msgstr "Перезапустить winbindd"

#. stop, restart all
#: ../web/statuspage.c:402
msgid "Stop All"
msgstr "Остановить всё"

#: ../web/statuspage.c:403
msgid "Restart All"
msgstr "Перезапустить всё"

#. start all
#: ../web/statuspage.c:407
msgid "Start All"
msgstr "Запустить всё"

#: ../web/statuspage.c:414
msgid "Active Connections"
msgstr "Активные подключения"

#: ../web/statuspage.c:416 ../web/statuspage.c:429 ../web/statuspage.c:437
msgid "PID"
msgstr "PID"

#: ../web/statuspage.c:416 ../web/statuspage.c:429
msgid "Client"
msgstr "Клиент"

#: ../web/statuspage.c:416
msgid "IP address"
msgstr "IP-адрес"

#: ../web/statuspage.c:416 ../web/statuspage.c:429 ../web/statuspage.c:437
msgid "Date"
msgstr "Дата"

#: ../web/statuspage.c:418
msgid "Kill"
msgstr "Отключить"

#: ../web/statuspage.c:426
msgid "Active Shares"
msgstr "Активные ресурсы"

#: ../web/statuspage.c:429
msgid "Share"
msgstr "Ресурс"

#: ../web/statuspage.c:429
msgid "User"
msgstr "Пользователь"

#: ../web/statuspage.c:429
msgid "Group"
msgstr "Группа"

#: ../web/statuspage.c:435
msgid "Open Files"
msgstr "Открытые файлы"

#: ../web/statuspage.c:437
msgid "Sharing"
msgstr "Ресурс"

#: ../web/statuspage.c:437
msgid "R/W"
msgstr "R/W"

#: ../web/statuspage.c:437
msgid "Oplock"
msgstr "Oplock"

#: ../web/statuspage.c:437
msgid "File"
msgstr "Файл"

#: ../web/statuspage.c:446
msgid "Show Client in col 1"
msgstr "Показать клиента в колонке 1"

#: ../web/statuspage.c:447
msgid "Show PID in col 1"
msgstr "Показать PID в колонке 1"

#: ../param/loadparm.c:836
msgid "Base Options"
msgstr "Основные параметры"

#: ../param/loadparm.c:855
msgid "Security Options"
msgstr "Параметры безопасности"

#: ../param/loadparm.c:945
msgid "Logging Options"
msgstr "Параметры журнала"

#: ../param/loadparm.c:962
msgid "Protocol Options"
msgstr "Параметры протокола"

#: ../param/loadparm.c:1008
msgid "Tuning Options"
msgstr "Параметры детальной настройки"

#: ../param/loadparm.c:1037
msgid "Printing Options"
msgstr "Параметры печати"

#: ../param/loadparm.c:1075
msgid "Filename Handling"
msgstr "Обработка имён файлов"

#: ../param/loadparm.c:1105
msgid "Domain Options"
msgstr "Параметры домена"

#: ../param/loadparm.c:1109
msgid "Logon Options"
msgstr "Параметры входа"

#: ../param/loadparm.c:1130
msgid "Browse Options"
msgstr "Параметры обзора"

#: ../param/loadparm.c:1144
msgid "WINS Options"
msgstr "Параметры WINS"

#: ../param/loadparm.c:1153
msgid "Locking Options"
msgstr "Параметры блокировки"

#: ../param/loadparm.c:1170
msgid "Ldap Options"
msgstr "Параметры Ldap"

#: ../param/loadparm.c:1186
msgid "Miscellaneous Options"
msgstr "Различные параметры"

#: ../param/loadparm.c:1191
msgid "EventLog Options"
msgstr "Параметры EventLog"

#: ../param/loadparm.c:1258
msgid "VFS module options"
msgstr "Параметры модуля VFS"

#: ../param/loadparm.c:1268
msgid "Winbind options"
msgstr "Параметры Winbind"

