#
# @(#) Test maximum number of clients (file descriptors) for winbindd
#

load_lib util-defs.exp

# Unimplemented - eek!

untested "bigfd"
return

# Compile bigfd.c

set output [target_compile "$srcdir/$subdir/bigfd.c" \
        "$srcdir/$subdir/bigfd" executable {additional_flags="-g"}]

if {$output != ""} {
    perror "compile bigfd"
    puts $output
    return
}

# Run bigfd

set output [util_start "$srcdir/$subdir/bigfd" "" ""]
puts $output

pass "bigfd"
