#!/usr/bin/env python


if bld.env._SAMBA_BUILD_ == 4:
    bld.SAMBA_SUBSYSTEM('CHARSET',
                        source='charcnv.c util_unistr.c',
                        public_deps='CODEPOINTS',
                        public_headers='charset.h',
                        )

bld.SAMBA_SUBSYSTEM('ICONV_WRAPPER',
                    source='iconv.c',
                    public_deps='iconv replace talloc')

bld.SAMBA_SUBSYSTEM('CODEPOINTS',
	source='codepoints.c',
	deps='DYNCONFIG ICONV_WRAPPER'
	)
