#! /bin/sh
BR=${1:-"br549"}

# fetch ip of working br0
IP=`/sbin/ifconfig $BR | sed -n -e 's/^.*inet addr:\([0-9][0-9\.]*\).*$/\1/p'`
echo "Using IP address $IP"

ifconfig $BR down
brctl delbr $BR
ifconfig eth0 172.20.5.22
rmmod bridge
