#!/bin/sh

. ../support/simple_eval_tools.sh

HEADER TLS-TCP Transport

SKIPIFNOT NETSNMP_TRANSPORT_DTLSUDP_DOMAIN

#
# Begin test
#

SNMP_TRANSPORT_SPEC=tlstcp
export SNMP_TRANSPORT_SPEC
export SNMP_SNMPD_PORT
export SNMP_TEST_DEST

. ./Stlstests
