
#ifndef __nt_eInfo_h__
#define __nt_eInfo_h__

/* NOTIFY CENTER EVENT MAPPING INFO STRUCTURE
---------------------------------*/
struct eInfo {
	char	*eName;
	int	value;
};

struct eInfo mapInfo[] =
{
	/* RESERVATION EVENT */
	{"RESERVATION_MAIL_SUCCESS_EVENT"      ,RESERVATION_MAIL_REPORT_EVENT},
	{"RESERVATION_MAIL_CONFIRM_EVENT"      ,RESERVATION_MAIL_CONFIRM_EVENT},
	/* WAN EVENT */
	{"WAN_DISCONN_EVENT"                   ,WAN_DISCONN_EVENT},
	{"WAN_BLOCK_EVENT"                     ,WAN_BLOCK_EVENT},
	/* PASSWORD EVENT */
	{"PASSWORD_SAME_WITH_LOGIN_WIFI_EVENT" ,PASSWORD_SAME_WITH_LOGIN_WIFI_EVENT},
	{"PASSWORD_WIFI_WEAK_EVENT"            ,PASSWORD_WIFI_WEAK_EVENT},
	{"PASSWORD_LOGIN_STRENGTH_CHECK_EVENT" ,PASSWORD_LOGIN_STRENGTH_CHECK_EVENT},
	/* GUEST NETWORK EVENT */
	{"GUESTWIFI_ONE_ENABLE_EVENT"          ,GUESTWIFI_ONE_ENABLE_EVENT},
	{"GUESTWIFI_MORE_ENABLE_EVENT"         ,GUESTWIFI_MORE_ENABLE_EVENT},
	/* RSSI EVENT */
	{"RSSI_LOW_SIGNAL_EVENT"               ,RSSI_LOW_SIGNAL_EVENT},
	{"RSSI_LOW_SIGNAL_AGAIN_EVENT"         ,RSSI_LOW_SIGNAL_AGAIN_EVENT},
	/* DUALWAN EVENT */
	{"DUALWAN_FAILOVER_EVENT"              ,DUALWAN_FAILOVER_EVENT},
	{"DUALWAN_FAILBACK_EVENT"              ,DUALWAN_FAILBACK_EVENT},
	/* LOGIN EVENT */
	{"LOGIN_FAIL_LAN_WEB_EVENT"            ,LOGIN_FAIL_LAN_WEB_EVENT},
	{"LOGIN_FAIL_WAN_WEB_EVENT"            ,LOGIN_FAIL_WAN_WEB_EVENT},
	{"LOGIN_FAIL_SSH_EVENT"                ,LOGIN_FAIL_SSH_EVENT},
	{"LOGIN_FAIL_TELNET_EVENT"             ,LOGIN_FAIL_TELNET_EVENT},
	{"LOGIN_FAIL_SSID_EVENT"               ,LOGIN_FAIL_SSID_EVENT},
	{"LOGIN_FAIL_AICLOUD_EVENT"            ,LOGIN_FAIL_AICLOUD_EVENT},
	{"LOGIN_DEVICE_DOUBLE_EVENT"           ,LOGIN_DEVICE_DOUBLE_EVENT},
	{"LOGIN_ACCOUNT_DOBLE_EVENT"           ,LOGIN_ACCOUNT_DOBLE_EVENT},
	{"LOGIN_FAIL_VPNSERVER_EVENT"          ,LOGIN_FAIL_VPNSERVER_EVENT},
	/* PROTECTION EVENT */
	{"PROTECTION_INTO_MONITORMODE_EVENT"   ,PROTECTION_INTO_MONITORMODE_EVENT},
	{"PROTECTION_VULNERABILITY_EVENT"      ,PROTECTION_VULNERABILITY_EVENT},
	{"PROTECTION_CC_EVENT"                 ,PROTECTION_CC_EVENT},
	{"PROTECTION_DOS_EVENT"                ,PROTECTION_DOS_EVENT},
	/* PARENTAL CONTROL EVENT */
	{"PROTECTION_DOS_EVENT"                ,PROTECTION_DOS_EVENT},
	/* TRAFFIC METER EVENT */
	{"TRAFFICMETER_CUTOFF_EVENT"           ,TRAFFICMETER_CUTOFF_EVENT},
	{"TRAFFICMETER_ALERT_EVENT"            ,TRAFFICMETER_ALERT_EVENT},
	{"TRAFFICMETER_BW_LIMITER_EVENT"       ,TRAFFICMETER_BW_LIMITER_EVENT},
	/* FIRMWARE EVENT */
	{"FIRMWARE_NWE_VERSION_AVAILABLE_EVENT",FIRMWARE_NWE_VERSION_AVAILABLE_EVENT},
	{"FIRMWARE_UPDATE_EVENT"               ,FIRMWARE_UPDATE_EVENT},
	/* USB EVENT */
	{"USB_DM_TASK_FINISHED_EVENT"          ,USB_DM_TASK_FINISHED_EVENT},
	{"USB_DISK_SCAN_FAIL_EVENT"            ,USB_DISK_SCAN_FAIL_EVENT},
	{"USB_DISK_EJECTED_FAIL_EVENT"         ,USB_DISK_EJECTED_FAIL_EVENT},
	{"USB_DISK_PARTITION_FULL_EVENT"       ,USB_DISK_PARTITION_FULL_EVENT},
	{"USB_DISK_FULL_EVENT"                 ,USB_DISK_FULL_EVENT},
	/* HINT EVENT */
	{"HINT_USB_CHECK_EVENT"                ,HINT_USB_CHECK_EVENT},
	{"HINT_USB_FIRSTIME_CHECK_EVENT"       ,HINT_USB_FIRSTIME_CHECK_EVENT},
	{"HINT_SAMBA_INLAN_EVENT"              ,HINT_SAMBA_INLAN_EVENT},
	{"HINT_OSX_INLAN_EVENT"                ,HINT_OSX_INLAN_EVENT},
	{"HINT_DUALBAND_WITHOUT_5G_EVENT"      ,HINT_DUALBAND_WITHOUT_5G_EVENT},
	{"HINT_USB3_WITHOUT_ENHANCE_EVENT"     ,HINT_USB3_WITHOUT_ENHANCE_EVENT},
	{"HINT_XBOX_PS_EVENT"                  ,HINT_XBOX_PS_EVENT},
	{"HINT_UPNP_RENDERER_EVENT"            ,HINT_UPNP_RENDERER_EVENT},
	{"HINT_DETECT_GAME_SERVICE_EVENT"      ,HINT_DETECT_GAME_SERVICE_EVENT},
	/* The End */
	{0,0}
};

#endif
