#!/bin/bash
#
# Copyright (C) 2011 Karel Zak <kzak@redhat.com> 
# 

test -f mount/mount.c || {
	echo
	echo "You must run this script in the top-level util-linux directory"
	echo
	exit 1
}

. tools/config-gen-functions.sh

while [ -n "$1" ]; do
	opts="$opts $(ul_get_configuration tools/config-gen.d/$1.conf)"
	shift
done

opts=$(echo $opts | tr " " "\n" | sort -u)
echo "Configure options:"
for x in $opts; do
	echo "	$x"
done
if [ -n "$CFLAGS" ]; then
	echo "CFLAGS:	$CFLAGS"
	export CFLAGS="$CFLAGS"
fi

echo
./configure $opts
