.TH RSTPCTL 8 "August 20, 2006" "" ""
.SH NAME
rstpd \- Daemon implementing Rapid Spanning Tree Protocol for Linux
bridges.
.SH SYNOPSIS
.BR "rstpd [\-d] [\-v <level>]"
.SH DESCRIPTION
.B rstpd
implements the Rapid Spanning Tree Protocol (RSTP) on Linux
bridges. When started, it merely monitors the ethernet bridges on the
machine until instructed to run RSTP on any of them using
.BR rstpctl .
When run with the
.BR "\-d"
option, it runs in the foreground and outputs messages which are
normally logged through syslog to standard output and standard
error. With the
.BR "\-v"
option, the level of verbosity of the logs can be controlled.
See
.BR rstpctl (8)
for more information on configuring RSTP. 

.SH SPANNING TREE PROTOCOL
Multiple ethernet bridges can work together to create even larger
networks of ethernets using the IEEE 802.1d spanning tree
protocol. This protocol is used for finding the shortest path between
two ethernets, and for eliminating loops from the topology. As this
protocol is a standard, linux bridges will interwork properly with
other third party bridge products. Bridges communicate with eachother
by sending and receiving BPDUs (Bridge Protocol Data Units). These
BPDUs can be recognised by an ethernet destination address of
01:80:c2:00:00:00.

The spanning tree protocol can also be turned off (for those
situations where it just doesn't make sense, for example when this
linux box is the only bridge on the LAN, or when you know that there
are no loops in the topology.)

The 2004 version of the 802.1D specification describes the Rapid
Spanning Tree Protocol, which supercedes the older Spanning Tree
Protocol while providing for backward compatible operation with it.
It provides for faster reconfiguration during network changes than
STP in many cases.

.SH NOTES
TODO: Indicate lack of persistence of configuration across restarts of
daemon.

.SH SEE ALSO
.BR rstpctl(8),
.BR brctl(8)

.SH COPYRIGHT
This manual page Copyright (c) 2006 EMC Corporation.

This manual page is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the Free 
Software Foundation; either version 2 of the License, or (at your option) 
any later version. It comes with NO WARRANTY.
.\" The full GNU General Public License is included in this distribution in the
.\" file called LICENSE.

.SH AUTHOR
Srinivas Aji <Aji_Srinivas@emc.com>
