#
# Makefile for plugins on Solaris 2
#
# $Id: Makefile.sol2,v 1.1.1.4 2003/10/14 08:09:53 sparq Exp $
#

include ../../svr4/Makedefs

CFLAGS	= -c -O -I.. -I../../include $(COPTS)
LDFLAGS	= -G 

all:	minconn.so

minconn.so: minconn.o
	ld -o $@ $(LDFLAGS) -h $@ minconn.o

minconn.o: minconn.c
	$(CC) $(CFLAGS) -c $? 

passprompt.so: passprompt.o
	ld -o $@ $(LDFLAGS) -h $@ passprompt.o

passprompt.o: passprompt.c
	$(CC) $(CFLAGS) -c $?

clean:
	rm -f *.o *.so
