.\"
.\" Version 1.4 of namei
.\"
.TH NAMEI 1 "June 2011" "util-linux" "User Commands"
.SH NAME
namei \- follow a pathname until a terminal point is found
.SH SYNOPSIS
.B namei
.RI [ options ]
.IR  pathname ...
.SH DESCRIPTION
.B namei
uses its arguments as pathnames to any type
of Unix file (symlinks, files, directories, and so forth).
.B namei
then follows each pathname until an endpoint
is found (a file, a directory, a device node, etc).
If it finds a symbolic link, it shows the link, and starts
following it, indenting the output to show the context.
.PP
This program is useful for finding "too many levels of
symbolic links" problems.
.PP
For each line of output,
.B namei
uses the following characters to identify the file type found:
.LP
.nf
   f: = the pathname currently being resolved
    d = directory
    l = symbolic link (both the link and its contents are output)
    s = socket
    b = block device
    c = character device
    p = FIFO (named pipe)
    - = regular file
    ? = an error of some kind
.fi
.PP
.B namei
prints an informative message when
the maximum number of symbolic links this system can have has been exceeded.
.SH OPTIONS
.IP "\fB\-l, \-\-long\fP"
Use the long listing format (same as -m -o -v).
.IP "\fB\-m, \-\-modes\fP"
Show the mode bits of each file type in the style of ls(1),
for example 'rwxr-xr-x'.
.IP "\fB\-o, \-\-owners\fP"
Show owner and group name of each file.
.IP "\fB\-n, \-\-nosymlinks\fP"
Don't follow symlinks.
.IP "\fB\-v, \-\-vertical\fP"
Vertically align the modes and owners.
.IP "\fB\-x, \-\-mountpoints\fP"
Show mountpoint directories with a 'D' rather than a 'd'.
.IP "\fB\-h\fR, \fB\-\-help\fR"
Output help text and exit.
.IP "\fB\-V\fR, \fB\-\-version\fR"
Output version information and exit.
.SH AUTHOR
The original
.B namei
program was written by Roger Southwick <rogers@amadeus.wr.tek.com>.

The program was re-written by Karel Zak <kzak@redhat.com>.
.SH BUGS
To be discovered.
.SH "SEE ALSO"
.BR ls (1),
.BR stat (1)
.SH AVAILABILITY
The namei command is part of the util-linux package and is available from
ftp://ftp.kernel.org/pub/linux/utils/util-linux/.
