.\" Copyright 1999 Andreas Dilger (adilger@enel.ucalgary.ca)
.\"
.\" This man page was created for libuuid.so.1.1 from e2fsprogs-1.14.
.\"
.\" This file may be copied under the terms of the GNU Public License.
.\"
.\" Created  Wed Mar 10 17:42:12 1999, Andreas Dilger
.TH UUIDGEN 1 "June 2011" "util-linux" "User Commands"
.SH NAME
uuidgen \- create a new UUID value
.SH SYNOPSIS
.B uuidgen
[\fIoptions\fR]
.SH DESCRIPTION
The
.B uuidgen
program creates (and prints)
a new universally unique identifier (UUID) using the
.BR libuuid (3)
library.  The new UUID can reasonably be considered unique among
all UUIDs created on the local system,
and among UUIDs created on other systems in the past
and in the future.
.PP
There are two types of UUIDs which
.B uuidgen
can generate: time-based UUIDs and random-based UUIDs.  By default
.B uuidgen
will generate a random-based UUID if a high-quality random number
generator is present.  Otherwise, it will choose a time-based UUID.
It is possible to force the generation of one of these two
UUID types by using the
.B \-r
or
.B \-t
options.
.SH OPTIONS
.TP
.BR \-r , " \-\-random"
Generate a random-based UUID.  This method creates a UUID consisting mostly
of random bits.  It requires that the operating system have a high
quality random number generator, such as
.IR /dev/random .
.TP
.BR \-t , " \-\-time"
Generate a time-based UUID.  This method creates a UUID based on the system
clock plus the system's ethernet hardware address, if present.
.TP
.BR \-h , " \-\-help"
Display help text and exit.
.TP
.BR \-V , " \-\-version"
Display version information and exit.
.SH "CONFORMING TO"
OSF DCE 1.1
.SH AUTHOR
.B uuidgen
was written by Andreas Dilger for libuuid.
.SH AVAILABILITY
The uuidgen command is part of the util-linux package and is available from
ftp://ftp.kernel.org/pub/linux/utils/util-linux/.
.SH "SEE ALSO"
.BR libuuid (3)
